MOL-162
arkivverket/mottak pull request #101
Opened 2021-01-07 16:18 UTC by omBratteng

2021-01-08 10:28 UTC, elmgren requested changes
Bra oversiktlig kode. 
Har laget suggestions på små feil som jeg ser i min IDE. Som at det skal vare 2 rader mellom metoder etc. 

Men les gjennom kommentarene så kan vi ta en samtale om det etterpå.

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +
```suggestion


```

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +    Exception raised when
Mangler forklaring her.

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +from app.connectors.sas_generator.sas_generator_client import SASGeneratorClient
Denne er ikke i bruk

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +from app.routers.router_dependencies import get_db_session, get_mailgun_domain, get_mailgun_secret, get_tusd_url, get_sas_url
get_sas_url er ikke i bruk

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +class BestillNedlastning(BaseModel):
Tror ikke vi trenger denne om det kun er status som skal sendes tilbake. Det får vi automatisk ut fra HTTP metoden som er brukt. Dvs. Post -> 200 Get -> 201.

2021-01-08 10:28 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +             response_model=BestillNedlastning,
Se kommentar om BestillNedlasting.

Tror man kan slette denne hvis det kun er status som skal sendes tilbake.

2021-01-08 15:17 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +
Har aktivert korrekt linter nå, `pep8` har tydeligvis byttet navn til `pycodestyle`, så nå får jeg disse lint varslingene.

2021-01-08 15:25 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/sas_generator/sas_generator_client.py
> +    async def request_sas(self, container: UUID, duration: int = 24) -> SASResponse:
Det var 24 timer ja

2021-01-08 15:28 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/sas_generator/models.py
> +    def as_data(self) -> dict:
Nei, den trengs ikke egentlig. Så jeg fjerner den.

2021-01-08 16:10 UTC, omBratteng commented on mottak-arkiv-service/app/routers/router_dependencies.py
> +
Enig, var ikke så glad i at jeg la den i router_dependencies, men var usikker hvor andre plasser jeg kunne legge den, så det ble der.

Blir en dårlig navngitt `connectors_variables.py` fil, ikke sikker hvilke andre navn som kan brukes.

2021-01-08 16:46 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/azure_servicebus/azure_servicebus_client.py
> +    def __init__(self):
Det kan jeg gjøre ja. Kan også gjøre den enda mer generisk, ved å endre `request_download` til å være `send_message`, siden det ikke er mye annet spesielt som gjøres.

2021-01-08 16:55 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Bestilling.py
> +class BestillingRequest:
Har endret navn til Arkivkopi

2021-01-11 08:28 UTC, elmgren commented on mottak-arkiv-service/app/connectors/azure_servicebus/azure_servicebus_client.py
> +    def __init__(self):
Høres bra ut med send_message

2021-01-11 08:34 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +             response_model=BestillNedlastning,
Har fjernet den nå, tenkte kanskje det kunne brukes en mer "dynamisk" feilmelding, f.eks dersom den ikke kunne generere sas token, eller fikk ikke sendt melding til service bussen. Men den forblir generisk, og logger heller feil.

2021-01-11 08:34 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    service_bus = AzureServicebus()
Litt usikker på hvordan den kan gjøres, fint om du kunne bistått med det.

2021-01-11 11:20 UTC, elmgren approved these changes

2021-01-11 14:03 UTC, elmgren approved these changes

2021-01-11 14:03 UTC, merged