MOL-791 Use new service bus policies and implement Pydantic settings
arkivverket/mottak pull request #1023
Opened 2021-12-09 15:35 UTC by omBratteng

2021-12-10 11:08 UTC, elmgren requested changes

2021-12-10 11:08 UTC, elmgren commented on mottak-arkiv-service/app/routers/router_dependencies.py
> +            queue_name=settings.archive_download_request_sender_queue_name,
hvorfor er det en trailing komma her? 
Ser at det går igjen i endringene i koden

2021-12-10 11:08 UTC, elmgren commented on mottak-arkiv-service/app/settings.py
> +    da_argo_host: str
hvorfor fjernet du valideringen?

2021-12-14 07:44 UTC, omBratteng commented on mottak-arkiv-service/app/settings.py
> +    da_argo_host: str
Litt fordi integration testing klaget dersom env variablene manglet, da må jeg fylle ut alle variabler i `.env.test` med data.

Og applikasjonen kan også starte fint selv om noen variabler mangler.

2021-12-14 07:49 UTC, omBratteng commented on mottak-arkiv-service/app/routers/router_dependencies.py
> +            queue_name=settings.archive_download_request_sender_queue_name,
Fordi det gjør git diffene enklere.

```diff
@@ -1,3 +1,4 @@
 async with ArchiveDownloadRequestSender(
-        connection_string=settings.azure_service_bus_sender_connection_string.get_secret_value()
+        connection_string=settings.azure_service_bus_sender_connection_string.get_secret_value(),
+        queue_name=settings.archive_download_request_sender_queue_name
 )
```

```diff
@@ -1,3 +1,4 @@
 async with ArchiveDownloadRequestSender(
         connection_string=settings.azure_service_bus_sender_connection_string.get_secret_value(),
+        queue_name=settings.archive_download_request_sender_queue_name,
 )
```

Litt mer visuelle eksempler https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

2021-12-14 08:53 UTC, elmgren commented on mottak-arkiv-service/app/routers/router_dependencies.py
> +            queue_name=settings.archive_download_request_sender_queue_name,
Kan se fordelene ved Git diff og når man flytter verdier runt. 

Men for meg så betyr en dangling comma at listen ikke er ferdig og jeg forventer et verdi etter et komma. Så her handler det for meg om det skal vare entydig kode eller å spare tid ved utvikling av kode. Personligen holder jeg for at koden skal være entydig og enkel heller enn at den skal vare sjappere å utvikle. 

Hvis vi kan ta opp dette for en samtale og vi blir enige om å gjøre det slik så skal jeg ikke være vanskelig. Men synes ikke vi kan gjøre en slik endring i hvordan vi strukturerer kodebasen uten å ta det opp felles først.

2021-12-14 08:59 UTC, elmgren commented on mottak-arkiv-service/app/settings.py
> +    da_argo_host: str
Kan vi heller gi de ikke obligatoriske variablerne default verdier?

Synes vi mister en sterk fordel med BaseSettings hvis vi ikke tar i bruk valideringen

2021-12-14 09:07 UTC, omBratteng commented on mottak-arkiv-service/app/settings.py
> +    da_argo_host: str
For å ikke fylle settings modellen med default verdier som kan skape problemer, og ikke fylle `.env.test`, så kan jeg legge inn en sjekk i validatoren som sjekker om env variablen `CI` er true, så skipper den validering

2021-12-14 09:08 UTC, omBratteng commented on mottak-arkiv-service/app/routers/router_dependencies.py
> +            queue_name=settings.archive_download_request_sender_queue_name,
https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas

2021-12-14 12:48 UTC, elmgren requested changes

2021-12-14 14:20 UTC, omBratteng commented on mottak-arkiv-service/app/settings.py
> +    def validate(cls, value):
Ny validator, `root_validator` gjorde ikke det jeg trudde den skulle

2021-12-14 14:39 UTC, elmgren approved these changes

2021-12-14 14:39 UTC, merged