MOL-741 Transfer azure blob container from Azure Blob Storage to Cloudian
arkivverket/mottak pull request #1029
Opened 2021-12-12 21:30 UTC by ComputasSnorriEngen

TODO:
- Write tests
- Complete README
- dependabot

2021-12-13 20:23 UTC, elmgren requested changes

2021-12-13 20:23 UTC, elmgren commented on transfer-archive/app/connectors/sas_generator/models.py
> +class SASTokenRequest:
Vurdere å bruke pydantic BaseModel her isteden. 

Slipper å lage konstruktor og innebygd X.dict() metode

2021-12-13 20:23 UTC, elmgren commented on transfer-archive/app/main.py
> +def run():
kan endre til 
```
async def run():
    ...
    (fjern loop koden)
    ....


if __name__ == '__main__':
    asyncio.run(run())
```

2021-12-14 07:51 UTC, ComputasSnorriEngen commented on transfer-archive/app/services/tranfer_service.py
> +
Blir det riktig å raise et exception her, eller skal jeg heller ta en sjekk på DownloadStatus der jeg kaller transfer_dataset? 

Dette er årsaken til at workflowen gikk igjennom selv om denne komponenten fikk 403 mot s3

2021-12-14 08:24 UTC, omBratteng requested changes

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/Dockerfile
> +    rm -r rclone-*-linux-${ARCH}
Her blander du inn Alpine som kan skape trøbbel med Debian, selv om det bare bruker til å laste den rclone.
Det er heller ikke nødvendig å rydde vekk zip filer eller slette installerte pakker, siden dette er bare ett foreliggende steg, og blir ikke med inn i final docker image

Samt, så er det ganske unødvendig komplisert å bruke ENV variabler for arch, siden vi alltid vil kjøre på amd64. Ei heller ikke nødvendig med `chmod` eller `chown`. Så du trenger egentlig bare å pakke den ut til en kjent path, som kan kopieres senere.

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/Dockerfile
> +    && chown -R filetransfer:filetransfer /home/filetransfer/.config/rclone
Kan se ut som du har kopiert dette fra arkiv-downloader? 
Der var vi nødt til å lage en egen bruker med UID og GID 1003 fordi den skulle skrive til en nettverks mounted disk, og for at permissions skulle være korrekt. Så her er det unødvendig.

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/README.md
> +- RCLONE_CONFIG_PATH
```suggestion
IAM_ACCESS_KEY_ID
IAM_SECRET_ACCESS_KEY
DATASETT_ID
S3_ENDPOINT_URL
BUCKET_NAME
S3_PATH
AZURE_CONTAINER
AZURE_BASE_URL
SAS_TOKEN
RCLONE_CONFIG_PATH
```

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/README.md
> +- RCLONE_CONFIG_PATH
Kanskje også sortert de alfabetisk?

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/README.md
> +
```suggestion

```

2021-12-14 08:24 UTC, omBratteng commented on transfer-archive/README.md
> +
```suggestion

```

2021-12-14 08:33 UTC, ComputasSnorriEngen commented on transfer-archive/Dockerfile
> +    rm -r rclone-*-linux-${ARCH}
Takk! Forventet en del endringer her, men ville vise til utgangspunktet først.

2021-12-14 08:34 UTC, ComputasSnorriEngen commented on transfer-archive/Dockerfile
> +    && chown -R filetransfer:filetransfer /home/filetransfer/.config/rclone
Det stemmer, jeg mener å huske at jeg var i en situasjon hvor jeg ikke kom utenom dette. Jeg kjører en real refaktorering av Dockerfile og ser.

2021-12-15 08:57 UTC, omBratteng requested changes

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/Dockerfile
> +    cp rclone /usr/bin/
```suggestion
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
		curl \
        unzip \
    && curl -so rclone.zip https://downloads.rclone.org/v${RCLONE_VER}/rclone-v${RCLONE_VER}-linux-amd64.zip \
    && unzip rclone.zip \
    && mv rclone-*-linux-amd64/rclone /usr/bin/rclone
```

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/sas_generator_client.py
> +        self.url = f"http://{sas_generator_host}/generate_sas"
Kunne vi fått endret denne til at `sas_generator_host` heller er `sas_generator_base_url`, slik at vi ikke hardkoder `http` i koden, men heller sender det som ENV variabel

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/app/services/rclone_service.py
> +    return ['rclone', 'copy', azure, s3, '-P']
```suggestion
    return ["rclone", "copy", azure, s3, "-P"]
```

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/README.md
> +`docker run -it --network host --env-file .env mottak/transfer-archive`
```suggestion
### Running docker container

`docker run -it --network host --env-file .env mottak/transfer-archive`
```

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/app/helpers/settings.py
> +    rclone_config_path: str = "/root/.config/rclone/rclone.conf"
Slik som env variablene, kunne disse vært sortert alfabetisk og/eller gruppert etter funksjon?

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/app/helpers/settings.py
> +            raise ValueError("Environment variable can not be empty")
```suggestion
        assert value != '', "Environment variable can not be empty"
```

Nå er ingen av env variablene booleans, men denne valideringen ville slått ut f.eks dersom `s3_path` hadde type `bool` og var satt til `False`.
Så er bedre å `assert value != ''`, fordi da sjekker du kun om det er en empty string, og ikke om det kan være en False boolean

2021-12-15 08:57 UTC, omBratteng commented on transfer-archive/app/helpers/settings.py
> +from pydantic import BaseSettings, validator, SecretStr
Flytt filen rett inn i `app`. Settings er ikke en helper funksjon, men en kritisk del av komponenten

2021-12-15 08:58 UTC, omBratteng commented on transfer-archive/README.md
> +# tranfer-archive
Må ikke glemme denne @ComputasSnorriEngen

2021-12-15 12:36 UTC, ComputasSnorriEngen commented on transfer-archive/app/connectors/sas_generator/sas_generator_client.py
> +        self.url = f"http://{sas_generator_host}/generate_sas"
Støttes, refaktorerer

2021-12-15 12:41 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/sas_generator_client.py
> +        self.url = f"http://{sas_generator_host}/generate_sas"
Da kan du også bruke `AnyHttpUrl` som type i settings. `HttpUrl` er ikke mulig, siden `HttpUrl` krever TLD, og når vi kjører internt i kubernetes, har vi ikke TLD

2021-12-15 13:14 UTC, elmgren requested changes

2021-12-15 13:14 UTC, elmgren commented on transfer-archive/tests/.env.test
> +IAM_ACCESS_KEY_ID=mockAccessKeyId
Skal denne filen ligge på root med øvrige .env filer?

2021-12-15 13:20 UTC, ComputasSnorriEngen commented on transfer-archive/tests/.env.test
> +IAM_ACCESS_KEY_ID=mockAccessKeyId
Den kan godt gjøre det, men den tilhører jo test pakken. Hva foretrekker du?

2021-12-15 16:47 UTC, ComputasSnorriEngen commented on transfer-archive/app/helpers/settings.py
> +    rclone_config_path: str = "/root/.config/rclone/rclone.conf"
Kjører alfabetisk. Ryddigst å forholde seg til

2021-12-15 16:53 UTC, ComputasSnorriEngen commented on transfer-archive/app/settings.py
> +    iam_secret_access_key: str
Måtte fjerne SecretStr her. rclone klager på at verdien blir feil når den leser config fila. Kan det løses på noen måte @omBratteng ?

2021-12-15 17:02 UTC, omBratteng commented on transfer-archive/app/settings.py
> +    iam_secret_access_key: str
Hvor er det du skriver ut access key til config filen?

2021-12-15 17:05 UTC, ComputasSnorriEngen commented on transfer-archive/app/settings.py
> +    iam_secret_access_key: str
transfer-archive/app/helpers/filewriter.py

2021-12-16 10:22 UTC, elmgren commented on transfer-archive/tests/.env.test
> +IAM_ACCESS_KEY_ID=mockAccessKeyId
Liker egentlig å ikke ha alt for mye i root da det blir et sabla ...🥁 🥁 🥁 ... "rot". 

Men ser at vi har .env filer samlet i root i øvrige mottaksløsningen så vi bør sikkert ha det likt

2021-12-16 12:15 UTC, elmgren approved these changes

2021-12-16 12:15 UTC, elmgren commented on transfer-archive/tests/.env.test
> +IAM_ACCESS_KEY_ID=mockAccessKeyId
Da foreslår jeg at vi beholder det her og legger til det å endre .env.test med boyscout rules øvrige steder i koden

2021-12-16 15:25 UTC, omBratteng commented on transfer-archive/app/settings.py
> +    iam_secret_access_key: str
Hmm, skal undersøke

2021-12-16 22:46 UTC, omBratteng requested changes

2021-12-16 22:46 UTC, omBratteng commented on transfer-archive/README.md
> +This container transfers files from Azure Blob Storage to S3 using rclone (LINK)
```suggestion
# transfer-archive

This container transfers files from Azure Blob Storage to S3 using rclone (LINK)  
```

2021-12-16 22:56 UTC, omBratteng commented
Kan se ut som GitHub har noe problemer, får ikke lastet ned dependencies fra github actions, hverken dette repoet eller andre repoer.

2021-12-17 00:27 UTC, omBratteng requested changes
1joy

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/sas_generator_client.py
> +            except HTTPError as err:
Bytt ut `HTTPError` med `RequestError` og `HTTPStatusError`, siden `HTTPError` ikke har attribute `request`, så får man en type error.

```suggestion
from httpx import AsyncClient, RequestError, HTTPStatusError

from app.connectors.sas_generator.exceptions import StorageSASGeneratorRequestFailed
from app.connectors.sas_generator.models import SASTokenRequest, SASResponse

logger = logging.getLogger(__name__)


class SASGeneratorClient:
    def __init__(self, sas_generator_base_url: str):
        self.url = f"{sas_generator_base_url}/generate_sas"

    async def request_sas(self, container_id: str, duration_hours: int = 24) -> Optional[SASResponse]:
        async with AsyncClient() as client:
            request = SASTokenRequest(container=container_id, duration_hours=duration_hours)

            try:
                logger.info(f"Requesting SAS Token from {self.url} with payload: {request.dict()}")
                resp = await client.post(self.url, json=request.dict())
            except (RequestError, HTTPStatusError) as err:
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/services/tranfer_service.py
> +def transfer_data(azure_remote: RcloneAzureConfig, s3_remote: RcloneS3Config):
```suggestion
def transfer_data(azure_remote: RcloneAzureConfig, s3_remote: RcloneS3Config) -> None:
```

Og typo i filnavnet, `tranfer_service` -> `transfer_service`

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/main.py
> +async def run():
```suggestion
async def run() -> None:
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/main.py
> +def _log_startup_info(settings: Settings):
```suggestion
def _log_startup_info(settings: Settings) -> None:
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/services/sas_service.py
> +async def generate_sas_token(container_id: str, sas_generator_client: SASGeneratorClient):
```suggestion
async def generate_sas_token(container_id: str, sas_generator_client: SASGeneratorClient) -> SASResponse:
```
(husk å importere `SASResponse` også

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/services/rclone_service.py
> +async def setup_rclone_remotes(sas_generator_client: SASGeneratorClient):
```suggestion
async def setup_rclone_remotes(sas_generator_client: SASGeneratorClient) -> tuple[RcloneAzureConfig, RcloneS3Config]:
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/services/rclone_service.py
> +                                      endpoint=settings.s3_endpoint_url)
Så får vi med trailing comma
```suggestion
    s3_rclone_config = RcloneS3Config(
        access_key_id=settings.iam_access_key_id,
        secret_access_key=settings.iam_secret_access_key,
        endpoint=settings.s3_endpoint_url,
    )
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/helpers/filewriter.py
> +def write_rclone_config(config: dict):
```suggestion
def write_rclone_config(config: dict) -> None:
```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/models.py
> +            return None
Vurder om denne kan droppes i fordel for [`SASResponse.parse_raw(resp.json())`](https://github.com/arkivverket/mottak/blob/MOL-741_transfer-archive/transfer-archive/app/connectors/sas_generator/sas_generator_client.py#L39)

> [*parse_raw*][1]: this takes a str or bytes and parses it as json, then passes the result to parse_obj. Parsing pickle data is also supported by setting the content_type argument appropriately.

[1]: https://pydantic-docs.helpmanual.io/usage/models/#helper-functions

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/helpers/filewriter.py
> +        logger.error(error)
En mulig løsning for å bruke SecretStr, ref diskusjonen https://github.com/arkivverket/mottak/pull/1029/files#r769811236
```suggestion
import logging

from pydantic import SecretStr

from app.settings import Settings

logger = logging.getLogger(__name__)


def write_rclone_config(config: dict):
    settings = Settings()
    try:
        with open(settings.rclone_config_path, 'a+') as result_file:
            for key in config:
                value = config[key]
                if isinstance(value, SecretStr):
                    value = value.get_secret_value()

                if key == "name":
                    result_file.write(f"\n[{value}]\n")
                else:
                    result_file.write(f"{key} = {value}\n")
    except FileNotFoundError as error:
        logger.error(f"Application failed writing to file with error: {error}")
        raise
    except Exception as error:
        logger.error(error)

```

2021-12-17 00:27 UTC, omBratteng commented on transfer-archive/app/helpers/filewriter.py
> +        logger.error(error)
Utestet såklart 😸 😈

2021-12-17 00:29 UTC, omBratteng requested changes
Du trudde vel ikke at jeg var ferdig med review 😈

2021-12-17 00:29 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/sas_generator_client.py
> +                )
```suggestion
                raise StorageSASGeneratorRequestFailed(
                    f"Kunne ikke nå tjenesten storage-sas-generator med adresse={self.url} for tilgang til Azure storage container {container_id}"
                )
```

2021-12-17 00:34 UTC, ComputasSnorriEngen commented
😅 Bare bra det!

2021-12-17 00:35 UTC, omBratteng commented
Er ferdig nå da, så langt.

2021-12-20 10:52 UTC, ComputasSnorriEngen commented on transfer-archive/app/connectors/sas_generator/models.py
> +            return None
Det kan droppes, men da må vi sende inn `json.dumps(response.json())`

2021-12-20 21:32 UTC, omBratteng commented on transfer-archive/app/connectors/sas_generator/models.py
> +            return None
Eventuelt bare response.text

2021-12-21 08:02 UTC, ComputasSnorriEngen commented on transfer-archive/app/helpers/filewriter.py
> +        logger.error(error)
Testet lokalt og sett at `secret_access_key` skrives dekryptert til config filen

2021-12-21 08:08 UTC, ComputasSnorriEngen commented on transfer-archive/app/connectors/sas_generator/models.py
> -            return None
Fjerning av denne fører så vidt jeg kan se til at SASTokenPreconditionFailed aldri vil forekomme i sas_service.

2021-12-21 10:00 UTC, elmgren commented on transfer-archive/app/connectors/sas_generator/models.py
> -            return None
Hvis SAS returnerer 412 blir den None.

Må beholde SASTokenPreconditionFailed

2021-12-21 13:09 UTC, omBratteng approved these changes

2021-12-21 13:14 UTC, merged