MOL-739 submit-to-preservation workflow without fan-out-fan-in
arkivverket/mottak pull request #1030
Opened 2021-12-12 22:20 UTC by ComputasSnorriEngen

2021-12-16 08:19 UTC, ComputasSnorriEngen commented on kicker/app/workflows/submit-to-preservation.yaml
> +            value: "{{workflow.parameters.DEPOT_INSTITUSJON}}"
Dette må fikses i iam-open-dataset også.

2021-12-16 08:27 UTC, omBratteng commented on kicker/app/workflows/submit-to-preservation.yaml
> +            value: "{{workflow.parameters.DEPOT_INSTITUSJON}}"
Jeg liker ikke ordet `institusjon`, alt for vanskelig å skrive rett på første forsøk

2021-12-16 09:06 UTC, ComputasSnorriEngen commented on kicker/app/workflows/submit-to-preservation.yaml
> +            value: "{{workflow.parameters.DEPOT_INSTITUSJON}}"
og andre forsøk...

2021-12-23 08:23 UTC, elmgren requested changes

2022-01-03 13:20 UTC, elmgren approved these changes

2022-01-05 14:19 UTC, elmgren approved these changes

2022-01-05 14:24 UTC, omBratteng commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +        "S3_ENDPOINT_URL": "https://s3-oslo.arkivverket.no",
Kan disse hentes fra env filen, så slipper vi å eksponere det på internett hva tjenester er navngitt?

2022-01-05 14:24 UTC, omBratteng commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +        "BEVARING_ARKIV_SERVICE_BASE_URL": "http://10.17.136.213/api",
Kan disse hentes fra env filen, så slipper vi å eksponere det på internett hva tjenester er navngitt/ IPer?

2022-01-05 14:27 UTC, elmgren approved these changes

2022-01-05 14:34 UTC, ComputasSnorriEngen commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +        "S3_ENDPOINT_URL": "https://s3-oslo.arkivverket.no",
Absolutt! Fikser

2022-01-05 14:34 UTC, ComputasSnorriEngen commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +        "BEVARING_ARKIV_SERVICE_BASE_URL": "http://10.17.136.213/api",
I fix

2022-01-06 09:39 UTC, omBratteng commented on kicker/app/settings.py
> +    bevaring_arkiv_service_base_url: str
Siden disse er http, kan type være `AnyHttpUrl`

2022-01-06 11:18 UTC, omBratteng approved these changes

2022-01-06 12:22 UTC, elmgren requested changes

2022-01-06 12:22 UTC, elmgren commented on kicker/app/connectors/argo/models.py
> +import os
```suggestion
```

2022-01-06 14:27 UTC, elmgren approved these changes

2022-01-06 14:42 UTC, merged