MOL-215 Save arkivkopi request to the database
arkivverket/mottak pull request #114
Opened 2021-01-13 16:08 UTC by omBratteng

The `pytz` dependency could be dropped if we upgrade to Python 3.9 which has ZoneInfo as a std lib
https://docs.python.org/3.9/library/zoneinfo.html

2021-01-14 08:12 UTC, kriwal-arkivverket requested changes

2021-01-14 08:54 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def convert_to_datetime(datetime_string: str):
Kan vi legge denne i service-klassen?
Foretrekker at repository kun utfør kall mot databasen.

2021-01-14 08:57 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def convert_to_datetime(datetime_string: str):
Tenker du bare selve metoden?

2021-01-14 08:58 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +    sas_token_start = convert_to_datetime(query_string["st"][0])
Eller flytte dette også ut i service klassen @elmgren?

2021-01-14 09:10 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +    sas_token_start = convert_to_datetime(query_string["st"][0])
Flytter vi den over, så flytter vi denne også. Da tenker jeg vi må endre input parameterne. Men jeg tenker kanskje at alt dette kan ligge her. Dette er foreløpig veldig spesifikt for å konvertere ArkivkopiStatus til Arkivkopi_DBO

2021-01-14 09:12 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +    sas_token_start = convert_to_datetime(query_string["st"][0])
Edit, slettet kommentaren. Har ikke sterke meninger om hvor `convert_to_datetime` metoden ligger :)

2021-01-14 11:25 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def convert_to_datetime(datetime_string: str):
Ja slik at man utfør konvertering av sas_token i service layer og sender sas_token_start og sas_token_slutt inn som parametere til repository.

2021-01-14 13:55 UTC, elmgren requested changes

2021-01-14 13:55 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    query_string = parse_qs(sas_token["sas_token"])
Her kan vi kanske ta en metode. 
Legge hele dene delen i en metode, _create_arkivkopi som returnere en arkivkopi (opprettes i domain.models) som du sen sender in til arkivkopi_repository.create

Se hvordan vi har gjort det i arkivuttrekk_repository.create

2021-01-15 10:28 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    query_string = parse_qs(sas_token["sas_token"])
Se siste commit gjort, [`a0664bd` (#114)](https://github.com/arkivverket/mottak/pull/114/commits/a0664bd07923654a4b4cbf5fcb72509d246d5824), forhåpentligvis gjort slik som det er gjort i `arkivuttrekk_repository.create`.

2021-01-15 11:42 UTC, elmgren requested changes

2021-01-15 11:42 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +from datetime import datetime
Har du noen automation eller kortkommando for å fjerne ubrukte imports? 
Ser at datetime og ArkivkopiStatus ikke lenger er i bruk

2021-01-15 12:29 UTC, elmgren approved these changes

2021-01-18 20:01 UTC, merged