MOL-849
arkivverket/mottak pull request #1162
Opened 2022-01-24 20:18 UTC by elmgren

2022-01-31 10:49 UTC, omBratteng commented on kicker/app/connectors/argo/models/ArgoWorkflowResponse.py
> +                                    )
Ville dette sett bedre ut?
```suggestion
        return ArgoWorkflowResponse(
            workflow_name=workflow_name,
            workflow_uid=workflow_uid,
            workflow_type=workflow_type,
            invitasjon_ekstern_id=invitasjon_ekstern_id,
            target_bucket=target_bucket,
            overforingspakke_id=overforingspakke_id,
        )
```

2022-01-31 15:58 UTC, omBratteng requested changes

2022-01-31 15:58 UTC, omBratteng commented on kicker/app/main.py
>  from app.connectors.argo.models import ArgoWorkflow
```suggestion
from app.connectors.argo.models.ArgoWorkflow import ArgoWorkflow
```

2022-01-31 16:09 UTC, omBratteng requested changes

2022-01-31 16:09 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
>      workflow_name: str
Denne kræsjer med mottak, som forventer `workflow_navn`.
Tenker vi bare endrer navn i mottak slik at den heter `workflow_name`, siden det er ikke domenespesifikt, så det kan godt være på engelsk

2022-01-31 16:10 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
>      workflow_name: str
Eventuelt endre den i kicker til å være `workflow_navn` og i `from_argo_workflow_response` så mapper `argo_workflow_response.workflow_name` til `workflow_navn`

2022-01-31 21:12 UTC, elmgren commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
>      workflow_name: str
Done: Endret i mottak til `workflow_name`

2022-01-31 21:13 UTC, elmgren commented on kicker/app/main.py
>  from app.connectors.argo.models import ArgoWorkflow
Done

2022-01-31 21:14 UTC, elmgren commented on kicker/app/connectors/argo/models/ArgoWorkflowResponse.py
> +                                    )
Ja, har endret på en del steder men har en stash jeg kan pushe for å få ryddet opp i dette i hele Kicker og mottak-arkiv-service, men den kan jeg ta i egen task eller til sist i denne.

2022-02-01 13:52 UTC, thomjah-computas requested changes

2022-02-01 13:52 UTC, thomjah-computas commented on mottak-arkiv-service/app/database/dbo/mottak.py
> +    endret: datetime = Column(DateTime(), server_default=func.now(), onupdate=func.current_timestamp(), nullable=False)
now() og current_timestamp() betyr det samme, så det er kaotisk å bruke begge

2022-02-01 13:52 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +async def router_get_workflow_metadata(overforingspakke_id: int,
Er det ønskelig at man skal kunne sende inn en "type" her for å filtrere om man ønsker verifisering eller overføring, eller må det gjøres på klienten?

2022-02-01 13:54 UTC, omBratteng commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +async def router_get_workflow_metadata(overforingspakke_id: int,
Jeg fikser det i MOL-737

2022-02-01 13:56 UTC, omBratteng commented on mottak-arkiv-service/app/database/dbo/mottak.py
> +    endret: datetime = Column(DateTime(), server_default=func.now(), onupdate=func.current_timestamp(), nullable=False)
Endret det.

2022-02-01 14:27 UTC, thomjah-computas approved these changes

2022-02-01 14:27 UTC, merged