MOL-891
arkivverket/mottak pull request #1180
Opened 2022-02-03 09:39 UTC by elmgren

2022-02-03 09:49 UTC, omBratteng commented on kicker/app/connectors/container_tag_params.py
> +        self.save_dataset_in_mottak = {SAVE_DATASET_IN_MOTTAK_TAG: save_dataset_in_mottak}
pydantic modell? 👼🏻

2022-02-03 10:00 UTC, omBratteng commented on save-datasett-in-mottak/Dockerfile
> +FROM python:3.10.2-slim AS prepare
```suggestion
FROM python:3.10.2 AS prepare
```
Ved fremtidige images så kommer jeg til å fjerne `-slim` fra `prepare` steget. Siden det kan være dependencies som trenger f.eks gcc for å bygge wheels, siden det kan ofte ta lang tid før de er tilgjengelig.
Så ved å bruke "non-slim" image, så får vi med bygge verktøy for å bygge wheels

2022-02-03 10:00 UTC, omBratteng commented on save-datasett-in-mottak/Dockerfile
> +FROM python:3.10.2-slim AS prepare
Men runtime, altså lengre ned, kan fortsatt være `-slim` image, siden den ikke trenger å bygge wheels fra tid til annen.

2022-02-03 10:02 UTC, omBratteng commented on save-datasett-in-mottak/app/settings.py
> +    return Settings()
Fint det, meeeeen i en container som kjøres en gang. Er det noe å tjene inn på å cache settings?

2022-02-03 11:01 UTC, elmgren commented on save-datasett-in-mottak/app/settings.py
> +    return Settings()
🙈  litt copy pasta her. Beklager det

2022-02-03 12:25 UTC, elmgren commented on kicker/app/connectors/container_tag_params.py
> +        self.save_dataset_in_mottak = {SAVE_DATASET_IN_MOTTAK_TAG: save_dataset_in_mottak}
Har prøvd å få til dette med pydantic men problem oppstår da man må sette en type på input feltet i modellen.
I denne klassen ønsker vi at `input: str` -> `output: Dict[str, str]` hvilket jeg ikke får til uten en constructor i klassen. 

Har prøvd med lambda funksjoner men får da ikke satt noen type på objektet og resultatet er ikke som ønsket. 

@omBratteng har bedt om hjelp av pydantic community her https://github.com/samuelcolvin/pydantic/discussions/3774

Vi følger opp dette i en senere oppgave og godkjenner versjonen her.

2022-02-03 12:31 UTC, omBratteng commented on kicker/app/workflows/transfer-arkivuttrekk-to-bevaring.yaml
> +      retryStrategy: # hvorfor er det retryStrategy både her og i dag:tasks:?
Fordi den under `dag.tasks[].` ikke gjør noe?

2022-02-03 12:36 UTC, elmgren commented on kicker/app/workflows/transfer-arkivuttrekk-to-bevaring.yaml
> +      retryStrategy: # hvorfor er det retryStrategy både her og i dag:tasks:?
Hehe... sant det var på min todo liste. 
Jeg fjerner de som ligger i dag:tasks. Ser ut som vi har gjort det slikt i øvrige workflows

2022-02-04 08:03 UTC, omBratteng requested changes

2022-02-04 08:03 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/bevaring_datasett_repository.py
> +    db.add(dbo)
```suggestion
    )
    
    db.add(dbo)
```

2022-02-07 09:46 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = "Error"
```suggestion
class WorkflowStatus(str, Enum):
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    ERROR = "Error"
```

2022-02-07 09:46 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = "Error"
Endrer du også andre steder i filen hvor `'` er brukt, til`"`

2022-02-08 12:31 UTC, omBratteng commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +)
Er ikke nødvendig å fikse alle med en gang, med rette de opp når man kommer over de

2022-02-08 19:56 UTC, elmgren commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +)
Fikset noen i forbifarten :)

2022-02-08 19:59 UTC, omBratteng requested changes

2022-02-08 19:59 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    Arkivkopi as Arkivkopi_DBO,
```suggestion
    Arkivuttrekk as Arkivuttrekk_DBO,
    Invitasjon as Invitasjon_DBO,
    Arkivkopi as Arkivkopi_DBO,
```

2022-02-09 08:30 UTC, omBratteng requested changes

2022-02-09 08:30 UTC, omBratteng commented on kicker/.env.default
>  ARGO_HOST=
Kunne du delt det i to grupper, sortert alfabetisk.
Første gruppe er vanlige env variabler, og andre gruppe er env variabler med `_TAG` suffix.

2022-02-09 08:31 UTC, omBratteng commented on kicker/.env.default
>  ARGO_HOST=
Og gjøre det samme i README filen

2022-02-09 08:40 UTC, omBratteng requested changes

2022-02-09 08:40 UTC, omBratteng commented on kicker/app/connectors/argo/models/ArgoWorkflow.py
>          params = {**tag_params.mailer}
```suggestion
        params = {
            **tag_params.mailer,
        }
```
Så får vi det likt mellom de tre :smile:

2022-02-09 08:40 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = "Error"
Ser nå at vi allerede har en enum class for workflow status rett over `WorkflowPhase`. `phase` er det Argo Workflows kaller statusen sin, og det er det vi har brukt i [API endepunktet](https://github.com/arkivverket/mottak/blob/develop/mottak-arkiv-service/app/routers/dto/Workflow.py#L12)

2022-02-09 08:40 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = "Error"
Så vi kan fint fjerne `WorkflowStatus` til fordel for `WorkflowPhase`. Så blir terminologien likt

2022-02-09 08:40 UTC, omBratteng commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +    if workflow_status == WorkflowStatus.SUCCEEDED:
Samme som tidligere kommentar, bytte ut `workflow_status` med `workflow_phase`

2022-02-09 09:43 UTC, elmgren commented on kicker/.env.default
>  ARGO_HOST=
Done

2022-02-09 09:52 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = "Error"
Etter samtale over slack blev vi enige i å beholde begge konsepter da `WorkflowStatus` og `WorkflowPhase` ikke er helt like og blir brukt på forskjellige steder i Argo Workflow. 

Har lagt til kommentar som forklare hvor vi bruker de og hvorfor vi beholder begge konsepter.

2022-02-09 09:52 UTC, elmgren commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +    if workflow_status == WorkflowStatus.SUCCEEDED:
Se kommentar oven.

2022-02-09 09:53 UTC, omBratteng requested changes

2022-02-09 09:53 UTC, omBratteng commented on save-dataset-in-mottak/README.md
> +Create a file named `optional_env_file` which must remain outside version control.
Legg det inn i en `.gitignore` fil i komponenten :)

2022-02-09 10:01 UTC, elmgren commented on save-dataset-in-mottak/README.md
> +Create a file named `optional_env_file` which must remain outside version control.
🙈  done

2022-02-09 12:53 UTC, omBratteng requested changes

2022-02-09 12:53 UTC, omBratteng commented on kicker/app/workflows/transfer-arkivuttrekk-to-bevaring.yaml
> +            memory: 300Mi
Denne trenger ikke så mye ressurser ser jeg for meg

```suggestion
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 192Mi
```

2022-02-09 12:53 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/BevaringDatasett.py
> +    datasett_id: UUID
Er ikke denne optional?

2022-02-09 12:53 UTC, omBratteng commented on save-dataset-in-mottak/README.md
> +WORKFLOW_STATUS=<status of the argo workflow. One of
One of... what?

2022-02-09 12:53 UTC, omBratteng commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +async def _update_arkivuttrekk_status(db: AsyncSession, arkivuttrekk_id: int, workflow_status: str) -> None:
Blir ikke dette korrekt?
```suggestion
async def _update_arkivuttrekk_status(db: AsyncSession, arkivuttrekk_id: int, workflow_status: WorkflowStatus) -> None:
```

2022-02-09 14:19 UTC, elmgren commented on save-dataset-in-mottak/README.md
> +WORKFLOW_STATUS=<status of the argo workflow. One of
... Done

2022-02-09 14:19 UTC, elmgren commented on mottak-arkiv-service/app/jobs/services/workflow_metadata_services.py
> +async def _update_arkivuttrekk_status(db: AsyncSession, arkivuttrekk_id: int, workflow_status: str) -> None:
Jo, men ser at jeg har gjort en feil når jeg oppdatere status i `_save_workflow_of_type_transfer_to_bevaring` tidligere. Ny kode er pushet som inneholder denne suggestion.

2022-02-10 11:14 UTC, merged