MOL-230 Refactor tusd Dockerfile to use poetry to install dependencies
arkivverket/mottak pull request #122
Opened 2021-01-19 15:00 UTC by omBratteng

2021-01-21 14:39 UTC, elmgren requested changes

2021-01-21 14:39 UTC, elmgren commented on tusd/Dockerfile
> +    && apt-get install --no-install-recommends --no-install-suggests -y \
Ser på tidligerare løsning i arkiv-downloader. Er det noen anledning til at vi ikke installerer poetry slik?

 FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN pip install poetry

2021-01-21 14:39 UTC, elmgren commented on tusd/Dockerfile
> +COPY poetry.lock /srv
COPY kan legges på samme rad når de skal til samme path

COPY pyproject.toml poetry.lock /srv

2021-01-21 14:39 UTC, elmgren commented on tusd/Dockerfile
> +RUN poetry config virtualenvs.create false \
Kommentar hører sammen med de ovan som kommer fra løsning i arkiv_downloader

RUN poetry install --no-dev

2021-01-21 19:40 UTC, omBratteng commented on tusd/Dockerfile
> +COPY poetry.lock /srv
Som vi diskuterte, så foretrekker jeg `COPY` på flere linjer, da det gjør det mer oversiktig.

2021-01-22 11:26 UTC, elmgren approved these changes

2021-01-22 11:26 UTC, merged