Mol 164
arkivverket/mottak pull request #123
Opened 2021-01-19 15:11 UTC by elmgren

2021-01-26 08:47 UTC, kriwal-arkivverket requested changes

2021-01-26 08:49 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +        logging.error(f"Fant ikke arkivkopi med id={arkivkopi.arkivkopi_id} å updatere til status={arkivkopi.status}")
Jeg tenker logging kan være engelsk

2021-01-26 21:43 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +        logging.error(f"Fant ikke arkivkopi med id={arkivkopi.arkivkopi_id} å updatere til status={arkivkopi.status}")
Fra samtale 26. Januar. 
Vi skal logge på engelsk. Norsk brukes kun hvis info til sluttbruker

2021-01-26 21:47 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadRequestSender.py
> +        super().__init__(connection_string=get_sender_con_str(), queue_name=REQUEST_SENDER_QUEUE_NAME)
Etter samtale 26. Januar
Miljøvariabler skal opprettes først når de trengs.
Hvis for mange variabler som blir sendt som argumenter bør vi opprette objekter for kall og sende disse. Se implementasjon av Mailgun i router.arkivuttrekk.

2021-01-26 21:48 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadStatusReceiver.py
> +        super().__init__(connection_string=get_status_con_str(), queue_name=STATUS_RECEIVER_QUEUE_NAME)
Se tidligere kommentar

2021-01-26 21:53 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadStatusReceiver.py
> +    async def fetch(self):
Ligger nå i jobs.schedule_status_receiver-job.py.
Kommer ikke på bra navn her. Skal lese kø og updatere arkivkopiStatus hvis melding.
update_arkivkopi_status_if_message_on_queue føles litt langt :)

2021-01-26 21:55 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadStatusReceiver.py
> +                update_arkivkopi_status(arkivkopi_status_response, self.db)
Etter samtale 26. Januar

Har et nytt oppsett der vi har løst denne avhengigheten. Den som gjenstår er at connectors har en avhengighet til ArkivkopiStatus som ligger i domain. Se kommentar på lucidchart tegning

2021-01-28 21:49 UTC, elmgren commented on mottak-arkiv-service/tests/connectors/arkiv_downloader/test_models.py
> +    arkivkopi_request_2 = ArkivkopiRequest(arkivkopi_id, storage_account, container, sas_token)
bruke actual og expected?
Ser at det ikke funker overalt men actual istedet for result

2021-01-28 21:49 UTC, elmgren commented on mottak-arkiv-service/tests/connectors/arkiv_downloader/test_models.py
> +    expected = json.dumps(arkivkopi_request.__dict__)
Generelt spørsmål på hvordan vi skal utføre enhetstester. 

Ok å bruke objektet som vi tester på i expected eller skal vi opprette expected eksplisitt i testen? Grunnen til den mer jobbige måten å gjøre det på er økt lesbarhet hvis et test feiler i fremtiden. 

Eksempel fra denne testen. 
```
expected = {
    "arkivkopi_id": 1, 
    "storage_account": "dasaccdev", 
    "container": "33e8d091-48fd-4718-9c7a-abb9a266ee8f", 
    "sas_token": "st=2021-01-28T12%3A44%3A26Z&se=2021-01-29T00%3A59%3A26Z&sp=rl&sv=2020-02-10&sr=c&sig=IGAxVlPEF1Y%2B6Xh9mCEa90Dtq8VXP3GVJaa2f/5P%2BMA%3D"
}
```

2021-01-29 07:13 UTC, kriwal-arkivverket commented on mottak-arkiv-service/alembic/versions/45a842b264e5_add_new_arkivkopi_status.py
> +    with op.get_context().autocommit_block():
- Vanligvis kjører alembic hele changeloggen i en commit, mao alt eller ingenting. Men dette er en type operasjon som må gjøres i en commit.

- Da feiler det :p

2021-01-29 07:13 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadRequestSender.py
> +        return await super().send_message(arkivkopi_request.as_json_str())
Her kan vi bruke både self og super, men på den under kan vi ikke det.

2021-01-29 07:13 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadStatusReceiver.py
> +        messages = await super().receive_messages()
Her kan vi bruke self, fordi self da vil peke samme metode som kallet gjøres fra.

2021-01-29 07:13 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def get_by_arkivuttrekk_id_newest(db: Session, arkivuttrekk_id) -> Arkivkopi_DBO:
Jeg lurte på det, men er det ikke vanligere i "databasespråk" og si `get_by_<column>_<filter/orderby>`?

2021-01-29 07:13 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    request_sent = await archive_download_request_client.send_download_request(sas_token, arkivkopi.id)
Tror det, skal teste litt

2021-01-29 08:33 UTC, kriwal-arkivverket commented on mottak-arkiv-service/alembic/versions/45a842b264e5_add_new_arkivkopi_status.py
> +    with op.get_context().autocommit_block():
Etter diskusjon, vi sletter raden hvis vi ikke klarer å legge bestilling på kø.

2021-01-29 08:46 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/arkiv_downloader/queues/ArchiveDownloadRequestSender.py
> +        return await super().send_message(arkivkopi_request.as_json_str())
Vi kan ikke bruke static, pga behov for at kø navn og connection string er satt opp i parent.

2021-01-29 13:09 UTC, elmgren reviewed
Ser veldig bra ut.

2021-01-29 13:32 UTC, omBratteng approved these changes

2021-01-29 13:39 UTC, merged