MOL-977
arkivverket/mottak pull request #1260
Opened 2022-03-10 20:12 UTC by ComputasSnorriEngen

2022-03-11 08:28 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Jeg oppdaget denne, `constr` https://pydantic-docs.helpmanual.io/usage/types/#constrained-types
Kanskje `constr(min_length=1)` kan funke, og trenger ikke validator?

2022-03-11 08:33 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +        assert value != "", f"Field arkivskaper_kontaktperson can not be empty"
Kan ikke hard-kode arkivskaper_kontaktperson når det validerer flere felter. Var det begynnelsen på en formattering-streng som ble glemt?

2022-03-14 07:22 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +        assert value != "", f"Field arkivskaper_kontaktperson can not be empty"
🎯

2022-03-14 07:22 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Jeg tar en titt på det

2022-03-14 08:04 UTC, thomjah-computas approved these changes

2022-03-14 08:21 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Hva med `Optional[constr(min_length=1)]`? Da forsikrer man seg at det ikke kommer en tom streng der også

2022-03-14 08:22 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Lurt.

2022-03-14 08:23 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
😉

2022-03-14 08:25 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Det kan bli problematisk - man må passe på hva klienten sender inn, siden et input tekst-felt ikke har en formening om None eller tom streng. Ref det jeg sa på Slack, kanskje serveren ønsker å normalisere slik at tom streng (for Optional) blir til NULL i databasen?

2022-03-14 08:39 UTC, omBratteng approved these changes

2022-03-14 08:40 UTC, omBratteng requested changes

2022-03-14 08:40 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +from pydantic.types import constr
```suggestion
from pydantic import BaseModel, constr
```

2022-03-14 09:01 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Hva om vi gir Optionals `None` som default?

2022-03-14 09:02 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Det funker

2022-03-14 10:03 UTC, omBratteng approved these changes

2022-03-14 11:30 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
"Det funker" as in "er JSON input `system: ''` så blir det `system==None` i request objektet"?

2022-03-14 11:49 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Nei, da er det en tom streng og ValidationError blir løftet

2022-03-14 11:54 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
>      arkivbeskrivelse: Optional[str]
Hva sender klienten for tomme felter i dag?

2022-03-15 14:23 UTC, thomjah-computas approved these changes

2022-03-15 14:23 UTC, merged