MOL-942
arkivverket/mottak pull request #1261
Opened 2022-03-14 09:54 UTC by elmgren

2022-03-14 12:34 UTC, omBratteng requested changes

2022-03-14 12:34 UTC, omBratteng commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        return arkivbeskrivelse
```suggestion
        arkivbeskrivelse = [
            record.text
            for record in _get_altRecordID_elements(root, ns)
            if record.get("TYPE") == "DELIVERYSPECIFICATION"
        ].pop()
        return arkivbeskrivelse
```

2022-03-14 12:34 UTC, omBratteng commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        return arkivbeskrivelse
Samt andre steder

2022-03-14 15:45 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        return arkivbeskrivelse
Etter samtale over slack ble vi enige i følgende oppsett
```
def _get_arkivbeskrivelse(root: ET.Element, ns: dict) -> Optional[str]:
    return None
    """
    Sought: a description of the archive.
    Can be found in a child element of an <mets:altRecordID> with TYPE="DELIVERYSPECIFICATION"
    """
    try:
        arkivbeskrivelse = [
            record.text for record in _get_altRecordID_elements(root, ns) if record.get("TYPE") == "DELIVERYSPECIFICATION"
        ].pop()
        return arkivbeskrivelse
    except IndexError:
        return None
```

Hvis if-satsen ikke får plass på en rad legges den på egen rad under

2022-03-15 15:17 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    def get_if_value_is_member(cls, value_str) -> Optional[Uttrekksformat]:
```suggestion
    def get_if_value_is_member(cls, value_str: str) -> Optional[Uttrekksformat]:
```

2022-03-15 15:18 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/domain/xmlparser.py
> +    pass
Glemt å fjerne denne?

2022-03-15 15:27 UTC, ComputasSnorriEngen requested changes
Er det en grunn til at vi bruker enkel-fnutt og ikke dobbel i xmlparser.py?

2022-03-16 09:43 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +    pass
Ja 🙈

2022-03-17 10:40 UTC, ComputasSnorriEngen approved these changes

2022-03-17 13:06 UTC, omBratteng approved these changes

2022-03-17 14:28 UTC, merged