MOL-944
arkivverket/mottak pull request #1293
Opened 2022-03-15 14:06 UTC by elmgren

2022-03-18 08:04 UTC, thomjah-computas requested changes
Kan ikke se at denne PRen oppfyller oppgavens gjøremål, som er at komponenten iam-open-dataset fyller inn nye felter til bevaring-arkiv-service.

2022-03-22 09:37 UTC, elmgren commented
@thomjah-computas 
Stemmer det. Hadde misforstått scope av denne tasken og trodde at utvikling av kicker og iam-open-datasett skulle utføres i en annen oppgave. 

Har nå lagt til dette.

2022-04-04 07:38 UTC, thomjah-computas commented on iam-open-dataset/app/domain/models.py
> +    aktor: Optional[str]
Selv om det å sende riktig aktør ikke er i scope i denne storyen, så matcher ikke `aktor` her med feltene som bevaring-arkiv-service forventer.

2022-04-04 07:38 UTC, thomjah-computas commented on iam-open-dataset/app/domain/models.py
> +    aktor: Optional[str]
Selv om det å sende riktig aktør ikke er i scope i denne storyen, så matcher ikke `aktor` her med feltene som bevaring-arkiv-service forventer.

2022-04-04 08:19 UTC, elmgren commented on iam-open-dataset/app/domain/models.py
> +    aktor: Optional[str]
Takk. Jeg sender ikke inn feltet lenger fra Kicker lenger men glemte å fjerne det her

Done

2022-04-05 07:21 UTC, omBratteng commented on kicker/app/workflows/transfer-arkivuttrekk-to-bevaring.yaml
> +            value: "{{workflow.parameters.MERKELAPP}}"
Noen plasser er det `workflow.parameters.MERKELAPP` og andre er det `workflow.parameters.ARKIVUTTREKK_MERKELAPP`

2022-04-06 08:50 UTC, elmgren commented on kicker/app/workflows/transfer-arkivuttrekk-to-bevaring.yaml
> +            value: "{{workflow.parameters.MERKELAPP}}"
Ja, disse navnene blir brukt i de andre workflows. 
Har endret slik at 
`ARKIVUTTREKK_MERKELAPP/TITTEL ->  MERKELAPP`
`ARKIVUTTREKK_OBJ_ID -> OBJEKT_ID`

2022-04-07 05:42 UTC, omBratteng approved these changes

2022-04-07 10:21 UTC, thomjah-computas requested changes

2022-04-08 09:38 UTC, thomjah-computas commented on iam-open-dataset/app/domain/models.py
> -    depot_institusjon: str
Siden det ikke blir brukt, godtar vi at det ikke er en del av response-modellen

2022-04-08 09:38 UTC, thomjah-computas approved these changes

2022-04-08 09:38 UTC, merged