MOL-1120 Inject aktor into overførings params from Authorization header
arkivverket/mottak pull request #1582
Opened 2022-06-02 11:50 UTC by omBratteng

2022-06-03 09:19 UTC, thomjah-computas requested changes

2022-06-03 09:19 UTC, thomjah-computas commented on mottak-arkiv-service/app/authentication.py
> +def get_aktor_from_authz_token(
Hvis man skiller dependency injection fra FastAPI og token-prosessering i to funksjoner, så kan man enkelt lage en unit test for å prosessere token til Aktor. Da kan man teste at feil-scenarioer gir riktig HTTP-kode, for eksempel

2022-06-03 09:42 UTC, omBratteng commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +    aktor: Aktor = Depends(get_aktor_from_authz_token),
Ja, veldig digg med dependencies og sub-dependencies
https://fastapi.tiangolo.com/tutorial/dependencies/sub-dependencies/

2022-06-03 09:53 UTC, omBratteng commented on mottak-arkiv-service/app/routers/services/overforingspakke_service.py
> +    aktor: Aktor,
Tenker du på hele `_get_transfer_to_bevaring_params`?

2022-06-03 12:41 UTC, omBratteng commented
Da har jeg laget to tester, en for `_get_transfer_to_bevaring_params` og en for authz metoder

2022-06-06 10:17 UTC, thomjah-computas approved these changes

2022-06-06 10:18 UTC, merged