Mol 285
arkivverket/mottak pull request #161
Opened 2021-02-07 20:54 UTC by elmgren

I couldn't think of a good name for the DataFromDatabase class. Suggestions are happily accepted

2021-02-09 12:37 UTC, kriwal-arkivverket requested changes

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
> +        'SUBMITTER_NAME': data_from_db.avgiver_navn,
Jeg har nettopp vært på møte med Rolf (sjefsarkitekt) og Petr, hvor de presenterte https://arkivverket.atlassian.net/wiki/spaces/ARK/pages/1881669932/Akt+rer+og+roller. Der defineres rollen avgiver. Så da synes jeg vi skal bruke avgiver og ikke submitter. Og hva er årsaken til at vi bytter fra norske navn til engelske her?

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
> +        # THESE ARE NEW KEYS, REMOVE UNUSED AFTER ALL MOL-284 CHANGES ARE DONE IN KICKER AND ENTAILING COMPONENTS
Jeg skulle gjerne sett at vi også sendte med koordinator, ettersom jeg regner med at vi i begynnelsen nå, ønsker å varsle koordinator og ikke avgiver.

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
>      connection = my_connect(os.getenv('DBSTRING'), logger=logging)
gir det mening å flytte kallet til my_connect og my_disconnect inn i get metadata?
det vil da selvfølgelig gjelde fra alle hooks, og ikke bare post_finish

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/models/DataFromDatabase.py
> +    def __init__(self,
type hints på variablene?

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/models/DataFromDatabase.py
> +from __future__ import annotations
Jeg heller kanskje mot at pakken models, egentlig burde ligge under implementations. Hva tenker du?

2021-02-09 12:37 UTC, kriwal-arkivverket commented on tusd/hooks/models/HookData.py
> +                 tusd_id=None,
type hints på variablene?

2021-02-09 19:35 UTC, elmgren commented on tusd/hooks/README.md
> +General information about the hook event JSON document
Done

2021-02-09 20:09 UTC, elmgren commented on tusd/hooks/implementations/hooks_utils.py
> +            'a.avgiver_epost        AS avgiver_epost, '
Done

2021-02-09 21:14 UTC, elmgren commented on tusd/hooks/implementations/post_create.py
> +    metadata = get_metadata(connection, hook_data.ekstern_id, logging)
Done

2021-02-09 21:15 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
> +        'SUBMITTER_NAME': data_from_db.avgiver_navn,
Følgte eksisterende oppsett der params var på engelsk. Ikke noen begrunnelse mao. så jeg endrer nesten alle nye params til å ha norske navn.

2021-02-09 21:15 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
> +        # THESE ARE NEW KEYS, REMOVE UNUSED AFTER ALL MOL-284 CHANGES ARE DONE IN KICKER AND ENTAILING COMPONENTS
Done

2021-02-09 21:30 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
>      connection = my_connect(os.getenv('DBSTRING'), logger=logging)
Tenkte også på det men såg at vi trenger i så fall håndtere slik at vi har en connection ved kall til add_overforingspakke_to_db og update_overforingspakke_to_db

2021-02-09 21:34 UTC, elmgren commented on tusd/hooks/models/DataFromDatabase.py
> +from __future__ import annotations
Enig. Done

2021-02-09 21:44 UTC, elmgren commented on tusd/hooks/models/DataFromDatabase.py
> +    def __init__(self,
Done

2021-02-09 21:45 UTC, elmgren commented on tusd/hooks/models/HookData.py
> +                 tusd_id=None,
Done

2021-02-10 07:23 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
>      connection = my_connect(os.getenv('DBSTRING'), logger=logging)
Ok, tror jeg har vært igjennom samme tankerekka selv tidligere :) Vi lar det være for nå, så vokser ikke pr noe større.

2021-02-10 09:47 UTC, kriwal-arkivverket requested changes

2021-02-10 09:47 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/models/DataFromDatabase.py
> +        ekstern_id = metadata.get('ekstern_id')
`metadata.get('ekstern_id')` returnerer denne str eller UUID? (hva kommer fra databasen?)

2021-02-10 09:47 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/models/HookData.py
> +    tusd_id: UUID
Så vidt jeg kan se i eksemplene, er ikke tusd_id en uuid, jeg ville nok håndtert denne som en str

2021-02-10 09:47 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_create.py
> +    data_from_db = get_data_from_db(connection, hook_data.ekstern_id, logging)
hook_data.ekstern_id er markert som UUID (men jeg mistenker det faktisk er str, se kommentar på DataFromDatabase objektet). Mens metoden forventer str som input

2021-02-10 09:47 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
> +        'TARGET_OBJECT_NAME': data_from_db.ekstern_id,
Er ikke dette `TARGET_BUCKET_NAME`?

2021-02-10 09:47 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/pre_create.py
> +    data_from_db = get_data_from_db(connection, hook_data.ekstern_id, logger=logging)
Type mismatch, se tidligere kommentarer på samme metode

2021-02-10 13:24 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
> +        'TARGET_OBJECT_NAME': data_from_db.ekstern_id,
Done

2021-02-10 13:51 UTC, elmgren commented on tusd/hooks/implementations/models/HookData.py
> +    tusd_id: UUID
Done

2021-02-10 13:51 UTC, elmgren commented on tusd/hooks/implementations/post_create.py
> +    data_from_db = get_data_from_db(connection, hook_data.ekstern_id, logging)
Done, er en str

2021-02-10 13:59 UTC, elmgren commented on tusd/hooks/implementations/models/DataFromDatabase.py
> +        ekstern_id = metadata.get('ekstern_id')
Returnere en str

2021-02-10 13:59 UTC, elmgren commented on tusd/hooks/implementations/pre_create.py
> +    data_from_db = get_data_from_db(connection, hook_data.ekstern_id, logger=logging)
Done

2021-02-10 14:05 UTC, kriwal-arkivverket approved these changes

2021-02-10 14:05 UTC, merged