MOL-1147 Add `koordinator_navn` to mottak API
arkivverket/mottak pull request #1623
Opened 2022-06-08 11:32 UTC by omBratteng

2022-06-08 14:58 UTC, omBratteng commented on mottak-arkiv-service/app/authentication.py
> +def get_user_from_authz_token(
Splittet litt opp, en egen klasse nå som kan sette auth header dersom python_env er satt til `local`.
Og `Aktor` blir opprettet fra `User`, med litt `Depends` magi

2022-06-09 08:34 UTC, thomjah-computas requested changes

2022-06-09 08:34 UTC, thomjah-computas commented on mottak-arkiv-service/app/authentication.py
>          claims = jwt.decode(
Det virker litt snodig at man gjør `jwt.decode()` både her og i JWTBearer, da især at koden er duplisert. Man kunne ha enkapsulert jwt => claims i JWTBearer kanskje, og Authorization.py kan kalle det for å hente ut claims. Hvis man ønsker at `JWTBearer.__call__` verifiserer token, kan den bare spørre etter claims uten å gjøre noe med dem.
Det blir også litt usymmetrisk at DecodeError skal gi 400 det ene stedet, og 403 det andre, selv om feilen ikke kan dukke opp i det andre tilfellet.

2022-06-09 08:34 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    koordinator_navn: constr(min_length=1)
Vil frontend feile siden koordinat_navn blir påkrevd uten at frontend legger det inn?

2022-06-09 08:34 UTC, thomjah-computas commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    koordinator_navn: str
Overså et issue med database-commit - ny kolonne er satt med nullable=false i DBO, men nullable=true i Alembic-scriptet. Samme med annen kommentar - hvis feltet blir påkrevd, så vil systemet være i en status hvor man ikke kan opprette noe, siden frontend ikke setter inn feltet.

2022-06-09 08:50 UTC, omBratteng commented on mottak-arkiv-service/app/authentication.py
>          claims = jwt.decode(
Prøve å få `JWTBearer` til å returnere dekodet JWT, men da klager python på returner type.
Kan sikkert dra ut en jwt.decode fra `JWTBearer` og la den være mer generisk og drite i å teste dekoding?

2022-06-09 08:52 UTC, omBratteng commented on mottak-arkiv-service/app/auth/http_bearer.py
> +        if get_settings().python_env == "local":
Jo, blir det. Tenkte på det i natt 😅
Så skal endre på det

2022-06-09 08:52 UTC, omBratteng commented on mottak-arkiv-service/app/authentication.py
> +from app.auth.http_bearer import JWTBearer
👍🏻

2022-06-09 08:56 UTC, thomjah-computas commented on mottak-arkiv-service/app/authentication.py
>          claims = jwt.decode(
Man kan ha en `JWTBearer.decode_token(token: str) -> Dict[str, Any]` som `get_user_from_authz_token` bruker for å hente claims, og som også kan brukes til å sjekke at token er valid.

2022-06-09 09:02 UTC, thomjah-computas commented on mottak-arkiv-service/app/auth/http_bearer.py
> +import logging
Skal vi bry oss om at auth-mappen mangler en `__init__.py`?

2022-06-09 09:21 UTC, omBratteng commented on mottak-arkiv-service/app/auth/http_bearer.py
> +import logging
La den til nå

2022-06-10 10:53 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    koordinator_navn: str
Har laget ny migration. At front-end ikke kan skrive, er ikke et problem, så lenge det ikke deployes før MOL-1148 er merget.

2022-06-10 10:55 UTC, thomjah-computas commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    koordinator_navn: str
Er vel hyggelig om dev også er operativt

2022-06-10 11:13 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    koordinator_navn: str
Flytter migration til MOL-1154 som kan tas etter MOL-1148 er merget. Så fikser jeg DBO her, slik at den står som nullable.

2022-06-10 11:43 UTC, thomjah-computas commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    koordinator_navn: str  # MOL-1154 constr(min_length=1)
Så lenge det er `str` og ikke `Optional[str]` vil vel Pydantec klage på at den er påkrevd i HTTP-grensesnittet?

2022-06-10 11:56 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    koordinator_navn: str  # MOL-1154 constr(min_length=1)
Jo, stemmer. Skal fikse

2022-06-10 12:10 UTC, omBratteng commented
Testene feiler pga outage hos PyPi 🙄

2022-06-13 09:01 UTC, thomjah-computas commented
`poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics` gir rundt 10 problemer som ikke er for lang linje pga lang tekst-streng.

2022-06-13 10:51 UTC, thomjah-computas approved these changes

2022-06-13 10:52 UTC, merged