MOL-1206
arkivverket/mottak pull request #1697
Opened 2022-07-11 14:10 UTC by ComputasSnorriEngen

2022-07-11 15:07 UTC, omBratteng requested changes

2022-07-11 15:07 UTC, omBratteng commented on iam-close-dataset/tests/connectors/test_bevaring_client.py
>  ) -> CloseDatasetRequest:
```suggestion
def testobj_payload_with_valid_values(
    session_id: str = "a30c0c60-2aff-42ac-a0a8-b53b667a210c",
    datasett_id: str = "e22d8f48-4264-4972-9c6a-5e0fce8f01a4",
    iam_access_key_id: str = "SOME_RANDOM_ID",
) -> CloseDatasetRequest:
```

2022-08-03 08:12 UTC, thomjah-computas approved these changes

2022-08-03 08:14 UTC, omBratteng requested changes

2022-08-03 08:14 UTC, omBratteng commented on iam-close-dataset/app/main.py
>                  f"IAM_ACCESS_KEY_ID={settings.iam_access_key_id}")
```suggestion
    logger.info(
        "Running iam-close-dataset with the following environment variables: "
        f"BEVARING_ARKIV_SERVICE_BASE_URL={settings.bevaring_arkiv_service_base_url}, "
        f"SESSION_ID={settings.session_id}, "
        f"DATASETT_ID={settings.datasett_id}, "
        f"IAM_ACCESS_KEY_ID={settings.iam_access_key_id}"
    )
```

2022-08-04 07:07 UTC, thomjah-computas submitted a review, later dismissed

2022-08-04 07:27 UTC, omBratteng approved these changes

2022-08-04 07:30 UTC, omBratteng approved these changes

2022-08-04 07:31 UTC, merged