MOL-854
arkivverket/mottak pull request #1717
Opened 2022-07-13 07:49 UTC by ComputasSnorriEngen

2022-07-14 05:15 UTC, omBratteng requested changes

2022-07-14 05:15 UTC, omBratteng commented on mottak-arkiv-service/README.md
> +| UVICORN_SETTINGS__RELOAD     | Enables auto-reload with uvicorn                                    | False                               |
Fikser du den gamle `UVICORN_SETTINGS` til `UVICORN` i stedet, i settings?

2022-07-14 05:16 UTC, omBratteng commented on mottak-arkiv-service/app/main.py
> +    root_path="/api",
Her blir den satt statisk til å være `/api`, vil settings overskrive den?
Samt, har du testet det bak en proxy

2022-07-14 05:36 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/main.py
> +    root_path="/api",
Settings skal ikke overskrive den. 
Jeg har redigert deploymenten med `kubectl` i dev og satt den til å bruke bildet 'MOL-854'. Virker å funke som forventet: https://mottak.plattform.arkivverket.dev/api/docs

2022-07-14 05:39 UTC, omBratteng commented on mottak-arkiv-service/app/main.py
> +    root_path="/api",
Burde det ikke vært mulig å endre på den via settings? Om man vil at den skal være tilgjengelig f.eks under `/potetkanon`

2022-07-14 09:14 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/app/main.py
> +    root_path="/api",
Like gjerne flytte all fastAPI config til settings? `title`, `description`, `version` og `root_path`

2022-07-14 09:51 UTC, omBratteng commented on mottak-arkiv-service/app/main.py
> +    root_path="/api",
Sikkert lurt det ja

2022-07-15 12:35 UTC, omBratteng requested changes

2022-07-15 12:35 UTC, omBratteng commented on mottak-arkiv-service/app/settings.py
> +class FastApiSettings(BaseModel):
```suggestion
class FastAPISettings(BaseModel):
```

2022-07-15 12:35 UTC, omBratteng commented on mottak-arkiv-service/app/settings.py
> +    fastapi: FastApiSettings = FastApiSettings()
```suggestion
    fastapi: FastAPISettings = FastAPISettings()
```

2022-08-03 09:36 UTC, omBratteng approved these changes

2022-08-03 09:37 UTC, merged