MOL-1255 METS-parsing
arkivverket/mottak pull request #1821
Opened 2022-08-25 10:55 UTC by thomjah-computas

2022-08-25 11:47 UTC, ComputasSnorriEngen commented on mottak-arkiv-service/tests/conftest.py
> +#     )
Dette kan kanskje slettes?

2022-08-25 11:56 UTC, thomjah-computas commented on mottak-arkiv-service/tests/conftest.py
> +#     )
Ja, testet vel om fixture var brukt til noe, og så husket man ikke å slette den når man så at ingen brukte den.

2022-08-30 06:28 UTC, omBratteng requested changes
Må fikse konfliktene

2022-08-30 06:41 UTC, omBratteng approved these changes
Ser OK ut, skal teste lokalt før jeg merger

2022-08-30 07:27 UTC, merged