Mol 292
arkivverket/mottak pull request #183
Opened 2021-02-15 13:16 UTC by elmgren

Får ikke container å kjøre lokalt. 
Feilmelding `FATAL Unable to mount file system`

Pusher for å starte process med PR imens jeg ser mer på feilet

2021-02-15 13:36 UTC, kriwal-arkivverket requested changes

2021-02-15 13:36 UTC, kriwal-arkivverket commented on kicker/workflows/submit-archive.yaml
> -          - name: AZURE_STORAGE_KEY
Du kan ikke ta bort denne. Den brukes igjennom Goofy: https://github.com/kahing/goofys/blob/master/README-azure.md

2021-02-15 13:36 UTC, kriwal-arkivverket commented on arkade5/README.md
> +* TARGET_BUCKET_NAME, the bucket/blob where the archive is stored
target_bucket_name er kanskje litt dårlig navn? Høres ut som om at vi skal skrive dit?

2021-02-15 13:36 UTC, kriwal-arkivverket commented on kicker/workflows/submit-archive.yaml
> +          - name: TARGET_BUCKET_NAME
Usikker på om jeg synes env variablen burde hete target_bucket_name her.

2021-02-16 09:44 UTC, elmgren commented on kicker/workflows/submit-archive.yaml
> -          - name: AZURE_STORAGE_KEY
Har lagt til bake den og endret navnet på denne og AZURE_ACCOUNT til å være de anbefalte navnene fra goofys:
AZURE_STORAGE_ACCOUNT og AZURE_STORAGE_KEY

2021-02-16 09:44 UTC, elmgren commented on arkade5/README.md
> +* TARGET_BUCKET_NAME, the bucket/blob where the archive is stored
Endret til ARCHIVE_BUCKET

2021-02-16 09:44 UTC, elmgren commented on kicker/workflows/submit-archive.yaml
> +          - name: TARGET_BUCKET_NAME
Endret til ARCHIVE_BUCKET

2021-02-16 15:57 UTC, kriwal-arkivverket approved these changes

2021-02-16 15:57 UTC, kriwal-arkivverket commented on arkade5/README.md
> +docker run --privileged --env-file=.env <image>`
```suggestion
docker run --privileged --env-file=.env <image>
```

2021-02-16 15:58 UTC, merged