Mol-304
arkivverket/mottak pull request #213
Opened 2021-02-24 13:28 UTC by kriwal-arkivverket

2021-02-24 15:00 UTC, sse-computas approved these changes
Kjenner ikke alle detaljene men ser ut som gode endringer 👍🏻

2021-02-24 21:38 UTC, elmgren requested changes

2021-02-24 21:38 UTC, elmgren commented on arkiv-downloader/arkiv_downloader/main.py
> +    Generates target location and filename `save_path/target_file.extension` if source in an object, otherwise save_path
```suggestion
    Generates target location and filename `save_path/target_file.extension` if source is an object, otherwise save_path
```

2021-02-24 21:38 UTC, elmgren commented on arkiv-downloader/arkiv_downloader/main.py
> +    logger.info(f'Starting transfer of arkivkopi {arkivuttrekk.arkivkopi_id} to {storage_location}')
storage_location vill vise riktig for container men ikke tar fila. 
Men jeg tenker at vi har det vi trenger for å finne enten arkiv eller tar fil med denne informasjonen. 

Hvis du ikke er enig skulle man kunne legge kall til get_target i download(...) isteden for generate_azcopy_command(...)

2021-02-24 21:41 UTC, elmgren commented
Jeg tror at du har feil MOL på denne saken. Skal det ikke vare MOL-325?

2021-02-24 21:53 UTC, omBratteng commented
![image](https://user-images.githubusercontent.com/1681525/109070731-27b16600-76f3-11eb-99be-6150bf945d2d.png)

2021-02-25 06:47 UTC, kriwal-arkivverket commented
> Jeg tror at du har feil MOL på denne saken. Skal det ikke vare [MOL-325](https://arkivverket.atlassian.net/browse/MOL-325)?
🙈

2021-02-25 07:42 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/main.py
> +    logger.info(f'Starting transfer of arkivkopi {arkivuttrekk.arkivkopi_id} to {storage_location}')
Godt poeng, jeg flytter `get_target` til `download`. Blir litt ryddigere kode da synes jeg.

2021-02-25 08:27 UTC, elmgren approved these changes

2021-02-25 08:27 UTC, merged