Mol 326
arkivverket/mottak pull request #216
Opened 2021-02-28 22:19 UTC by elmgren

Gjenstår:
- fikse oppdatering av filnavn i databasen. Oppdatere til f"{arkivuttrekk.obj_id}.tar" der arkivkopi.arkivuttrekk_id == arkivuttrekk.id

2021-03-04 07:08 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/models.py
> +                 blob_info: Optional[dict] = None):
Solved

2021-03-05 11:07 UTC, kriwal-arkivverket requested changes

2021-03-05 11:45 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    target_name = arkivuttrekk.obj_id
Lurer på om vi har litt feil begge to. Bear with me :)

------- INFO-TAINMENT ---------
Ved unpack: (tusd->kicker->unpack)
create_target(TARGET_BUCKET_NAME).   # ekstern_id + ZERO_GENERATION

Ved mottak-arkiv-service:
container_id = ekstern_id + ZERO_GENERATION
target_name: 
      if arkiv:                       <obj_id>/                  
      if overforingspakke:  <obj_id.tar>

Ved arkiv-downloader:
save_path = ARCHIVE_TARGET_LOCATION     # /arkivuttrekk/da-mottak-<env>
if blob_info:  
    return save_path + request.blob_info.target_name
else:
   return save_path 
-----------------------

Jeg tror at vi må endre det slik at:
mottak-arkiv-service:
   target_name = <container_id>/<obj_id>    # og så "/" eller ".tar" ut fra arkiv eller objekt

Da blir on-prem filepath: 
"arkivuttrekk/da-mottak-<env>/<ekstern_id+ZERO_GENERATION>/<arkivuttrekk_obj_id>{"/" | ".tar")

Enig?

2021-03-05 14:10 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +async def request_download(id: int, db: Session = Depends(get_db_session),
`request_download` er allerede definert tidligere, vil ikke dette skape trøbbel?

2021-03-05 15:06 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/models.py
> +    def __init__(self, source_name=None, target_name=None):
Done

2021-03-05 15:09 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/models.py
> +    source_name: Optional[str]
Endret til type set i init metode.
Tenkte at vi kunde sette target_name til å gjelde både for arkiv og for objekter. Etter samtale er vi enige at vi skal sende target_name (og hele blob_info objektet) kun ved objektnedlasting.

2021-03-05 15:37 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/models.py
> +    blob_info: ArkivkopiRequestBlobInfo
Fixet, se kommenter over

2021-03-05 18:51 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +OVERFORINGSPAKKE_CONTAINER = "tusd-storage"
Done

2021-03-05 18:57 UTC, elmgren commented on mottak-arkiv-service/app/connectors/arkiv_downloader/models.py
> +                 arkivkopi_id=None,
Done

2021-03-05 19:09 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    target_name = arkivuttrekk.obj_id
Løsning etter samtale:
On-prem skal lagres slik:
arkiv: `/arkivuttrekk/da-mottak-<env>/ekstern_id+ZERO_GENERATION/`
tarfil: `/arkivuttrekk/da-mottak-<env>/ekstern_id.tar`

Vi fører et samtale om å få fjernet ZERO_GENERATION i denne task med fagsiden.

2021-03-05 19:12 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    source_name = overforingspakke.tusd_objekt_navn
Done

2021-03-05 19:22 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +async def request_download(id: int, db: Session = Depends(get_db_session),
Takk :) 
Har faktisk ikke skapt trøbbel da det er endpunkten som initierer funksjon. Men har enda skiftet navn

2021-03-05 19:30 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/Arkivkopi.py
>      def __init__(self,
Done, lar også id_ vare default da den også blir opprettet i databasen

2021-03-05 21:52 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +async def request_download(id: int, db: Session = Depends(get_db_session),
Fikk opp en flake8 linter error på den linjen

2021-03-07 21:26 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/invitasjon_repository.py
> +    db.query(Invitasjon_DBO).get(id_)
```suggestion
def get_by_id(db: Session, id_: int) -> Invitasjon_DBO:
    return db.query(Invitasjon_DBO).get(id_)
```

Burde ikke denne returnere noe?

2021-03-07 21:38 UTC, omBratteng commented on tusd/hooks/implementations/hooks_utils.py
> +            'i.ekstern_id           AS ekstern_id, '
```suggestion
            'SELECT i.id            AS invitasjon_id, '
            'i.ekstern_id           AS ekstern_id, '
```
Mangler komma, gir denne feilen `LINE 1: SELECT i.id            AS invitasjon_idi.ekstern_id         ...`

2021-03-07 23:12 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +             response_model=Arkivkopi,
Skal den returnere noe mer en ID og status? F.eks forventet lokasjon?

2021-03-08 07:52 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/invitasjon_repository.py
> +    db.query(Invitasjon_DBO).get(id_)
🙈  Jo

2021-03-08 13:48 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    target_name = arkivuttrekk.obj_id
DONE.

Har etter samtale med fagsiden gått for en løsning der vi fjerner ZERO_GENERATION

2021-03-08 13:49 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +             response_model=Arkivkopi,
Done, returnerer nå også target_name

2021-03-09 08:01 UTC, kriwal-arkivverket requested changes

2021-03-09 08:12 UTC, elmgren commented on mottak-arkiv-service/.env.default
> +TUSD_DOWNLOAD_LOCATION_CONTAINER=
Done
Egen PR på den branchen ligger her: https://github.com/arkivverket/mottak-k8s-config/pull/20

2021-03-09 08:42 UTC, kriwal-arkivverket commented on mottak-arkiv-service/.env.default
> +TUSD_DOWNLOAD_LOCATION_CONTAINER=
Da er den merga

2021-03-09 09:31 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    target_name = _get_target_name(invitasjon_id, db, is_object=False)
DONE.
Bruker en domene modell av Invitasjon og henter feltverdier fra den isteden for å gjøre multiple kall til invitasjon repository.

2021-03-09 09:32 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    container_id = tusd_download_location_container
DONE se svar over

2021-03-09 12:13 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    except ArkivkopiOfArchiveRequestFailed as err:
```suggestion
    except (ArkivkopiOfArchiveRequestFailed,SASTokenPreconditionFailed) as err:
```

2021-03-09 12:13 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    except ArkivkopiOfArchiveRequestFailed as err:
```suggestion
    except (ArkivkopiOfArchiveRequestFailed,SASTokenPreconditionFailed) as err:
```

2021-03-09 13:01 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    except ArkivkopiOfArchiveRequestFailed as err:
Done

2021-03-09 13:01 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    except ArkivkopiOfArchiveRequestFailed as err:
Done

2021-03-09 13:58 UTC, omBratteng approved these changes

2021-03-09 14:07 UTC, merged