Mol-363
arkivverket/mottak pull request #242
Opened 2021-03-10 14:34 UTC by kriwal-arkivverket

2021-03-10 15:11 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +"""
Det kan være en ide å skille ut tekstene i egne filer. Da oppdaterer man ikke koden direkte hvis man vil endre på teksten og det vil være mer oversiktlig hvis det kommer inn noe nye utviklere.

2021-03-10 15:25 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +"""
Enig i det. Evt. skrevet det i markdown. Så rendre et til plaintext og HTML

2021-03-10 17:02 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +"""
Har endre slik at det ligger som markdown fil, som bygger til html.
Mangler en god måte å rendre det til plain text

2021-03-11 08:46 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +"""
Jeg krøp til korset og tok i bruk BeautifulSoup for å konvertere html til plain tekst. I plain tekst versjonen så blir det noen ekstra line breaks, men det ble diskutert på stand-up og vurdert som ok.

2021-03-11 08:47 UTC, elmgren requested changes

2021-03-11 08:47 UTC, elmgren commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +        super().__init__(self.__subject,
kan vi legge til argumentnavn her for at det skal bli enklare å lese?

to=to,
sender=f'Mottak ....'

2021-03-11 08:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/connectors/mailgun/models.py
> +        super().__init__(self.__subject,
Har endret litt nå :)

2021-03-11 08:57 UTC, elmgren approved these changes

2021-03-11 09:39 UTC, merged