Mol 328
arkivverket/mottak pull request #246
Opened 2021-03-12 16:26 UTC by elmgren

2021-03-15 09:55 UTC, kriwal-arkivverket requested changes

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/exceptions.py
> +    def __init__(self, arkivuttrekk_obj_id: str, invitasjon_id: int):
Burde ikke arkivuttrekk_obj_id være uuid her?

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/exceptions.py
> +    def __init__(self, arkivuttrekk_obj_id: str, invitasjon_id: int):
Burde ikke arkivuttrekk_obj_id være uuid her?

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id_as_str(arkivuttrekk_id: int, db: Session) -> str:
Hvis `ArkivkopiOfArchiveNotFound` og  `ArkivkopiOfOverforingspakkeNotFound` tar inn uuid, trenger du ikke denne metoden lenger.

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def get_archive_by_invitasjonId_newest(db: Session, invitasjon_id: int) -> Optional[Arkivkopi_DBO]:
Dette blir feil navn for meg. Du henter ikke et arkiv. Du henter arkivkopi for et arkiv.

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def get_overforingspakke_by_invitasjonId_newest(db: Session, invitasjon_id: int) -> Optional[Arkivkopi_DBO]:
Dette blir feil navn for meg. Du henter ikke et arkiv. Du henter arkivkopi for en overføringspakke.

Litt usikker på hva som er beste løsning her, men kanskje bare ha en metode som ser slik ut:
`def get_overforingspakke_by_invitasjonId_newest(db: Session, invitasjon_id: int, is_object: bool) -> Optional[Arkivkopi_DBO]:`?
Også er det opp til metodene i `arkivuttrekk_service` å vite hva det betyr? Eventuelt lage nye navn på de metodene?

Update: Se kommentar i ruteren

2021-03-15 09:55 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +        return await arkivuttrekk_service.get_arkivkopi_status_of_archive(id, db)
Det å hente Arkivkopi status for overføringspakke og arkiv er såpass likt at jeg ville vurdert å bruke samme metoder igjennom arkivuttrekk_service og repository, også sagt at logikken for om det skal være is_object = True eller False burde ligge her i ruteren.

2021-03-15 10:15 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id_as_str(arkivuttrekk_id: int, db: Session) -> str:
Det var mest at jeg uansett trenger en metode for å hente ut objekt_id ettersom jeg her kun har tilgang til arkivuttrekk_id. Da tenkte jeg at jeg kunde passe på å gjøre det om til str her også isteden for å gjøre det i exception. 

Men ser nå at jeg ikke trenger type-cast her da jeg bruke f-string i exception. Endrer det slik at jeg returnere UUID fra denne metoden

2021-03-15 10:18 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id_as_str(arkivuttrekk_id: int, db: Session) -> str:
Jeg synes hele denne metoden er overflødig.

2021-03-15 10:18 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +    def __init__(self, arkivuttrekk_obj_id: str, invitasjon_id: int):
Done

2021-03-15 10:18 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +    def __init__(self, arkivuttrekk_obj_id: str, invitasjon_id: int):
Done

2021-03-15 10:18 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id_as_str(arkivuttrekk_id: int, db: Session) -> str:
Done

2021-03-15 12:06 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +        return await arkivuttrekk_service.get_arkivkopi_status_of_archive(id, db)
Done.
Har endret slik at henting av arkivkopi.status bruker felles funksjoner i arkivuttrekk_service og arkivkopi_repository.
Bruker nå også samme exception ArkivkopiNotFound.

2021-03-15 14:47 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    if not arkivkopi:
Forslag:
```python
if not arkivkopi:        
    arkivuttrekk = arkivuttrekk_repository.get_by_id(db, arkivuttrekk_id)
    raise ArkivkopiNotFound(arkivuttrekk.obj_id, invitasjon.id, is_object)
```

2021-03-15 14:48 UTC, kriwal-arkivverket requested changes

2021-03-15 14:48 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id(arkivuttrekk_id: int, db: Session) -> uuid.UUID:
Kan slettes synes jeg :)

2021-03-15 19:54 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def get_archive_by_invitasjonId_newest(db: Session, invitasjon_id: int) -> Optional[Arkivkopi_DBO]:
Fjernet metoden, bruker nå en generell metode for å returnere arkivkopi

2021-03-15 19:55 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/arkivkopi_repository.py
> +def get_overforingspakke_by_invitasjonId_newest(db: Session, invitasjon_id: int) -> Optional[Arkivkopi_DBO]:
Fjernet metoden og bruker nå en felles metode for å returnere arkivkopi

2021-03-15 19:55 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def _get_obj_id(arkivuttrekk_id: int, db: Session) -> uuid.UUID:
Done

2021-03-15 19:56 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    if not arkivkopi:
Done :)

2021-03-16 07:03 UTC, kriwal-arkivverket approved these changes

2021-03-16 07:03 UTC, merged