Mol 380
arkivverket/mottak pull request #250
Opened 2021-03-15 13:10 UTC by elmgren

Endringer også utført i mottak-k8s-config: add

2021-03-17 16:08 UTC, omBratteng requested changes

2021-03-17 16:08 UTC, omBratteng commented on kicker/workflows/verify-overforingspakke.yaml
> +            dependencies: [ task-checksum ]
```suggestion
          - name: task-checksum-check
            template: checksum-check
          - name: task-avscan
            template: avscan
            dependencies: [ task-checksum-check ]
```

2021-03-18 11:15 UTC, omBratteng requested changes
Oppdatere poetry dependencies?

2021-03-18 11:47 UTC, elmgren commented
Poetry blir oppdatert i MOL-362

2021-03-18 12:39 UTC, omBratteng approved these changes

2021-03-18 12:40 UTC, merged