MOL-366 Implement Azure SDK
arkivverket/mottak pull request #252
Opened 2021-03-15 14:00 UTC by omBratteng

2021-03-17 10:16 UTC, kriwal-arkivverket requested changes

2021-03-17 10:16 UTC, kriwal-arkivverket commented on s3-scan-tar/.env.default
> -AZURE_ACCOUNT=
Du kan ikke ta bort dette enda, først må vi legge til connection string i key vault (med terraform).

2021-03-17 12:22 UTC, omBratteng commented on s3-scan-tar/app/utils.py
> +def sizeof_fmt(size: int) -> str:
Det er oppdatert i d0d985c

2021-03-17 12:26 UTC, omBratteng commented on s3-scan-tar/app/scanner.py
> +            logging.error("clamd reset the connection. Increase max scan size for clamd.")
Er nok rett at det ikke er korrekt feilmelding, er legacy. Og max scan size er satt til 0 i `clamd.conf`, så den er da 4GB, med mindre man går endrer i `clamd.conf`.
Kan splitte den opp i to excepts, en for `ConnectionError` og en for `BufferTooLongError`

2021-03-17 14:13 UTC, omBratteng commented on s3-scan-tar/app/scanner.py
> +            logging.error("clamd reset the connection. Increase max scan size for clamd.")
Splittet i two exceptions i e6c40b9

2021-03-17 14:14 UTC, omBratteng commented on s3-scan-tar/app/utils.py
> +            return "%3.1f %s%s" % (size, unit, "B")
Forbedret lesbarheten i 548bd43

2021-03-17 14:16 UTC, omBratteng commented on s3-scan-tar/app/scanner.py
> +    objectname = os.getenv("TUSD_OBJECT_NAME")
Lagt til en kommentar i b6c2f38

2021-03-18 14:47 UTC, kriwal-arkivverket approved these changes

2021-03-18 14:48 UTC, merged