MOL-379 Update documentation
arkivverket/mottak pull request #253
Opened 2021-03-15 15:10 UTC by sse-computas

Add part on setting up local postgres database in documentation for mottak-arkiv-service

2021-03-15 15:18 UTC, omBratteng approved these changes

2021-03-15 20:16 UTC, elmgren requested changes

2021-03-15 20:16 UTC, elmgren commented on mottak-arkiv-service/README.md
> +      - Run `CREATE DATABASE arkivkopi;` to create the database and `exit` to quit psql
Trur ikke at jeg er enig i at det bør stå arkivkopi som navn her. 
Vi bruker arkivkopi som en tabell i databasen og det kan lede til missforstand om både tabell og databasen heter arkivkopi. 

Forslag. 
- Trenger ikke å gi noen føring for å navngi postgres instansen (default = postgres) eller så kan vi navngi den som "arkivverket"
- Da kan vi bruke navnet "mottak" isteden for "arkivkopi" ved oppkobling til lokal database. 
   -> DBSTRING=postgresql://localhost:5432/mottak

2021-03-16 08:49 UTC, elmgren requested changes

2021-03-16 08:49 UTC, elmgren commented on mottak-arkiv-service/README.md
> +      - Run `CREATE DATABASE mottak;` to create the database and `exit` to quit psql
```suggestion
      - Run `CREATE DATABASE mottak;` to create the database and `exit;` to quit psql
```

2021-03-16 08:51 UTC, elmgren approved these changes

2021-03-16 08:54 UTC, merged