MOL-384 Add support for missing archive type
arkivverket/mottak pull request #259
Opened 2021-03-16 14:56 UTC by sse-computas

Update mottak-arkiv-service with support for missing archive type
Also add endpoint to get all supported archive types

2021-03-22 12:36 UTC, elmgren requested changes

2021-03-22 12:36 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
>          return ArkivuttrekkType.FAGSYSTEM
Updatere metodebeskrivelsen. 

Forslag men gjerne bedre :)
"""
Method that converts a str to a ArkivuttrekkType Enum value or defaults to ArkivuttrekkType.NOT_SELECTED
"""

2021-03-22 12:36 UTC, elmgren commented on mottak-arkiv-service/app/main.py
> +if os.getenv("PYTHON_ENV", None) == "local":
Takk for at du la til dette. Mye enklere nå og snygg løsning

2021-03-22 12:36 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +            summary="Hent ut alle støttede arkivtyper",)
```suggestion
            summary="Hent ut alle støttede arkivtyper")
```

2021-03-22 12:36 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +@router.get("/typer",
Her får jeg PEP 8 warning i min IDE om at det bør vare to rader blanke rader mellom metodene. Får du det og?

Samme etter denne metoden

2021-03-22 12:36 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    return list(ArkivuttrekkType)
Er ikke helt sikker med meg selv her men jeg skriver det opp for diskusjon. 

Even om dette er en enkel retur av en liste så lurer jeg på om den burde gå gjennom service for at beholde et skille mellom router- og servicelayer. Hva tenker du (dere andre)?

2021-03-24 18:05 UTC, sse-computas commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    return list(ArkivuttrekkType)
Er det bedre nå? (Flyttet det ut i service-koden)

2021-03-25 08:02 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    return list(ArkivuttrekkType)
Ja, det ser bra ut synes jeg. 

Bare to små ting, fjern "_" i _get_all_types ettersom metoden ikke er privat lengre og legg til 2 rader avstand

2021-03-25 08:19 UTC, sse-computas commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    return list(ArkivuttrekkType)
Takk, har fikset det nå

2021-03-25 09:20 UTC, elmgren requested changes

2021-03-25 09:20 UTC, elmgren commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +
2 rader

2021-03-25 09:20 UTC, elmgren commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +    arkivuttrekk = metadatafil.as_arkivuttrekk()
her skulle jeg vilje at vi får en ny metode. "metadatafil.as_metadata" og konvertere til metadata istedenfor arkivuttrekk. Dvs. xmlparser returnere Metadata objekt.

2021-03-25 09:20 UTC, elmgren commented on mottak-arkiv-service/app/routers/metadatafil.py
> +        metadatafil = get_parsed_content(id, db)
Kan vi legge logikken her i metoden get_parsed_content()? Slik at get_parsed_content returnere Metadata vi vil ha?

2021-03-25 09:20 UTC, elmgren commented on mottak-arkiv-service/app/routers/services/metadatafil_service.py
> +def get_parsed_content(id_: int, db: Session) -> Metadatafil:
Se tidligere kommentarer om å returnere Metadata her og legge logikken i router her i steden

2021-03-25 09:43 UTC, kriwal-arkivverket requested changes

2021-04-22 12:14 UTC, elmgren requested changes

2021-04-22 12:56 UTC, sse-computas commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +async def router_get_parsed_content():
Done. Hadde helt glemt å endre på metoden jeg kopierte....

2021-04-22 12:57 UTC, sse-computas commented on mottak-arkiv-service/tests/routers/dto/test_Metadata.py
> +    THEN    check that returned DTO object ArkivuttrekkBase is correct
Fixed

2021-04-22 12:57 UTC, sse-computas commented on mottak-arkiv-service/tests/domain/models/test_Metadatafil.py
>  def test_as_arkivuttrekk(testfile_metadatfil):
Fixed

2021-04-22 13:00 UTC, sse-computas commented on mottak-arkiv-service/app/routers/services/metadatafil_service.py
> +# TODO: Find good name for this method
Done. Både navnet og beskrivelsen var oppdatert, hadde bare glemt å fjerne TODO

2021-04-22 13:00 UTC, sse-computas commented on mottak-arkiv-service/app/routers/metadatafil.py
>              status_code=status.HTTP_200_OK,
Done

2021-04-22 13:01 UTC, sse-computas commented on mottak-arkiv-service/app/routers/dto/Metadata.py
> +
Done

2021-04-22 13:01 UTC, sse-computas commented on mottak-arkiv-service/app/domain/xmlparser.py
>      and returns a domain object of type Arkivuttrekk.
Done

2021-04-23 11:20 UTC, sse-computas commented on mottak-arkiv-service/app/domain/xmlparser.py
>      return NOT_PRESENT_RETURN_VALUE
Done

2021-04-23 11:26 UTC, elmgren approved these changes

2021-04-23 11:29 UTC, merged