Mol 362
arkivverket/mottak pull request #268
Opened 2021-03-18 20:43 UTC by elmgren

2021-03-19 09:24 UTC, kriwal-arkivverket requested changes

2021-03-19 09:24 UTC, kriwal-arkivverket commented on kicker/workflows/verify-overforingspakke.yaml
>              value: "Overforingspakke skannet"
Lars og Ane ønsker seg arkiv tittelen i epost subject:
`"Overføringspakke skannet: <arkiv tittel>"

Også er det ø i overføringspakke :) (hvis det ikke knekker noe pga tegnsett)

2021-03-19 09:24 UTC, kriwal-arkivverket commented on kicker/workflows/verify-overforingspakke.yaml
> +                    - arkivuttrekk objekt id: {{workflow.parameters.ARKIVUTTREKK_OBJ_ID}}
Her også ønsker de seg arkivtittel:
```
Gjelder overforingspakke:
    - Tittel: <tittel>
    - arkivuttrekk objekt id: {{workflow.parameters.ARKIVUTTREKK_OBJ_ID}}
    - ...
```

2021-03-19 09:24 UTC, kriwal-arkivverket commented on s3-scan-tar/app/models.py
> +        self.set_status()
Det er ingen grunn til å sette status som variabel er det? Burde ikke det være en metode?

2021-03-19 09:24 UTC, kriwal-arkivverket commented on s3-scan-tar/app/scanner.py
> +def write_result(scan_result: AVScanResult):
Denne burde kanskje hete `write_to_file(scan_result, target)` siden det er det den gjør, også bør den ta inn path.

2021-03-19 09:24 UTC, kriwal-arkivverket commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
Dette burde kanskje være en env variabel? I kicker er vi avhengig av å vite hvor denne filen havner, og nå har vi en "skjult" avhengighet mellom denne strengen og yaml fila i kicker, som leser output her.

Jeg ville antageligvis også brukt `summary` istedenfor message?

2021-03-19 09:24 UTC, kriwal-arkivverket commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
Alternativt kan vi si at alle disse pipeline jobbene produserer en `summary` på `/tmp/summary`, men da må vi dokumentere det godt.

2021-03-19 09:30 UTC, omBratteng commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
👍 for env variabel.
Når man kjører det lokalt, kan man sette den til å outputte det i mappen man jobber i, og ikke i /tmp/ på maskinen

2021-03-22 09:15 UTC, elmgren commented on s3-scan-tar/app/models.py
> +        self.total = clean + virus
Endrer og endrer teksten i generate_message til 

Antall filer kontrollert: 15
- Filer uten virus: 13
- Filer med virus: 1
- Filer ikke kontrollert pga. filstørrelse: 1

2021-03-22 09:56 UTC, elmgren commented on kicker/workflows/verify-overforingspakke.yaml
>              value: "Overforingspakke skannet"
Done

2021-03-22 10:55 UTC, elmgren commented on kicker/workflows/verify-overforingspakke.yaml
> +                    - arkivuttrekk objekt id: {{workflow.parameters.ARKIVUTTREKK_OBJ_ID}}
Done

2021-03-22 10:56 UTC, elmgren commented on s3-scan-tar/app/models.py
> +        self.set_status()
Done

2021-03-22 11:05 UTC, elmgren commented on s3-scan-tar/app/scanner.py
> +def write_result(scan_result: AVScanResult):
Done

2021-03-22 11:23 UTC, elmgren commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
Done

2021-03-22 14:21 UTC, kriwal-arkivverket commented on s3-scan-tar/app/models.py
> +        self.total = clean + virus
Strengt tatt så er vel bare 14 av 15 filer kontrollert?

2021-03-22 14:33 UTC, kriwal-arkivverket commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
Litt usikker på om jeg synes summary er et beskrivende navn på env variabelen, du velger jo å gi den nytt navn med en gang i koden `summary_path = os.getenv('SUMMARY')`. (men ser at kommentaren min over kunne tolkes til at jeg mente det skulle være env variabel navnet)

2021-03-23 09:36 UTC, elmgren commented on s3-scan-tar/app/scanner.py
> +MESSAGE_PATH = '/tmp/message'
Endret til et oppsett som ligner det vi har i checksum der vi sender vi legger melding i /tmp/result

Navn på miljøvariabler endret til OUTPUT_PATH_(RESULT | LOG)

2021-03-23 09:57 UTC, kriwal-arkivverket requested changes

2021-03-23 09:57 UTC, kriwal-arkivverket commented on kicker/workflows/verify-overforingspakke.yaml
> +                Gjelder overforingspakke:
```suggestion
                Gjelder overføringspakke:
```

2021-03-23 09:57 UTC, kriwal-arkivverket commented on s3-scan-tar/app/scanner.py
> +    summary_path = os.getenv('OUTPUT_PATH_RESULT', "/tmp/result")
Kan vi løfte denne opp til de andre os.getenv?

2021-03-23 10:06 UTC, elmgren commented on s3-scan-tar/app/scanner.py
> +    summary_path = os.getenv('OUTPUT_PATH_RESULT', "/tmp/result")
Done

2021-03-23 10:14 UTC, kriwal-arkivverket approved these changes

2021-03-23 10:14 UTC, merged