Mol-82
arkivverket/mottak pull request #31
Opened 2020-09-24 07:50 UTC by kriwal-arkivverket

First version of arkiv-downloader

2020-09-25 10:31 UTC, elmgren requested changes

2020-09-25 10:31 UTC, elmgren commented on arkiv-downloader/arkiv_downloader/main.py
> +    with client.get_receiver() as receiver:
Trengs det noen feilhåndtering eller validering av meldinger i denne metoden?

2020-09-25 10:31 UTC, elmgren commented on arkiv-downloader/arkiv_downloader/models/dto.py
> +            # if the obj is uuid, we simply return the value of uuid
Er dette for å komme unden UUID not serializable in JSON?

2020-09-25 10:31 UTC, elmgren commented on arkiv-downloader/arkiv_downloader/models/dto.py
> +class TransferStatus(Enum):
Foretrekker du int Enum over str?

2020-09-25 10:31 UTC, elmgren commented on arkiv-downloader/tests/test_dto.py
> +    assert status == a.status, 'Status should ne identical'
'Status should be identical'

2020-09-25 10:31 UTC, elmgren commented on arkiv-downloader/tests/test_arkiv_downloader.py
> +    assert TransferStatus.FAILED == response, 'FileNotFoundError should be handled gracefully'
Hvor kastes feilmeldingen fra? Subprocess?

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/README.md
> +Env variables needed:
Nei, den kommer egentlig gjennom service bus, men for å teste, er det mye enklere å ta den inn som env variabel for nå.

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/README.md
> +- Download azcopy and put under [root/arkiv_downloader/azcopy](arkiv_downloader/azcopy)
Det har med hvordan docker imaget, vs lokal struktur leses (hvor scriptet/appen kjøres ifra).
Det stemmer at du skal laste ned binær fila og legge den i `/arkiv_downloader/azcopy/` ja.

Hvis du vil kan jeg prøve å få strukturen helt likt i Dockerfile og lokalt?

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/README.md
> +  "blob_sas_url": "https://<storage_account>.blob.core.windows.net/<container>?<sas_token>"
I main.py står den som det fordi det gjør det enklere for oss å teste. Jeg tenkte å fjerne den når vi får serveren vi skal kjøre på. Men kan godt ta den bort fra main.py hvis du vil, eller legge på en kommentar i koden.

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/__init__.py
> +__version__ = '0.1.0'
Ingen steder. Kom automatisk når jeg opprettet prosjektet. Bare glemte å fjerne fra denne __init__.py fila.

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/main.py
> +    del dotenv
Usikker, det var anbefalt på en stackoverflow post, men vet ikke om det spiller så stor rolle. Den brukes jo ikke mer etterpå. Så den trengs jo ikke mer.

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/main.py
> +logging.getLogger('uamqp').setLevel(logging.WARNING)  # Reducing noise in the logs from overly verbose logger
Dette er Azure service bus pakken som logger veldig mye til info. Så har endre logge nivået for den pakken, slik at det ikke blir så mye støy

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/main.py
> +    with client.get_receiver() as receiver:
Feilhåndteringen ligger i `ArkivuttrekkTransferInfo.from_string(message_str)`, så får vi None object tilbake. Tryner det så hardt at vi ikke kan konvertere meldingen til en string, så er det helt greit at det bobler helt opp og at appen går ned.

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/models/dto.py
> +            # if the obj is uuid, we simply return the value of uuid
Korrekt

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/tests/test_arkiv_downloader.py
> +    assert TransferStatus.FAILED == response, 'FileNotFoundError should be handled gracefully'
Korrekt:
```python
except FileNotFoundError as e:
        logging.error('Could not find azcopy', e)
        return TransferStatus.FAILED
```

2020-09-25 11:59 UTC, kriwal-arkivverket commented on arkiv-downloader/arkiv_downloader/models/dto.py
> +class TransferStatus(Enum):
Hmm, ikke så gjennomtenkt

2020-09-28 11:39 UTC, elmgren commented on arkiv-downloader/README.md
> +- Download azcopy and put under [root/arkiv_downloader/azcopy](arkiv_downloader/azcopy)
Nei, usikker på om jeg skjønte instruksen riktig

2020-09-28 11:44 UTC, elmgren commented on arkiv-downloader/README.md
> +  "blob_sas_url": "https://<storage_account>.blob.core.windows.net/<container>?<sas_token>"
TODO comment ser bra ut her

2020-09-28 11:55 UTC, merged