MOL-438: Update github workflows to commit new files
arkivverket/mottak pull request #318
Opened 2021-04-16 12:06 UTC by sse-computas

Change git-command to also include newly created yaml-files

2021-04-19 07:10 UTC, kriwal-arkivverket requested changes

2021-04-19 07:10 UTC, kriwal-arkivverket commented on .github/workflows/mottak-arkiv-web-workflow.yaml
> +        uses: actions/cache@v2.1.4
Hvorfor ruller du denne tilbake en versjon?

2021-04-19 07:14 UTC, sse-computas commented on .github/workflows/mottak-arkiv-web-workflow.yaml
> +        uses: actions/cache@v2.1.4
Det var ikke meningen. Har sikkert en gammel versjon lokalt

2021-04-19 14:48 UTC, sse-computas commented on .github/workflows/mottak-arkiv-web-workflow.yaml
> +        uses: actions/cache@v2.1.4
Det er fiksa nå

2021-04-20 07:30 UTC, kriwal-arkivverket approved these changes

2021-04-20 07:30 UTC, merged