MOL-428 Fix the pagination in the table
arkivverket/mottak pull request #323
Opened 2021-04-21 12:37 UTC by omBratteng

2021-04-23 10:40 UTC, elmgren requested changes

2021-04-23 10:40 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    """
Mangler description

2021-04-23 10:40 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    class Config:
Kan fjerne `class Config` blocket da klassen ikke brukes i databasen

2021-04-23 10:40 UTC, elmgren commented on mottak-arkiv-web/src/components/arkivuttrekk-table/ArkivuttrekkTable.tsx
> +		// @TODO: Figure out why useRequest causes infinte requests
Er det laget en task på dette?

2021-04-23 10:40 UTC, elmgren commented on mottak-arkiv-web/src/components/arkivuttrekk-table/TableActions.tsx
> +type ButtonClick = MouseEvent<HTMLButtonElement>
Liker at du har laget denne. Mye enklare å penere kode

2021-04-27 08:11 UTC, omBratteng commented on mottak-arkiv-web/src/components/arkivuttrekk-table/ArkivuttrekkTable.tsx
> +		// @TODO: Figure out why useRequest causes infinte requests
Jepp, MOL-410

2021-04-27 10:26 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    class Config:
Fjernet i 19eec78

2021-04-27 10:26 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    """
Lagt til i b9c2358

2021-04-27 12:09 UTC, elmgren approved these changes

2021-04-27 12:09 UTC, merged