Mol 102 v2
arkivverket/mottak pull request #33
Opened 2020-09-24 21:20 UTC by elmgren

Startet om med oppgaven mol-102. 
Lå for mange commits som ikke hadde med task å gjøre så det var enklere å starte på nytt på v2

2020-09-25 11:34 UTC, kriwal-arkivverket requested changes
Jeg synes vi kan committe .env fila som inneholder parametere for lokal db + at jeg savner litt kommentarer i Readme fila :)

2020-09-25 11:34 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/dto/Arkivuttrekk.py
> +class ArkivuttrekkOut(ArkivuttrekkIn):
Tror ikke jeg ville skilt på ArkivuttrekkIn og ArkivuttrekkUt. Det er samme objekter, bare at på den ene så er id, opprettet og endret None, mens på andre skal de ha verdi.

2020-09-28 12:18 UTC, elmgren commented on mottak-arkiv-service/alembic/env.py
> +sys.path.insert(0, os.path.realpath(os.path.join(os.path.dirname(__file__), '..')))
Det er noe krøll med uvicorn og bruk av roots og PYTHONPATH
Jeg får filene å kjøre i IntelliJ, både med pytest og uvicorn. 

Men når jeg kjør fra terminal funker så finner jeg ikke moduler. Denne linjen løste problemet i mol-102 branchen men jeg ser nå at feilet ikke er løst når jeg tester med terminal igjen. 

`uvicorn app/main:app --reload`
funker heller ikke å kjøre fra mappen app
`uvicorn main:app --reload`

2020-09-28 12:24 UTC, elmgren commented on mottak-arkiv-service/app/db/repository.py
> +from app.db.schemas import mottak
Enig. Tidligere hette ArkivuttrekkOut fra app.dto.Arkivuttrekk også Arkivuttrekk så det var for å skille de åt. 
Men har endret det nå :)

2020-09-28 12:44 UTC, elmgren commented on mottak-arkiv-service/app/db/repository.py
> +def get_all_arkivuttrekk(db: Session, skip: int = 0, limit: int = 10) -> List[ArkivuttrekkOut]:
Ja jeg hade missforstått når fastAPI (eller snarere Pydantic) gjør konvertering fra SQLAlchemy til Pydantic. 

Er som du sier at konverteringen skjer mha. response_model i main.py.

2020-09-28 13:47 UTC, elmgren commented on mottak-arkiv-service/app/dto/Arkivuttrekk.py
> +    class Config:
Den gjør en Pydantic modell kompatibel med ORM modeller (SQLAlchemy)

id = data["id"] 
id = data.id

Enlig fastAPI tutorial må denvære med for att man skal kunne konvertere en database modell til en pydantic modell i response_model argumentet (se main.py)

2020-09-28 13:53 UTC, elmgren commented on mottak-arkiv-service/app/dto/Arkivuttrekk.py
> +class ArkivuttrekkOut(ArkivuttrekkIn):
Ja er litt usikker på denne også. Tog det fra "best practice" fra fastAPI. 

Det var egentlig mer relevant i andre branchen der jeg tok inn metadatafilens xml som base64 og hadde et ekstre felt for encoding i "in" versjonen som ikke var med i ut. 

Vi tester uten dette og går tilbake hvis vi merker at vi trenger det senere

2020-09-28 17:58 UTC, elmgren commented on mottak-arkiv-service/app/db/__init__.py
> +def get_session():
Har lagt disse i en egen fil (app.db.database.py)

2020-09-28 18:01 UTC, elmgren commented
Når jeg ser på invitation så kommer det å komme en del andre ting inn i .env filen etterhvert, dvs. ikke kun lokal database. Tenker derfor at jeg ikke committer den.

2020-09-28 19:02 UTC, elmgren commented
Problem med pythonpath. 

Hvis jeg beholder imports med **app**.db så fungerer ikke **uvicorn**. 
`ModuleNotFoundError: No module named 'app'`

Hvis jeg bruker relativ import **.db** fungerer ikke **uvicorn**. 
`ImportError: attempted relative import with no known parent package`

Hvis jeg fjerner app i import av db så funker ikke **pytest**
ModuleNotFoundError: No module named 'db'

2020-09-29 05:29 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/db/repository.py
> +from app.db.schemas import mottak
Nå som du har lagt inn `from .schemas.mottak import *` i `__init__.py` fila.

Kan du importere på denne måte `from app.db import Arkivuttrekk`.
Tenker vi må bestemme oss for en måte å gjøre det på. Enten så importerer vi gjennom `__init__.py` fila, eller så gjør vi det gjennom "full path".

2020-09-29 10:09 UTC, elmgren commented on mottak-arkiv-service/app/db/repository.py
> +from app.db.schemas import mottak
Kjører full path imports

2020-09-29 10:15 UTC, merged