MOL-471
arkivverket/mottak pull request #350
Opened 2021-05-03 09:12 UTC by kriwal-arkivverket

2021-05-03 09:35 UTC, omBratteng commented on s3-unpack/Dockerfile
> +RUN pip install --upgrade pip
Trenger vi å oppgradere pip?

2021-05-03 09:40 UTC, omBratteng commented on s3-unpack/app/s3-unpack.py
> +    """Creates a new bucket on Azure Blob Storage
Er dette en tom funksjon?

2021-05-03 09:42 UTC, omBratteng commented on s3-unpack/app/s3-unpack.py
> +    blob_service_client: BlobServiceClient = BlobServiceClient.from_connection_string(conn_str)
Kunne det vært gjort litt slik som i s3-scan-tar, try...except block for å teste at connection er OK https://github.com/arkivverket/mottak/blob/develop/s3-scan-tar/app/scanner.py#L158-L160

2021-05-03 12:08 UTC, kriwal-arkivverket commented on s3-unpack/Dockerfile
> +RUN pip install --upgrade pip
Usikkert, har sett andre gjøre det. Men finner ikke noe dokumentasjon på hva som er best practice

2021-05-03 12:08 UTC, kriwal-arkivverket commented on s3-unpack/app/s3-unpack.py
> +    """Creates a new bucket on Azure Blob Storage
Hva mener du?

2021-05-03 12:09 UTC, kriwal-arkivverket commented on s3-unpack/app/s3-unpack.py
> +    blob_service_client: BlobServiceClient = BlobServiceClient.from_connection_string(conn_str)
Har refaktorert en del. Dratt metoder som snakker direkte med abs ut i en egen fil.

2021-05-03 12:16 UTC, omBratteng commented on s3-unpack/app/s3-unpack.py
> +    """Creates a new bucket on Azure Blob Storage
Jeg som såg feil i diffen, trudde
```patch
def create_target_bucket(bucket_name: str, blob_service_client: BlobServiceClient) -> +++ContainerClient:
+++    """Creates a new bucket on Azure Blob Storage
```
var hele funksjonen, og rett under var en annen
```patch
---def create_target(container_name):
+++    :param bucket_name: the name of the new bucket
+++    :param blob_service_client: A Blob Service Client with the rights to create a new bucket
+++    :return: a container client of the new bucket
+++    :raises: ResourceExistsError if the bucket already exists
+++    """
```

Det jeg ikke så var `def create_target(container_name):` var i rødt

2021-05-03 12:41 UTC, omBratteng commented on s3-unpack/Dockerfile
> +RUN pip install --upgrade pip
Jeg vet ikke om det er helt nødvendig, kan godt beholde den. Men kunne da slått den inn i samme `RUN` som den under

2021-05-03 12:43 UTC, kriwal-arkivverket commented on s3-unpack/Dockerfile
> +RUN pip install --upgrade pip
Neida, jeg tar den bort jeg. Så legger vi den heller til senere hvis det blir problemer.

2021-05-03 13:01 UTC, omBratteng requested changes

2021-05-03 13:01 UTC, omBratteng commented on s3-unpack/README.md
>  ## Unpack
Når du jobber med s3-unpack, kunne du formatert README filen til å være lik den i `mottak-arkiv-service`?

2021-05-03 13:12 UTC, omBratteng requested changes
Legg inn en `.dockerignore` fil også
```
**/*.egg-info
**/*.egg/
**/*.pyc
**/*.swp
**/__pycache__/
```

2021-05-03 13:36 UTC, omBratteng requested changes

2021-05-03 13:36 UTC, omBratteng commented on s3-unpack/app/s3-unpack.py
> +except:
```suggestion
except ModuleNotFoundError:
```

2021-05-03 13:38 UTC, kriwal-arkivverket commented on s3-unpack/app/s3-unpack.py
> +            logger.info(f'Skipping {file_name} of size {member.size}')
Fikset, pusher snart

2021-05-03 13:39 UTC, kriwal-arkivverket commented on s3-unpack/app/utils.py
> +def get_sha256(handle: Optional[BytesIO]) -> str:
Ikke uten litt stygg unpacking hvor vi kaller denne metoden

2021-05-03 13:42 UTC, kriwal-arkivverket commented on s3-unpack/app/s3-unpack.py
> +except:
Done

2021-05-03 13:49 UTC, omBratteng commented on s3-unpack/Dockerfile
> +ARG PYTHONIMAGE=python:3.9.4-slim
Er litt spent på om Dependabot vil skjønne at dette er versjonen av docker image.
Kunne vi testet med å bruke 3.9.3 i denne PR, og derette sjekke om Dependabot faktisk catcher at det er en nyere versjon?

2021-05-03 14:44 UTC, kriwal-arkivverket commented on s3-unpack/Dockerfile
> +ARG PYTHONIMAGE=python:3.9.4-slim
Har endret til 3.9.3

2021-05-03 14:45 UTC, kriwal-arkivverket commented on s3-unpack/README.md
>  ## Unpack
Done, også lagt til beskrivelse for azurerite, men får det ikke til å kjøre

2021-05-03 14:50 UTC, omBratteng requested changes

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/tests/azurerite/azurerite_upload.py
> +from azure.storage.blob import ContainerClient, BlobServiceClient
```suggestion
from azure.storage.blob import ContainerClient
```

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/tests/azurerite/azurerite_upload.py
> +blob_name = os.getenv("TUSD_OBJECT_NAME", str(uuid.uuid4()))
```suggestion
container_name = os.getenv("SOURCE_BUCKET", "tusd-storage")
blob_name = os.getenv("SOURCE_OBJECT_NAME", str(uuid.uuid4()))
```

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/README.md
> +## Environment variables
```suggestion
## Environment variables

```

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/README.md
> +### Required env variables
```suggestion
### Required env variables

```

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/README.md
> +### Optional env variables
```suggestion
### Optional env variables

```

2021-05-03 14:50 UTC, omBratteng commented on s3-unpack/README.md
> +### Prerequisites
```suggestion
### Prerequisites

```

2021-05-04 13:16 UTC, omBratteng requested changes

2021-05-04 13:16 UTC, omBratteng commented on s3-unpack/app/blob.py
> +DEFAULT_BUFFER_SIZE = 4 * 1024 ** 2
```suggestion
DEFAULT_BUFFER_SIZE = 32 * 1024 ** 2
```
Tenker det er en grei default buffer, 32 MiB burde holde en god del filer inni tarfilen

2021-05-04 13:57 UTC, omBratteng approved these changes

2021-05-04 13:58 UTC, merged