MOL-463
arkivverket/mottak pull request #385
Opened 2021-05-20 11:12 UTC by elmgren

Gjenstår og teste at løpet:
- invitasjon -> tusd -> kicker -> argo_workflow funker som det skal

Har testet at hvert steg funker lokalt. 
Får ikke til å laste opp en invitasjon med archive-uploader i dev miljø pga. feil ved bruk av npm install og yarn install

2021-05-21 06:46 UTC, kriwal-arkivverket requested changes

2021-05-21 06:46 UTC, kriwal-arkivverket commented on kicker/app/container_tags.py
> +#TODO remove this. Environment should only be read in main?
Ja, fjern dette

2021-05-21 06:46 UTC, kriwal-arkivverket commented on kicker/app/domain/kicker_receiver.py
> +    def receive_workflows(self, max_batch_size: int = 1) -> List[ArgoWorkflow]:
Denne burde returnere en liste med KickerRequests

2021-05-21 06:46 UTC, kriwal-arkivverket commented on kicker/app/main.py
> +        workflows = receiver.receive_workflows()
Her burde du få tilbake en liste med kicker requests, også lage en ny linje som ser noe sånt ut
```
requests = receiver.receive_workflows()
workflows = [ArgoWorkflow.from_request(request, container_tags) for request in requests]
```

Årsaken til at jeg tenker det er fornuftig, er fordi nå tryner import statements av `ArgoWorkflow` hvis ikke env variablene som trengs er satt, og det er kanskje litt unødvendig? (det betyr også at ArgoWokflow klassen har en skjult avhengighet til env variabler, og da tenker jeg det er mye ryddigere å samle det på det sted.
![image](https://user-images.githubusercontent.com/69841926/119094191-0077e580-ba11-11eb-9c58-c3341f7e3073.png)

2021-05-21 07:39 UTC, elmgren commented on kicker/app/connectors/argo/argo_client.py
> +    def send_workflow(self, argo_workflow: ArgoWorkflow):
Enig. Done

2021-05-21 07:40 UTC, elmgren commented on kicker/app/connectors/argo/argo_workflow.py
> +from app.container_tags import *
Done

2021-05-21 07:46 UTC, elmgren commented on kicker/app/connectors/argo/argo_workflow.py
> +    elif 'parameters' in manifest['spec']['arguments']:
Enig, done

2021-05-21 07:57 UTC, elmgren commented on kicker/app/domain/kicker_receiver.py
> +    def receive_workflows(self, max_batch_size: int = 1) -> List[ArgoWorkflow]:
Takk, dette blir mye bedre
Done

2021-05-21 08:18 UTC, elmgren commented on kicker/app/main.py
> +        workflows = receiver.receive_workflows()
Done

2021-05-21 10:02 UTC, elmgren commented on kicker/app/container_tags.py
> +#TODO remove this. Environment should only be read in main?
Opprettet ny parameterklasse for container tags
Done

2021-05-26 13:55 UTC, kriwal-arkivverket requested changes

2021-05-26 13:55 UTC, kriwal-arkivverket commented on kicker/app/main.py
>              logger.info(f'Received message on queue {receiver.queue_name}')
Denne loggingen ligger vel ikke på rett sted lenger?

2021-05-27 06:41 UTC, elmgren commented on kicker/app/main.py
>              logger.info(f'Received message on queue {receiver.queue_name}')
Takk. Er nå flyttet til kicker_receiver
Done

2021-05-27 11:23 UTC, kriwal-arkivverket approved these changes

2021-05-27 11:24 UTC, merged