Mol 121
arkivverket/mottak pull request #40
Opened 2020-10-14 13:53 UTC by elmgren

2020-10-15 13:24 UTC, kriwal-arkivverket requested changes

2020-10-15 13:24 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/xmlparser.py
> +def get_tidsspenn(root: ET.Element, ns: dict) -> str:
tidsspenn? er dette et domeneuttrykk? hvis ikke bør vi holde dette som to separate felter, også heller la front-end slå det sammen som visningsting hvis det er ønskelig å se det samlet.

2020-10-15 13:24 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/metadatafil.py
> +    return result
Importer `from fastapi.responses import Response`
Og returner sånn som dette:
`return Response(content=result, media_type="application/xml")`
Så skjønner mottaker at det er xml

2020-10-15 13:24 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/dto/Metadatafil.py
> +    storrelse: str
Storrelse er ikke en str

2020-10-15 13:50 UTC, elmgren commented on mottak-arkiv-service/app/database/mappers/metadatafil.py
> +        opprettet=str(dbo.opprettet),
Har hatt problem med JSONencoding. Skal prøve å få det til med å bruke datetime

2020-10-15 13:51 UTC, elmgren commented on mottak-arkiv-service/app/database/repository.py
> +def arkivuttrekk_get_by_id(db: Session, id: int) -> Arkivuttrekk_DBO:
Ahh, det skal jeg bruke fra nå

2020-10-15 13:59 UTC, elmgren commented on mottak-arkiv-service/app/database/mappers/metadatafil.py
> +def map_dbo2model(dbo: Metadatafil_DBO) -> Metadatafil_domain:
Ja min IntelliJ gjør det, missede å kjøre refactor på denne

2020-10-15 18:52 UTC, elmgren commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +    if not dbo:
I neste PR bruker jeg custom exception her, endre til dette oppsettet uansett?

2020-10-15 18:52 UTC, elmgren commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +def get_content(id: int, db: Session) -> str:
I neste pr er returverdi enten kun str eller raise exception. La den være slik tils dess

2020-10-15 18:53 UTC, elmgren commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +def get_parsed_content(id: int, db: Session) -> ParsedMetadatafil:
Se svar oven, Exception

2020-10-15 18:56 UTC, elmgren commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +        domain_model = map_dbo2model(dbo)
Det ser veldig ryddig ut. Den stjeler jeg :)

2020-10-15 19:10 UTC, elmgren commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +        return map_parsed_domain2dto(domain_parsed)
Fikset

2020-10-15 19:11 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/metadatafil.py
> +class ParsedMetadatafil:
Hehe... Større fiks kommer på dette :)

2020-10-15 19:21 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/metadatafil.py
> +        self.id = id
Fixed

2020-10-15 19:21 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/metadatafil.py
> +                 type=None,
Fixed

2020-10-15 19:22 UTC, elmgren commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +def content_type2metadata_type(content_type: str):
Done

2020-10-15 19:23 UTC, elmgren commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +def get_file_content(file: UploadFile):
Done

2020-10-15 19:25 UTC, elmgren commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +
Høres greit ut. Kjente ikke til det og har savnet det fra Java

2020-10-15 19:27 UTC, elmgren commented on mottak-arkiv-service/app/routers/metadatafil.py
> +             status_code=status.HTTP_200_OK,
Done

2020-10-15 19:29 UTC, elmgren commented on mottak-arkiv-service/tests/conftest.py
> +
Det er navnestandard for pytest. Prøvde annet navn først å det funket ikke.

2020-10-15 19:57 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        altRecordIDs = root.findall('mets:metsHdr/mets:altRecordID', namespaces=ns)
Done

2020-10-15 20:00 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +    altRecordIDs = root.findall('mets:metsHdr/mets:altRecordID', namespaces=ns)
Done

2020-10-15 20:01 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        type = record.get('TYPE')
Endret til type_

2020-10-15 20:03 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +def get_tidsspenn(root: ET.Element, ns: dict) -> str:
arkiv_startdato og arkiv_sluttdato legges til i ArkivuttrekkBase

2020-10-15 20:19 UTC, elmgren commented on mottak-arkiv-service/app/routers/metadatafil.py
> +    return result
Takk

2020-10-15 20:20 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Metadatafil.py
> +    storrelse: str
Blir endret til float i ArkivuttrekkBase

2020-10-16 05:44 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/mappers/metadatafil.py
> +        opprettet=str(dbo.opprettet),
I så fall er det konverteringslogikk som skal ligge i repository laget.
At Json ikke støtte datetime har ikke noe med domenemodellen å gjøre :)

2020-10-16 05:46 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/metadatafil_service.py
> +    if not dbo:
Nei da kan du la det stå :)

2020-10-16 05:48 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        altRecordIDs = root.findall('mets:metsHdr/mets:altRecordID', namespaces=ns)
Ooops, her glemte jeg å krympe R selv 🙈 
Mente egentlig `alt_record_ids` eller `altrecord_ids`

2020-10-16 05:49 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/mappers/metadafil.py
> +
I denne fila synes jeg det var veldig godt med docstrings, men i utgangspunktet trenger vi det ikke på private metoder nei.

2020-10-16 05:50 UTC, kriwal-arkivverket commented on mottak-arkiv-service/tests/conftest.py
> +
Hadde en følelse at det var tilfellet, men håpet i det lengste at det ikke var det :P

2020-10-19 10:20 UTC, elmgren commented on mottak-arkiv-service/app/domain/xmlparser.py
> +        altRecordIDs = root.findall('mets:metsHdr/mets:altRecordID', namespaces=ns)
Ahh...skal fikse

2020-10-22 09:08 UTC, merged