MOL-454: Connect overforingspakke to argo workflow in mottak-arkiv-service
arkivverket/mottak pull request #402
Opened 2021-05-31 08:40 UTC by sse-computas

2021-06-07 20:05 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +@router.get('/{id}/invitasjoner',
Trur jeg ville hatt denne som `/{id}/invitasjon`, selv om man henter ut flere invitasjoner

2021-06-08 06:59 UTC, sse-computas commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +@router.get('/{id}/invitasjoner',
Enig 👍🏻

2021-06-10 10:00 UTC, elmgren requested changes

2021-06-10 10:00 UTC, elmgren commented on mottak-arkiv-service/tests/connectors/argo_workflows/test_models.py
> +def test_overforingspakke_workflow_response_from_string():
`test_workflow_overforingspakke_response_from_string()`

2021-06-11 11:55 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
> +from datetime import datetime
Done

2021-06-11 11:55 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/queues/WorkflowsOverforingspakkeStartedReciver.py
> +from app.connectors.arkiv_downloader.models import ArkivkopiStatusResponse
Done

2021-06-11 11:55 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/queues/WorkflowsOverforingspakkeStartedReciver.py
> +    Class which contains the queue that recieves ArkivkopiStatus from arkiv_downloader
Done

2021-06-11 11:55 UTC, sse-computas commented on mottak-arkiv-service/app/jobs/schedule_status_receiver_job.py
> +    workflow_status_receiver = OverforingspakkeWorkflowReceiver(get_status_con_str())
Done

2021-06-11 11:56 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/queues/WorkflowsOverforingspakkeStartedReciver.py
> +STATUS_RECEIVER_QUEUE_NAME = 'argo-workflow-metadata-receiver'
Done

2021-06-11 13:05 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/queues/WorkflowsOverforingspakkeStartedReciver.py
> +        :return: list with ArkivkopiStatus objects
Done

2021-06-11 13:12 UTC, sse-computas commented on mottak-arkiv-service/app/database/dbo/mottak.py
> +
Also done

2021-06-13 08:05 UTC, elmgren approved these changes

2021-06-13 08:06 UTC, elmgren reviewed
Approved, more changes requested

2021-06-13 08:07 UTC, elmgren requested changes
Approved up to this point, more changes requested

2021-06-13 08:44 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/overforingspakke_repository.py
> +
Done

2021-06-13 08:46 UTC, elmgren commented on mottak-arkiv-service/app/database/repositories/overforingspakke_repository.py
> +def create_workflow(db: Session, workflow: WorkflowOverforingspakkeResponse) -> WorkflowsOverforingspakke_DBO:
1: Done

2021-06-13 08:55 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +def add_overforingspakke_workflow(workflow: WorkflowOverforingspakkeResponse, db: Session) -> Optional[WorkflowsOverforingspakke_DBO]:
1: Done
2: Done
3: Done

2021-06-13 08:56 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +async def get_invitations(arkivuttrekk_id: int, db: Session) -> Optional[List[Invitasjon]]:
1: Done

2: Vi har etter samtal blitt enige i å øke antall repository kall for økt lesbarhet. Ny kode kommer

2021-06-15 11:36 UTC, elmgren commented on mottak-arkiv-service/app/domain/models/Invitasjon.py
>          if isinstance(other, Invitasjon):
Svar: Ja, vi skal ikke jevnføre overforingspakke når vi jevnfør Invitasjon

2021-06-15 11:38 UTC, elmgren commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +
Dette får gå i venteboksen da oppgaven er allerede stor.

2021-06-15 11:39 UTC, elmgren approved these changes

2021-06-15 12:55 UTC, omBratteng requested changes

2021-06-15 12:55 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/WorkflowOverforingspakke.py
> +from datetime import datetime
```suggestion
from datetime import datetime
from uuid import UUID
```

2021-06-15 12:55 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/WorkflowOverforingspakke.py
> +    workflow_uid: str
```suggestion
    workflow_uid: UUID
```

2021-06-15 12:55 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    sas_generator_client: SASGeneratorClient = Depends(get_sas_generator_client)):
I min editor så formateres det som det var før

2021-06-15 12:55 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    Invitasjon_DTO]:
Min editor forslår det slik (PEP8 E125)
```suggestion
async def _attach_overforingspakker_to_invitasjoner(invitasjoner: List[Invitasjon_DBO], db: Session) -> List[
        Invitasjon_DTO]:
```

2021-06-15 18:30 UTC, omBratteng commented on mottak-arkiv-service/alembic/versions/4ce1131b0075_add_table_workflowoverforingspakke.py
> +import sqlalchemy as sa
```suggestion
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
```

2021-06-16 07:49 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    sas_generator_client: SASGeneratorClient = Depends(get_sas_generator_client)):
Jeg får denne måten når jeg bruker min. Får ta en titt på det senere.
Prøver å få det på din måte manuelt

2021-06-16 07:50 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    Invitasjon_DTO]:
Done

2021-06-16 07:50 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    sas_generator_client: SASGeneratorClient = Depends(get_sas_generator_client)):
Trenger ikke bruke tid på dette nå, kan se på det senere når vi diskuterer kode standarder på ett senere tidspunkt.

2021-06-16 07:50 UTC, omBratteng commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    Invitasjon_DTO]:
Trenger ikke bruke tid på dette nå, kan se på det senere når vi diskuterer kode standarder på ett senere tidspunkt.

2021-06-16 08:22 UTC, omBratteng requested changes

2021-06-16 08:22 UTC, omBratteng commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +@router.get('/{id}/workflows',
```suggestion
@router.get('/{overforingspakke_id}/workflows',
```

2021-06-16 08:23 UTC, omBratteng commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +@router.get('/{id}/workflows',
variabelen må matche argumentet i funksjonen, om ikke så må man kalle den slik
`/overforingspakke/{id}/workflows?overforingspakke_id=1`

2021-06-16 08:57 UTC, omBratteng approved these changes

2021-06-16 08:58 UTC, merged