Mol 122
arkivverket/mottak pull request #41
Opened 2020-10-15 10:51 UTC by elmgren

2020-11-02 10:23 UTC, kriwal-arkivverket requested changes

2020-11-02 10:23 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    return arkivuttrekk_create(db, arkivuttrekk)
Litt uheldig at du bytter rekkefølgen her. Blir fort vanskelig å huske når du skal starte med action, og når du skal starte med objekttype.

2020-11-02 14:28 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +class UnvalidContentType(Exception):
O fy fan 🙈

2020-11-02 14:53 UTC, elmgren commented on mottak-arkiv-service/app/exceptions.py
> +class MetadatafilMissingInnhold(Exception):
Fjerner denne

2020-11-02 14:56 UTC, elmgren commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +    except MetadatafilNotFound or MetadatafilMissingInnhold as err:
Nei jeg er litt overrasket over denne også nå. Misstenker at jeg egentlig tenkte ha disse på metadatafil/parsed men for jeg forstår ikke hva jeg har tenkt her.

2020-11-02 15:10 UTC, elmgren commented on mottak-arkiv-service/app/domain/arkivuttrekk_service.py
> +    return arkivuttrekk_create(db, arkivuttrekk)
Tanken er at repository metoder skal begynne med objeket ettersom de ligger i samme fil. 

Denne metoden hette kun create før metoden create_invitation ble lagt til. Endre navn for å ha tydlig skille mellom disse. Men er enig i at det ikke er så tydelig lenger og det blir sikkert ikke enklere fremover.

Kan vi ta en sjapp samtale om denne. Er usikke på om vi bør ha flere repositories klasser eller om vi burde vi opprette egen service for invitasjon?

2020-11-03 10:06 UTC, kriwal-arkivverket approved these changes

2020-11-03 10:06 UTC, merged