Mol-128
arkivverket/mottak pull request #44
Opened 2020-10-21 13:21 UTC by kriwal-arkivverket

2020-10-28 20:44 UTC, elmgren requested changes

2020-10-29 07:28 UTC, kriwal-arkivverket commented on azure-pipelines/k8s/output/dev/av-mottak/templates/tusd-deployment.yaml
> +              value: sandbox7cbdab032f7b4321af274439b1f353a2.mailgun.org
Den er nok mest midlertidig, når vi skal i prod må vi uansett bestille et skikkelig domene fra mailgun. Men helt enig at det mest riktige nok er å ha den i values.

2020-10-29 07:31 UTC, kriwal-arkivverket commented on azure-pipelines/k8s/output/dev/av-mottak/templates/tusd-deployment.yaml
> +# Source: av-mottak/templates/tusd-deployment.yaml
Den blir generert ja, og vet ikke helt hvorfor Service kommer først i den autogenererte. Kanksje det er vanligere å ha den først?

Skal jeg flytte det til samme rekkefølge i templaten?

2020-10-29 07:33 UTC, kriwal-arkivverket commented on azure-pipelines/values/dev/values.yaml
> +TUSD_KICKER_SERVICE_BUS_QUEUE: argo-workflow
Det lurte jeg også på, men disse to brukes både i TUSD og i Kicker. Så derfor jeg følte det ble feil å legge de under en av de.

2020-10-29 07:37 UTC, kriwal-arkivverket commented on azure-pipelines/pipelines/kicker-deploy.yaml
>        resourceGroup: meta # resource group for your ACR
Nei, containerne ligger fortsatt under meta resource groupen

2020-10-29 07:38 UTC, kriwal-arkivverket commented on azure-pipelines/README.md
> +- If you copy paste an existing pipeline, you should only have to change `registry` under `resources.containers` and the `variables`
Helt korrekt 🙈

2020-10-29 07:42 UTC, kriwal-arkivverket commented on azure-pipelines/pipelines/kicker-deploy.yaml
>        - checkout: self
nei, det er faktisk en referanse dette git repoet: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

2020-10-29 07:43 UTC, kriwal-arkivverket commented on azure-pipelines/pipelines/deploy.yaml
> +      git commit -m "Updates ${{ parameters.valuesContainerKey }} ${{ parameters.containerTag }}"
Hvis vi føler oss komfortable med det, jeg tenkte vi kunne følge med litt først, for å se at ting fungerer som vi tror

2020-10-29 08:40 UTC, elmgren commented on azure-pipelines/k8s/output/dev/av-mottak/templates/tusd-deployment.yaml
> +              value: sandbox7cbdab032f7b4321af274439b1f353a2.mailgun.org
Ser at den ligger i values men den brukes ikke her

2020-10-29 08:45 UTC, elmgren commented on azure-pipelines/k8s/output/dev/av-mottak/templates/tusd-deployment.yaml
> +# Source: av-mottak/templates/tusd-deployment.yaml
Gjerne for min del

2020-10-29 09:14 UTC, elmgren approved these changes

2020-10-29 09:14 UTC, merged