Mol-554
arkivverket/mottak pull request #445
Opened 2021-06-15 09:02 UTC by kriwal-arkivverket

2021-06-17 14:16 UTC, elmgren requested changes

2021-06-17 14:16 UTC, elmgren commented on .github/build-workflows.zsh
> +  ["mailer"]="DA_MOTTAK_MAILER_TAG" ["mottak-arkiv-web"]="DA_MOTTAK_ARKIV_WEB_TAG" ["arkade5"]="DA_MOTTAK_ARKADE5_TAG" ["artifact-writer"]="DA_MOTTAK_ARTIFACT_WRITER_TAG")
Mappes det til Values som ikke finnes sen tidligere?
Hvis nei så må vi oppdatere i Mottak-k8s-config

2021-06-17 14:16 UTC, elmgren commented on .github/workflows/artifact-writer-workflow.yaml
> +        if: ${{ 'artifact-writer' == 'storage-sas-generator' }}
Hvorfor 'storage-sas-generator' her? Ser at det er lik for andre også. Er det tenkt at det skal bli en liste med gyldige applikasjoner for integrasjonstester her?

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/README.md
> +Make sure the `OUTPUT_BUCKET` exists.
Skal det vare TARGET_BUCKET her?

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/README.md
> +If no `OUTPUT_FOLDER`: Default is root of bucket.
TARGET_FOLDER?

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/README.md
> +Create `.env` file in [root folder](.) containing env variables, use [`.env.default`](.env.default) as a template.
Mangler .env.default

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/app/main.py
> +def upload_file(file_: str, target_blob_name, target_bucket: str, blob_servie_client: BlobServiceClient):
target_blob_name mangler type

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/app/main.py
> +def append_path_path_sep_if_missing(folder: Optional[str]) -> Optional[str]:
et path for mye i navnet?

2021-06-17 14:16 UTC, elmgren commented on artifact-writer/app/main.py
> +        target_blob_name = strip_artifact_location_from_path(artifacts_location, artifact)
Hva sier du om å refaktorere bort litt av logikken fra main til en egen metode?

Tenker at det kan vare lurt å opprette en "_get_target_blob_name" metod og så får man inn hele if statement etc der.

2021-06-18 08:19 UTC, kriwal-arkivverket commented on artifact-writer/app/main.py
> +        target_blob_name = strip_artifact_location_from_path(artifacts_location, artifact)
God idè, ble mye penere når jeg lagde den metoden

2021-06-18 09:00 UTC, elmgren commented on .github/build-workflows.zsh
> +  ["mailer"]="DA_MOTTAK_MAILER_TAG" ["mottak-arkiv-web"]="DA_MOTTAK_ARKIV_WEB_TAG" ["arkade5"]="DA_MOTTAK_ARKADE5_TAG" ["artifact-writer"]="DA_MOTTAK_ARTIFACT_WRITER_TAG")
Jo det har du helt rett i. Tenkte at vi kun oppdaterte verdier men ser at vi legger til nye også når jeg nå tar en titt i koden :)

2021-06-18 13:10 UTC, omBratteng requested changes
Mindre README endringer, og det skrives *Azurite* og ikke *Azurerite*

2021-06-18 13:10 UTC, omBratteng commented on artifact-writer/README.md
> +
```suggestion

```

2021-06-18 13:10 UTC, omBratteng commented on artifact-writer/README.md
> +Make sure the `TARGET_BUCKET` exists.
```suggestion

Make sure the `TARGET_BUCKET` exists.
```

2021-06-18 13:10 UTC, omBratteng commented on artifact-writer/README.md
> +To start Azurerite:
```suggestion
### Running Azurite

```

2021-06-18 13:10 UTC, omBratteng commented on artifact-writer/README.md
> +Create a target container in Azurerite (you can use [setup.py](tests/integration/setup.py) as
```suggestion
Create a target container in Azurite (you can use [setup.py](tests/integration/setup.py) as
```

2021-06-18 13:10 UTC, omBratteng commented on artifact-writer/README.md
> +Run `artifact-writer`, as docker image:
```suggestion
### Running in a Docker container

```

2021-06-21 10:42 UTC, omBratteng approved these changes
Approved på de endringene jeg forespurte

2021-06-21 12:17 UTC, omBratteng requested changes

2021-06-21 12:17 UTC, omBratteng commented on artifact-writer/app/main.py
> +    blob_client = blob_servie_client.get_blob_client(container=target_bucket, blob=target_blob_name)
```suggestion
def upload_file(file_: str, target_blob_name: str, target_bucket: str, blob_service_client: BlobServiceClient):
    logger.info(f'Uploading {file_} ({os.path.getsize(file_)} B) to {target_bucket} at {target_blob_name}')
    blob_client = blob_service_client.get_blob_client(container=target_bucket, blob=target_blob_name)
```

`blob_servie_client` -> `blob_service_client`

2021-06-21 12:17 UTC, omBratteng commented on artifact-writer/README.md
> +```
```suggestion
```console
```

2021-06-21 13:31 UTC, elmgren approved these changes

2021-06-21 13:35 UTC, omBratteng approved these changes

2021-06-21 13:59 UTC, omBratteng approved these changes

2021-06-21 13:59 UTC, merged