MOL-539
arkivverket/mottak pull request #455
Opened 2021-06-21 12:53 UTC by omBratteng

- Drop legacy tables `tester` and `lokasjon`
- Creates new table `arkivuttrekk_lokasjon`
- Creates new entry into `arkivuttrekk_lokasjon` based on workflow metadata message

2021-06-23 13:28 UTC, elmgren requested changes

2021-06-23 13:28 UTC, elmgren commented on mottak-arkiv-service/app/jobs/services/workflow_overforingspakke_services.py
> +    workflow_overforingspakke = WorkflowOverforingspakke(overforingspakke_id=overforingspakke_id,
legg `if overforingspakke_id:` over her slik at vi ikke oppretter objekter hvis overføringspakke_id mangler. 

Legg logger etter opprettet objekt

2021-06-23 13:28 UTC, elmgren commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
> +        self.target_bucket = target_bucket
Kan vi bruke samme navn i gjennom applikasjonen. Her heter den target_bucket og i resten av applikasjonen container. 

Kan ta det opp i plenum hva vi liker best.

2021-06-23 13:36 UTC, omBratteng commented on mottak-arkiv-service/app/jobs/services/workflow_overforingspakke_services.py
> +    workflow_overforingspakke = WorkflowOverforingspakke(overforingspakke_id=overforingspakke_id,
Fikset i 1d3c759

2021-06-23 13:36 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/arkivuttrekk_lokasjon_repository.py
> +from typing import List
Fikset i 5acdd42

2021-06-23 13:37 UTC, omBratteng commented on mottak-arkiv-service/app/database/dbo/mottak.py
>      testere = relationship('Tester', backref='arkivuttrekk')
Fikset i 958a16d

2021-06-23 13:50 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
> +        self.target_bucket = target_bucket
Enig i at navngivningen bør være konsekvent. Hva navnet bør være er jeg mer usikker på. Det heter vel _container_ på Azure og _bucket_ på AWS/S3/GCP?

2021-06-23 13:52 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/argo_workflow/models.py
> +        self.target_bucket = target_bucket
Har endret det til container i f0c7700

2021-06-23 13:56 UTC, elmgren approved these changes

2021-06-23 13:58 UTC, sse-computas approved these changes

2021-06-24 08:50 UTC, elmgren approved these changes

2021-06-24 08:50 UTC, merged