MOL-515
arkivverket/mottak pull request #465
Opened 2021-06-22 08:18 UTC by kriwal-arkivverket

2021-06-22 20:09 UTC, elmgren requested changes

2021-06-22 20:09 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    workflow_overforingspakke_rows = list(filter(None, workflow_overforingspakke_rows))
Enda sted vi bruker list(filter()) og ikke list comprehension. 
Erstatte med `[workflow_row for workflow_row in workflow_overforingspakke_rows if workflow_row]`?

2021-06-22 20:09 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/registry.py
> +    Writes a new rows to workflow_overforingspakke
```suggestion
    Writes new rows to workflow_overforingspakke.
```

2021-06-23 06:35 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/README.md
> +- `metadata.namespace`: da-mottak-<env>
Fikset

2021-06-23 06:35 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +from uuid import UUID
Done

2021-06-23 06:36 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +INCLUDED_FIELDS = ['items.metadata.name','items.metadata.generateName','items.metadata.uid','items.metadata.spec','items.spec.arguments.parameters','items.status.startedAt']
Done

2021-06-23 06:36 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    Gets all workflow jobs from argo-server with fields as given in INCLUDED_FIELDS
Done

2021-06-23 06:37 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/polulate-workflows-overforingspakke-job.yaml
> +# Source: da-bevaring/templates/discovery-service/discovery-service-oslobyarkiv-cron.yaml
Done

2021-06-23 06:38 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def _build_workflows_overforingspakke_row(workflow_data: dict, db_data: dict):
Antar at du mente `-> Optional[dict]`

Done

2021-06-23 06:40 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    db_data = get_all_overforingspakke_rows(DBSTRING)
God idè, db_data er svært lite beskrivende :)

2021-06-23 06:41 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/registry.py
> +def get_existing_worflow_overforingspakke(dbstring: str, workflow_names: list[str]):
Done

2021-06-23 06:43 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    workflow_overforingspakke_rows = list(filter(None, workflow_overforingspakke_rows))
Har endret til list comprehension slik at koden alltid bruker det

2021-06-23 06:44 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/registry.py
> +    Writes a new rows to workflow_overforingspakke
Fikset

2021-06-23 07:34 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def _build_workflows_overforingspakke_row(workflow_data: dict, db_data: dict):
Ja og så lurte jeg på å endre navnet på db_data. Trenger ikke å være det lange det samme som i run() men et som forteller hva som ligger i.

2021-06-23 07:50 UTC, elmgren requested changes

2021-06-23 07:50 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def run():
Kan vi dele opp run() i tre deler for økt lesbarhet?
```code
def run():
   api_workflow_metadata = _get_workflow_metadata()
   workflow_overforingspakke_rows = _get_workflow_overforingspakke_rows(api_workflow_metadata)
   _write_new_rows_to_db(workflow_overforingspakke_rows)
```

2021-06-23 07:53 UTC, elmgren requested changes

2021-06-23 07:53 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    logger.info(f'Got {len(workflow_metadata)} from argo-server')
legge til "workflows" etter antall i loggen?
-> `Got 77 workflows from argo-server`

2021-06-23 08:27 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def _build_workflows_overforingspakke_row(workflow_data: dict, db_data: dict):
Done

2021-06-23 08:31 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +    logger.info(f'Got {len(workflow_metadata)} from argo-server')
Done

2021-06-23 08:39 UTC, kriwal-arkivverket commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def run():
Delvis done :)

2021-06-23 09:12 UTC, elmgren requested changes

2021-06-23 09:12 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
>      tusd_objekt_navn_to_id_map = _convert_to_tusd_object_name_to_overforingspakke_id_map(overforingspakke_rows)
```suggestion

    tusd_objekt_navn_to_id_map = _convert_to_tusd_object_name_to_overforingspakke_id_map(overforingspakke_rows)
```

2021-06-23 09:12 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
>      only_new_rows = _filter_out_existing_rows(workflow_overforingspakke_rows)
```suggestion

    only_new_rows = _filter_out_existing_rows(workflow_overforingspakke_rows)
```

2021-06-23 13:10 UTC, elmgren commented on scripts/populate-workflows-overforingspakke/app/main.py
> +def _extract_used_data_from_json(data: dict) -> dict[str, str]:
Done

2021-06-23 13:10 UTC, elmgren approved these changes

2021-06-24 06:53 UTC, merged