MOL-572 `r|` tarfile read mode
arkivverket/mottak pull request #475
Opened 2021-06-28 15:06 UTC by omBratteng

2021-06-28 15:30 UTC, kriwal-arkivverket requested changes

2021-06-28 15:30 UTC, kriwal-arkivverket commented on s3-scan-tar/README.md
> +```console
er ikke dette dotenv?

2021-06-28 15:30 UTC, kriwal-arkivverket commented on s3-scan-tar/.env.default
> +TARFILE_READ_MODE=r|
.env.default skal vel ikke ha noe etter `=` ?

2021-06-28 15:30 UTC, kriwal-arkivverket commented on s3-scan-tar/README.md
>  The values given here are examples or hints to proper variables.
`TARFILE_READ_MODE` mangler i lista?

2021-06-28 15:37 UTC, omBratteng commented on s3-scan-tar/.env.default
> +TARFILE_READ_MODE=r|
`.env.default` kan fint ha default verdier, som f.eks `r|`

2021-06-28 15:38 UTC, omBratteng commented on s3-scan-tar/README.md
>  The values given here are examples or hints to proper variables.
Den er nevnt litt lengre ned, og er ikke en påkrevd env variabel, siden den defaulter til `r|` i koden

2021-06-28 15:39 UTC, omBratteng commented on s3-scan-tar/README.md
> +```console
`dotenv` er ikke ett støttet språk i github codeblock

2021-06-29 06:59 UTC, kriwal-arkivverket commented on s3-scan-tar/README.md
> +```console
Men det er støttet av Intellij 😅

2021-06-29 07:00 UTC, kriwal-arkivverket commented on s3-scan-tar/.env.default
> +TARFILE_READ_MODE=r|
joda, men vi har ikke brukt å ha det 😄

2021-06-29 07:31 UTC, omBratteng commented on s3-scan-tar/.env.default
> +TARFILE_READ_MODE=r|
Fjernet default value

2021-06-29 08:08 UTC, merged