MOL-512: Add endpoint to get argo workflow status
arkivverket/mottak pull request #489
Opened 2021-06-30 08:37 UTC by sse-computas

- Endpoint /workflow/{workflow_id}/status
- Enum for all workflow statuses ("Succeeded", "Failed"...)
- Client for connecting to Argo workflows
- 2 new env variables. For local env use: _DA_ARGO_HOST=localhost:2746_ and  _DA_NAMESPACE=da-mottak-dev_

2021-06-30 10:10 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Jeg husker ikke hva denne gjorde, men var det ikke noen plasser som ikke trengte dette? @kriwal-arkivverket @elmgren

2021-06-30 10:24 UTC, omBratteng requested changes

2021-06-30 10:24 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +        return resp.json()
Kjør `self.get` i en try...except slik at man catcher evt. feil, f.eks dersom APIet ikke kan snakke med argo-workflows. 
Se på https://github.com/arkivverket/mottak/blob/develop/mottak-arkiv-service/app/connectors/sas_generator/sas_generator_client.py#L15-L34 som eksempel. Hvis status != 200 så returner feil

2021-06-30 10:24 UTC, omBratteng commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = 'Error'
Lurer litt på om vi skulle kalt denne WorkflowPhase, mtp. det er det Argo kaller det, og er vell samme terminologi i k8s. Da kunne vi også kanskje endret respons til å være `phase` i stedet for `status`

2021-06-30 10:27 UTC, sse-computas commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = 'Error'
Enig i det 👍🏻 Skal oppdatere

2021-06-30 10:32 UTC, sse-computas commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Endepunktet feiler hvis den ikke er med. Tror den må være med siden dette er en egenlaget klasse

2021-06-30 10:41 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Må lese meg litt opp om hva den gjør

2021-07-01 12:15 UTC, sse-computas commented on mottak-arkiv-service/app/domain/models/Workflow.py
> +    ERROR = 'Error'
Oppdatert til å bruke phase

2021-07-01 12:15 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +        return resp.json()
Forbedret feilhåndteringen

2021-07-01 14:20 UTC, omBratteng requested changes

2021-07-01 14:20 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +        return resp.json()
httpx connection blir ikke lukket
```
httpx/_client.py:1914: UserWarning: Unclosed <app.connectors.argo_workflow.argo_workflow_client.ArgoWorkflowClient object at 0x1091441c0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
```
https://www.python-httpx.org/async/#opening-and-closing-clients

Trur det er lettere om du bruker httpx clienten slik som i https://github.com/arkivverket/mottak/blob/develop/mottak-arkiv-service/app/connectors/sas_generator/sas_generator_client.py#L16

2021-07-01 14:54 UTC, elmgren requested changes

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/README.md
>  ARGO_WORKFLOW_METADATA_RECEIVER_CON_STRING="Endpoint=sb://av-mottak-dev-servicebus.servicebus.windows.net/;SharedAccessKeyName=argo-workflow-metadata-receiver;SharedAccessKey=<some_secret_key>
```suggestion
ARGO_WORKFLOW_METADATA_RECEIVER_CON_STRING="Endpoint=sb://av-mottak-dev-servicebus.servicebus.windows.net/;SharedAccessKeyName=argo-workflow-metadata-receiver;SharedAccessKey=<some_secret_key>"
```

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +            logger.error(f"Error while requesting {err.request.url!r}.")
Fjern "!r! i {err.request.url!r}

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/README.md
>  ARGO_WORKFLOW_METADATA_RECEIVER_CON_STRING="Endpoint=sb://av-mottak-dev-servicebus.servicebus.windows.net/;SharedAccessKeyName=argo-workflow-metadata-receiver;SharedAccessKey=<some_secret_key>
Bør også bestemme oss for om vi skal bruke "" rundt verdier her eller ikke. Nå er det blandet

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +        return resp.json()
👍  for httpx clienten

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/app/connectors/connectors_variables.py
> +
husk 2 rader mellom metoder

2021-07-01 14:54 UTC, elmgren commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Kan vi opprette clienten her (i router) og sende opprettet client til service metodene? 

Se på hvordan vi har gjort det i routers.arkivuttrekk for clienter og hvordan vi bruker Depends(get_env_variable).

2021-07-01 14:56 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Når du bruker denne så sier du at DTO og DBO er helt like. 
Så vi var tvungen å fjerne denne når vi endrede Invitasjon DTO slik at den skulle inneholde informasjon om overforingspakke.

2021-07-01 14:57 UTC, omBratteng commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Tenker du på httpx klienten?

2021-07-02 10:49 UTC, elmgren commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Ja

2021-07-02 10:59 UTC, sse-computas commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Hvis jeg fjerner de to linjene, greier den ikke konvertere fra domeneobjektet til DTO automatisk. Det er kanskje andre måter å løse det på?

Feilmeldingen: 
```
pydantic.error_wrappers.ValidationError: 1 validation error for Workflow
response
  value is not a valid dict (type=type_error.dict)
```

2021-07-02 11:14 UTC, omBratteng commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Vi har vell hentet connector klienten og hatt den som Depends, ikke httpx.
https://github.com/arkivverket/mottak/blob/develop/mottak-arkiv-service/app/routers/arkivuttrekk.py#L127

2021-07-02 12:07 UTC, omBratteng commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Tok dette opp under Tech kaffe, vi har misforstått oss begge

2021-07-02 12:52 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +        return resp.json()
Bedre nå?

2021-07-02 12:53 UTC, sse-computas commented on mottak-arkiv-service/app/connectors/argo_workflow/argo_workflow_client.py
> +            logger.error(f"Error while requesting {err.request.url!r}.")
Done

2021-07-02 12:53 UTC, sse-computas commented on mottak-arkiv-service/app/routers/workflow.py
> +    try:
Bedre nå? Gjort det som i request_download_of_overforingspakke() i routers.arkivuttrekk

2021-07-02 13:05 UTC, sse-computas commented on mottak-arkiv-service/README.md
>  ARGO_WORKFLOW_METADATA_RECEIVER_CON_STRING="Endpoint=sb://av-mottak-dev-servicebus.servicebus.windows.net/;SharedAccessKeyName=argo-workflow-metadata-receiver;SharedAccessKey=<some_secret_key>
Endret så alle variablene bruker "" og la den manglene " på slutten

2021-07-02 15:27 UTC, omBratteng approved these changes

2021-07-04 14:07 UTC, elmgren commented on mottak-arkiv-service/app/routers/dto/Workflow.py
> +        orm_mode = True
Fant god forklaring på hva denne faktisk gjør her: https://github.com/tiangolo/fastapi/issues/965

Så det orm_mode = True gjør er at objektet som returneres ikke trenger å være en dict. Du kan anta at objektet som returners har feltene som er satt opp oven. Dvs. du kan bruke `object.id` istedet for `object['id']`

Så her er det jeg som har lagt mer inn i navnet 'orm_mode' enn hva config faktisk gjør.

2021-07-04 14:09 UTC, elmgren approved these changes

2021-07-04 14:15 UTC, merged