MOL-627
arkivverket/mottak pull request #560
Opened 2021-07-22 12:25 UTC by kriwal-arkivverket

2021-07-22 23:11 UTC, omBratteng requested changes
"ferie" 🙃 

`Dockerfile` endringer henter Arkade i eget steg, og kopirer den til siste runtime steg, siden de andre pakkene installert via `apt-get` ikke trengs ved kjøring av Arkade5. Samt generes mappe strukturen som er nødvendig

`entrypoint.sh` reflekterer ny lokasjon for arkade5 `/arkade5`

2021-07-22 23:11 UTC, omBratteng commented on arkiv-producer/README.md
> +```
~~~suggestion
# Arkiv-producer

A small docker container for packing test archives locally. It is loosely built on the concepts described
[here](https://arkivverket.atlassian.net/l/c/HNKRqesj).

## Project prerequisites

- [`docker`](https://www.docker.com/get-started)

## Building docker image

```shell
docker build -t arkiv-producer .
```

## Creating an archive

Before starting, you'll need to generate the [folder structure](#required-folder-structure) where you can add the files that you want to archive.

- Add files to the [`data/input`](./data/input) folder
- [Pack the archive with](#pack-the-archive) the docker image built in the [previous step](#building-docker-image)
  - Alternatively you can use the prebuilt image `arkivverket.azurecr.io/da-mottak/arkiv-producer:<tag>`

### Required folder structure

To run `arkiv-producer`, you'll need this folder structure. The other directories `data/output` and `data/processing` are generated by the Docker image.

```tree
.
└── data
    └── input
```

Which can be created with this command:

```shell
mkdir -p data/input
```

### Pack the archive

Pack the archive with the docker image built in the [previous step](#building-docker-image)

```shell
docker run -v $(pwd)/data:/data arkiv-producer
```

Alternatively use the prebuilt image `arkivverket.azurecr.io/da-mottak/arkiv-producer:<tag>`

```shell
docker run -v $(pwd)/data:/data arkivverket.azurecr.io/da-mottak/arkiv-producer:<tag>
```
~~~

2021-07-23 06:18 UTC, kriwal-arkivverket commented on arkiv-producer/input/.gitignore
> +!.gitignore
Nei, fordi dette er eneste måten å få sjekket inn "tomme" mapper i git

2021-07-23 06:18 UTC, kriwal-arkivverket commented on arkiv-producer/output/.gitignore
> +!.gitignore
Nei, fordi dette er eneste måten å få sjekket inn "tomme" mapper i git

2021-07-23 06:18 UTC, kriwal-arkivverket commented on arkiv-producer/processing/.gitignore
> +!.gitignore
Nei, fordi dette er eneste måten å få sjekket inn "tomme" mapper i git

2021-07-23 06:23 UTC, kriwal-arkivverket commented on arkiv-producer/Dockerfile
> +CMD ["/opt/entrypoint.sh"]
HVorfor bygger du i et annet docker image enn det vi skal kjøre i til slutt?

2021-07-23 08:15 UTC, omBratteng commented on arkiv-producer/Dockerfile
> +CMD ["/opt/entrypoint.sh"]
Microsoft sitt dotnet bilde er basert på debian. Det ser du ved at det står `buster-slim` i image tag. Samt så kjører første steget bare en nedlastning og så unzipping. Men den kan godt bruke samme image i begge stegene.

2021-08-02 12:34 UTC, merged

2021-08-02 13:55 UTC, omBratteng reviewed
👍