MOL-606
arkivverket/mottak pull request #561
Opened 2021-07-22 13:20 UTC by kriwal-arkivverket

2021-07-22 20:59 UTC, omBratteng requested changes
"ferie" 🙃

2021-07-22 20:59 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +
Skulle denne vært under `@router.get("/typer"`, slik at de er "gruppert" under path?

2021-07-22 20:59 UTC, omBratteng commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +
Kanskje https://github.com/arkivverket/mottak/blob/MOL-606/mottak-arkiv-service/app/routers/arkivuttrekk.py#L59-L64 også kunne ha blitt flyttet til å ligge øverst?

2021-07-22 20:59 UTC, omBratteng commented on mottak-arkiv-service/app/database/repositories/arkivuttrekk_repository.py
> +    return original
Jeg syntes det er bedre å kalle den `arkivuttrekk` i stedet for `original`.
```suggestion
    arkivuttrekk: Arkivuttrekk_DBO = db.query(Arkivuttrekk_DBO).get(id_)
    for key, value in updated_fields.items():
        setattr(arkivuttrekk, key, value)
    db.commit()
    return arkivuttrekk
```

2021-07-22 20:59 UTC, omBratteng commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +
Skulle denne ligget under `class Arkivuttrekk(BaseModel):`?
Alfabetisk kommer `ArkivuttrekkUpdate` etter `Arkivuttrekk`

2021-07-23 06:57 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/arkivuttrekk.py
> +
usikker på om jeg skjønner hva du mener, jeg mener dette er en patch på et arkivuttrekk, mao hører den hjemme på `/arkivuttrekk/{id}`.

Ja, kan sikker flytter get arkivuttrekk til toppen, men swagger rydder opp i det for oss uansett :) 
![image](https://user-images.githubusercontent.com/69841926/126747377-bfdd5e0e-ed4e-4355-9111-e8c2d0d5863f.png)

2021-07-23 07:02 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/database/repositories/arkivuttrekk_repository.py
> +    return original
Enig, fiksa det

2021-07-23 07:03 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +
Done, men usikker på om jeg er enig i at alfabetisk er riktig måte å sortere de på 😅

2021-08-02 13:55 UTC, omBratteng approved these changes

2021-08-02 14:00 UTC, merged