MOL-636 `mottak-arkiv-service` integration tests
arkivverket/mottak pull request #622
Opened 2021-08-16 14:56 UTC by omBratteng

2021-08-16 23:09 UTC, omBratteng commented
Ikke merge før resterende workflows ar lagt inn i PR.

2021-08-19 12:40 UTC, sse-computas requested changes
Bra jobba 👍🏻  Flott du fikk ryddet opp i python-workflowene, men jeg har noen innspill på måten det løses på i hver `..../integration/setup.py`

2021-08-19 12:40 UTC, sse-computas commented on artifact-writer/tests/integration/setup.py
> +    return f'DBSTRING=postgresql://postgres:postgres@{response}:5432/postgres\n'
Hvis jeg ikke tar helt feil, bruker vel ikke artifact-writer postgres-databasen?

Se også kommentaren for `mottak-arkiv-service/tests/integration/setup.py`

2021-08-19 12:40 UTC, sse-computas commented on .github/workflows/arkiv-downloader-workflow.yaml
> -            --env AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHB
Bra du fikk rydda opp der 👍🏻

2021-08-19 12:40 UTC, sse-computas commented on mottak-arkiv-service/tests/integration/setup.py
> +    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGM
Disse to metodene kan vel slåes sammen? Da blir det enklere å vedlikeholde de seinere.
Syns også at de lange env-variablene ikke bør være "begravd" i en helpe-metode, men heller i main() eller til toppen av filen så det er lett å eventuelt endre på seinere. 

Mulig du kan gjøre noe sånt:
```
DBSTRING = 'DBSTRING=postgresql://postgres:postgres@<ip-adresse>:5432/postgres\n'
f.write(DBSTRING.replace('<ip-adresse>',10.10.10.10))
```

Dette gjelder de to andre setup.py filene også

2021-08-19 12:40 UTC, sse-computas commented on s3-checksum256/tests/integration/setup.py
> +    return f'DBSTRING=postgresql://postgres:postgres@{response}:5432/postgres\n'
Hvis jeg ikke tar helt feil, bruker vel ikke s3-checksum heller postgres-databasen?

Se også kommentaren på `mottak-arkiv-service/tests/integration/setup.py`

2021-08-19 12:40 UTC, sse-computas commented on storage-sas-generator/tests/integration/setup.py
> +    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGM
Se kommentar på de andre setup-py-filene

2021-08-19 13:38 UTC, omBratteng commented on mottak-arkiv-service/tests/integration/setup.py
> +    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGM
Syns de burde være separat, slik at en kan kopiere en enkelt funksjon, dersom man bare trenger f.eks database env, så slipper man å fjerne azurite konfig.

2021-08-19 13:54 UTC, sse-computas commented on mottak-arkiv-service/tests/integration/setup.py
> +    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGM
Jeg ordla meg dårlig. Jeg mener at du eventuelt skiller ut koden som er felles i en egen metode. Noe sånt:

```
def get_ip(docker_id: str):
    logging.info(f"Fetching IP for azurite container from container {docker_id}")
    response = subprocess.check_output(
        ["/usr/bin/env", "docker", "inspect", "--format",
            "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}", docker_id]
    ).decode("utf-8").strip("\n")
    return response
```


```
def setup_database_env(docker_id: str) -> str:
    reponse = get_ip(docker_id)
    return f'DBSTRING=postgresql://postgres:postgres@{response}:5432/postgres\n'
```


```
def setup_azurite_env(docker_id: str) -> str:
    reponse = get_ip(docker_id)
    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://{response}:10000/devstoreaccount1;\n'

```

2021-08-19 14:05 UTC, sse-computas commented on mottak-arkiv-service/tests/integration/setup.py
> +    return f'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGM
Hvis de kodelinjene flyttes i en egen metode, kommer env-variablene-strengene bedre frem også, så da tenker jeg de bare kan være der de er.

2021-08-23 13:20 UTC, sse-computas approved these changes

2021-08-23 13:20 UTC, merged