MOL-592: Add httpx, tests and improved error handling to mailer
arkivverket/mottak pull request #634
Opened 2021-08-18 13:57 UTC by sse-computas

2021-08-18 14:48 UTC, omBratteng requested changes
`mailer/app/mailgun-status.py` kan fjernes.
Så er det noen commits her fra `mottak-arkiv-service` 🤔

2021-08-18 14:48 UTC, omBratteng commented on mailer/Dockerfile
> +FROM $PYTHONIMAGE
```suggestion
FROM python:3.9.6-slim
```
Ved å bruke $PYTHONIMAGE, klarer ikke Dependabot å sjekke versjon som brukes. Og Dependabot vil oppdatere begge i en eventuell PR

2021-08-18 14:48 UTC, omBratteng commented on mailer/Dockerfile
> +CMD ["python", "-m", "app.mailer"]
```suggestion
COPY app/ app/

CMD ["python", "-m", "app.mailer"]
```

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
> +
~~~suggestion
### Test mailer by sending e-mail to yourself

Create an env-file based on `.env.default`. Set `RECIPIENT` to the e-mail you want to send you, for instance your adresse.

#### Local Python

```console
poetry run app/mailer.py
```

#### Docker

```console
docker build  -t mailer .
docker run --env-file=.env mailer
```

~~~

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
> +```
~~~suggestion
Update packages and install potentially new ones added since

```console
poetry update
```
~~~

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
>   - ATTACHMENTS: <optional path to a list of attached files>
Fjern ` - ` fra disse, og erstatt `:` med `=`

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
>  ```yaml
~~~suggestion
```env
~~~

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
> +### Environment variables
```suggestion
## Environment variables
```

2021-08-18 14:48 UTC, omBratteng commented on mailer/README.md
> +### Error handling
```suggestion
## Error handling
```

2021-08-19 07:31 UTC, closed without merging

2021-08-19 07:31 UTC, sse-computas commented
endret branch