Mol-204
arkivverket/mottak pull request #69
Opened 2020-12-01 10:23 UTC by kriwal-arkivverket

2020-12-01 19:58 UTC, elmgren approved these changes

2020-12-01 19:58 UTC, elmgren commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +if __name__ == '__main__':
Denne likte jeg meget godt. Skal jeg se om jeg kan legge til lignende tester i mottak-arkiv-service og arkiv-downloader?

2020-12-01 19:58 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
> +        'ARCHIEVE_TYPE': dbdata['type'],  # TODO fix this typo in kicker and all dependencies there
Hvorfor tilbake på denne og INVITATION_ID?

2020-12-01 19:58 UTC, elmgren commented on tusd/tests/test_post_finish.py
> +                'ARCHIEVE_TYPE': 'noark5', 'NAME': 'Joe Black', 'EMAIL': 'perbue@arkivverket.no', 'INVITATIONID': 2}
Se spørmål fra post_finish.py

2020-12-01 20:00 UTC, elmgren requested changes

2020-12-01 20:00 UTC, elmgren commented on tusd/tests/test_post_finish.py
>      metadata = invitation_dict
Ignorere denne kommentaren. Er kun lagt til fordi jeg klikket approve å ikke request feedback.

2020-12-02 07:38 UTC, kriwal-arkivverket commented on tusd/hooks/implementations/post_finish.py
> +        'ARCHIEVE_TYPE': dbdata['type'],  # TODO fix this typo in kicker and all dependencies there
Dette er fordi det er avhengigheter mot kicker. Dette er meldingen til kicker, og kicker forventer å få disse nøklene. Det ble alt for mange endringer å endre alle steder i kicker. Så derfor valgte jeg å innføre typoen her igjen

2020-12-02 07:38 UTC, kriwal-arkivverket commented on kicker/tests/kicker-trigger/kicker-trigger.py
> +if __name__ == '__main__':
Ja, det kan du vurdere å gjøre :)

2020-12-02 08:04 UTC, elmgren approved these changes

2020-12-02 08:04 UTC, merged