MOL-647: Add endpoint for arkade5 report
arkivverket/mottak pull request #697
Opened 2021-09-06 12:48 UTC by sse-computas

- Endpoint for download of Arkade5 report in PDF or HTML
- Client for Azure Storage
- Improv error message for storage-sas-generator

2021-09-06 13:17 UTC, omBratteng requested changes

2021-09-06 13:17 UTC, omBratteng commented on mottak-arkiv-service/app/domain/overforingspakke.py
> +    reports = _filter_elements_with_postfix(blobs, "."+file_format)
`suffix` kanskje?
```suggestion
def _filter_elements_with_suffix(input_list, file_format) -> List[str]:
    """
    Receives a list of filenames and a file format
    Returns a list of the files ending with given file format
    """
    return [e for e in input_list if e.endswith(file_format)]


def _select_report(blobs: List[str], file_format: str):
    reports = _filter_elements_with_suffix(blobs, f".{file_format}")
```

2021-09-06 13:17 UTC, omBratteng commented on mottak-arkiv-service/app/routers/services/overforingspakke_service.py
> +    # bucket_name = "simens-arkade5-test-container"
```suggestion
```

2021-09-06 13:17 UTC, omBratteng commented on mottak-arkiv-service/pyproject.toml
> +aiofiles = "^0.7.0"
Hvor brukes `aiofiles`?

2021-09-06 13:27 UTC, omBratteng requested changes

2021-09-06 13:27 UTC, omBratteng commented on mottak-arkiv-service/README.md
> +DATABASE mottak;
```suggestion
CREATE DATABASE mottak;
```
Man er i psql interaktiv terminal, så å ha det på en linje er enklere

2021-09-06 13:44 UTC, sse-computas commented on mottak-arkiv-service/pyproject.toml
> +aiofiles = "^0.7.0"
Ups, den kan fjernes. FastAPI trengte den for å returnere noen filtyper, men jeg fant en bedre måte å løse det på

2021-09-06 13:55 UTC, sse-computas commented on mottak-arkiv-service/app/domain/overforingspakke.py
> +    reports = _filter_elements_with_postfix(blobs, "."+file_format)
Bra forslag, har endret 👍🏻

2021-09-06 13:55 UTC, sse-computas commented on mottak-arkiv-service/app/routers/services/overforingspakke_service.py
> +    # bucket_name = "simens-arkade5-test-container"
Har det fjernet det, takk

2021-09-06 13:56 UTC, sse-computas commented on mottak-arkiv-service/README.md
> +DATABASE mottak;
Slurvefeil, vil også ha det på ei linje

2021-09-06 13:58 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/azure_storage/azure_storage_client.py
> +        self.account_url = f"https://{sas_token.storage_account}.blob.core.windows.net"
Liker ikke helt at det er hard-kodet til å fungere kun med det endepunktet.
Men det er en limit fra storage-sas-generator, man får bare ut sas token, og ikke sas url.
Med denne, kan man ikke teste mot azurite

2021-09-06 14:01 UTC, omBratteng requested changes
Bruke async ABS i `AzureStorageClient`
`azure.storage.blob.aio`

2021-09-06 14:06 UTC, omBratteng requested changes
Tidligere endring re `suffix`

2021-09-06 14:06 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/azure_storage/azure_storage_client.py
> +        return blobs
```suggestion
    async def get_filenames_in_container(self, blob_name_suffix: str = None) -> List[str]:
        """
        Returns filenames for all files in the container matching the given name suffix
        """
        blob_service_client = BlobServiceClient(account_url=self.account_url, credential=self.credential)
        container = blob_service_client.get_container_client(self.container_name)
        blob_list = container.list_blobs(blob_name_suffix)
        blobs = [str(blob.name) for blob in blob_list]
        return blobs
```

2021-09-06 14:16 UTC, omBratteng requested changes

2021-09-06 14:16 UTC, omBratteng commented on mottak-arkiv-service/app/connectors/azure_storage/azure_storage_client.py
> +        return blobs
Tar i bruk async client, og gjenbruker service clienten
```suggestion
import logging
from typing import List

from azure.storage.blob.aio import BlobServiceClient

from app.connectors.sas_generator.models import SASResponse

logger_azure = logging.getLogger("azure.core.pipeline.policies.http_logging_policy")
logger_azure.setLevel(logging.WARNING)

logger = logging.getLogger(__name__)


class AzureStorageClient:
    def __init__(self, sas_token: SASResponse, container_name: str):
        self.account_url = f"https://{sas_token.storage_account}.blob.core.windows.net"
        self.credential = sas_token.sas_token
        self.container_name = container_name

        self.client = BlobServiceClient(account_url=self.account_url, credential=self.credential)
        self.container = self.client.get_container_client(self.container_name)

    async def download_blob(self, blob_name: str) -> bytes:
        """
        Downloads a file/blob from Azure Storage straight to memory
        """
        logger.info(f"Streaming blob {blob_name} from Azure container {self.container_name}")
        stream = await self.container.download_blob()
        return stream.readall()

    async def get_filenames_in_container(self, blob_name_suffix: str = None) -> List[str]:
        """
        Returns filenames for all files in the container matching the given name suffix
        """
        blob_list = self.container.list_blobs(blob_name_suffix)
        blobs = []
        async for blob in blob_list:
            blobs.append(str(blob.name))
        return blobs
```

2021-09-06 14:18 UTC, omBratteng requested changes

2021-09-06 14:18 UTC, omBratteng commented on mottak-arkiv-service/app/routers/overforingspakke.py
> +        headers = {f"Content-Disposition": f"attachment;filename={filename}"}
```suggestion
        headers = {"Content-Disposition": f"attachment;filename={filename}"}
```

2021-09-08 11:09 UTC, sse-computas commented
Fant et par feil!

2021-09-08 11:15 UTC, kriwal-arkivverket commented
Burde vi bruke smart_open til å strømme fila fra abs? :)

2021-09-08 11:18 UTC, sse-computas commented
For å teste endepunktet kan dere legge til følgende rad i databasen:

INSERT INTO arkivuttrekk_lokasjon (overforingspakke_id, bucket, opprettet, endret)
    VALUES (28, 'simens-arkade5-test-container', '2021-02-22 14:43:27.413618+01', '2021-02-22 14:43:27.413618+01');

2021-09-08 11:30 UTC, omBratteng commented
@kriwal-arkivverket trur ikke smart_open trengs her, er en såpass enkel ting vi bruker den til

2021-09-08 11:35 UTC, sse-computas commented
> Burde vi bruke smart_open til å strømme fila fra abs? :)

Tankegangen for å ikke bruke smart_open var at det er et såpass enkelt endepunkt og (forhåpentligvis) kun små PDF/HTML-filer som returneres. Også ville jeg helst unngå å legge til enda en Python-pakke som dependency.

2021-09-08 13:41 UTC, omBratteng approved these changes

2021-09-08 13:42 UTC, merged