MOL-691 `mottak-arkiv-service`
arkivverket/mottak pull request #720
Opened 2021-09-10 11:01 UTC by omBratteng

- MOL-691 Add new column `depotinstitusjon` to `arkivuttrekk` 5c14d84
- MOL-691 Log error if not successful in creating new arkivuttrekk 0100c98
- MOL-691 Add depotinstitusjon to models 9650336
- MOL-691 Fix failing tests b8573e5

2021-09-15 05:57 UTC, kriwal-arkivverket requested changes

2021-09-15 05:57 UTC, kriwal-arkivverket commented on mottak-arkiv-service/alembic/versions/d28b8226e3bb_add_depotinstitusjon_to_arkivuttrekk.py
> +    op.execute("UPDATE arkivuttrekk SET depotinstitusjon='Arkivverket'")
Det er vel et test arkiv som er mottatt som ikke er fra Arkivverket. Så dette blir kanskje litt feil?

2021-09-15 06:00 UTC, omBratteng commented on mottak-arkiv-service/alembic/versions/d28b8226e3bb_add_depotinstitusjon_to_arkivuttrekk.py
> +    op.execute("UPDATE arkivuttrekk SET depotinstitusjon='Arkivverket'")
Jo, blir litt feil. Kunne satt den som en tom streng, for å kunne forfylle nullable=False senere

2021-09-15 11:11 UTC, omBratteng commented on mottak-arkiv-service/alembic/versions/d28b8226e3bb_add_depotinstitusjon_to_arkivuttrekk.py
> +    op.execute("UPDATE arkivuttrekk SET depotinstitusjon='Arkivverket'")
@kriwal-arkivverket kanskje vært bedre å sette den til en tom streng? Så ser man raskt i frontend hvilke som mangler?

2021-09-15 11:21 UTC, kriwal-arkivverket commented on mottak-arkiv-service/alembic/versions/d28b8226e3bb_add_depotinstitusjon_to_arkivuttrekk.py
> +    op.execute("UPDATE arkivuttrekk SET depotinstitusjon='Arkivverket'")
Kan du ikke bare gå en liste fra Henry med obj_id på de arkivuttrekkene som skal ha oslo byarkiv?

2021-09-15 14:09 UTC, omBratteng commented on mottak-arkiv-service/alembic/versions/d28b8226e3bb_add_depotinstitusjon_to_arkivuttrekk.py
> +    op.execute("UPDATE arkivuttrekk SET depotinstitusjon='Arkivverket'")
Vi kan bare la kolonnen være nullable. Trur ikke vi burde legge inn listen med hvilke arkivuttrekk som skal ha oslo byarkiv inn i alembic scriptet mtp. repoet er public

2021-09-17 11:56 UTC, kriwal-arkivverket requested changes

2021-09-17 11:56 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/domain/models/Arkivuttrekk.py
> +    "oslo-byarkiv": "Oslo byarkiv"
+ som diskutert på Huddle på slack

2021-09-17 13:06 UTC, kriwal-arkivverket requested changes

2021-09-17 13:06 UTC, kriwal-arkivverket commented on mottak-arkiv-service/tests/routers/dto/test_Arkivuttrekk.py
> +        depotinstitusjon="Arkivverket",
så matcher det forventet verdi
```suggestion
        depotinstitusjon="arkivverket",
```

2021-09-17 13:06 UTC, kriwal-arkivverket commented on mottak-arkiv-service/tests/routers/dto/test_Arkivuttrekk.py
> +        depotinstitusjon="Arkivverket",
Så matcher det forventet verdi
```suggestion
        depotinstitusjon="arkivverket",
```

2021-09-17 13:06 UTC, kriwal-arkivverket commented on mottak-arkiv-service/app/routers/dto/Arkivuttrekk.py
> +    depotinstitusjon: str
Burde ikke type her være Depotinstitiusjoner? Det er jo enums koden som er forventet verdi.

2021-09-30 09:54 UTC, omBratteng commented
LGTM men skal teste opp mot MOL-653

2021-09-30 10:14 UTC, merged