Mol 211
arkivverket/mottak pull request #76
Opened 2020-12-05 11:58 UTC by elmgren

@kriwal-arkivverket 
Spørsmål om global_state som ligger i main.py

IntelliJ melder fra at vi ikke setter azure_client i GlobalState. Er det meningen å bruke client som vi setter i runtime_config også i denne?

2020-12-07 10:00 UTC, kriwal-arkivverket commented
> @kriwal-arkivverket
> Spørsmål om global_state som ligger i main.py
> 
> IntelliJ melder fra at vi ikke setter azure_client i GlobalState. Er det meningen å bruke client som vi setter i runtime_config også i denne?

Jeg vet ikke helt hva Per har tenkt her, men foreslår at vi flytter azure klienten inn i global state. For hvis vi gjør det, kan vi slette runtime_config (så vidt jeg ser er eneste referanse til den når vi setter klienten, og henter den ut).

2020-12-07 10:12 UTC, kriwal-arkivverket commented on storage-sas-generator/app/main.py
>          permission=ContainerSasPermissions(read=True),
```suggestion
        permission=ContainerSasPermissions(read=True, list=True),
```

2020-12-07 16:33 UTC, elmgren commented
Har prøvt å generer feilet i generate_sas vi snakket om men får ikke startet opp en client hvis account informasjon er feil. 
Tror at denne kan fjernes men lar den ligge og venter på din synspunkt :)

2020-12-08 13:45 UTC, kriwal-arkivverket requested changes

2020-12-08 13:45 UTC, kriwal-arkivverket commented on storage-sas-generator/app/main.py
> +async def register_status(status_code: int, message: str, client: Optional[BlobServiceClient]) -> None:
Either you always include client when you call this method, or you have to set a default value.

2020-12-08 13:45 UTC, kriwal-arkivverket commented on storage-sas-generator/app/main.py
>          await register_status(STATUS_ERROR, exception)
See comment above regarding missing parameter. But either you send None here, or set default value in signature.

2020-12-08 13:59 UTC, elmgren commented on storage-sas-generator/app/main.py
> +async def register_status(status_code: int, message: str, client: Optional[BlobServiceClient]) -> None:
Included client in call.

2020-12-08 13:59 UTC, elmgren commented on storage-sas-generator/app/main.py
>          await register_status(STATUS_ERROR, exception)
Included client in call

2020-12-08 14:34 UTC, merged