MOL-740
arkivverket/mottak pull request #921
Opened 2021-11-10 14:34 UTC by ComputasSnorriEngen

2021-11-10 14:42 UTC, ComputasSnorriEngen commented
Åpen for andre navn enn 'iam-open-dataset', valgte det fordi vi har s3-checksum osv. men syns ikke det gir helt mening å kalle det iam-...

2021-11-10 14:44 UTC, ComputasSnorriEngen commented
Samme gjelder pakkestrukturen. Lagde den som føltes naturlig, er noen uenige så endrer jeg.

2021-11-10 15:06 UTC, omBratteng requested changes
Kjapp gjennomgang uten å teste kode. Mangler også en README fil

2021-11-11 06:57 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +        logger.info(f"Access keys: {access_keys} received.")
Hehe. Den diskusjonen har jeg jevnlig med meg selv. 
Korrekt skrivemåte er å alltid avslutte en setning med punktum. Hvis en logg linje har 2 setninger i seg så skilles de med et punktum og derfor burde også neste setning avsluttes med punktum. 

Men for meg er det ett fett. Lik denne kommentaren og du vil aldri se et punktum på slutten av en logglinje fra meg ;) Til min søsters (som er norsklærer) store forargelse.

2021-11-11 06:59 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/services/bevaring_service.py
> +    )
Kan man gjøre det som et argument? altså:
`def _payload(settings = Settings())`?

2021-11-11 07:00 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/web/bevaring_client.py
> +        self.url = f"{bevaring_arkiv_service_host}"
Kan ikke forsvare denne

2021-11-11 07:26 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/utils.py
> +        logger.critical("Missing environment variable [BEVARING_ARKIV_SERVICE_HOST]")
Det har du rett i. Pydantic vil melde om at variabelen er påkrevd, men ikke satt.

2021-11-11 07:37 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/utils.py
> +        exit(ENVERROR)
Done

2021-11-11 07:38 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/utils.py
> +        logger.critical("Missing environment variable [BEVARING_ARKIV_SERVICE_HOST]")
Done

2021-11-11 07:38 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +logger = logging.getLogger(__name__)
Done

2021-11-11 07:38 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +        logger.info(f"Access keys: {access_keys} received.")
Done

2021-11-11 07:38 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/web/bevaring_client.py
> +        self.url = f"{bevaring_arkiv_service_host}"
Done

2021-11-11 07:39 UTC, ComputasSnorriEngen commented on iam-open-dataset/pyproject.toml
> +gunicorn = {version = "^20.1.0", optional = true}
Done

2021-11-11 07:39 UTC, ComputasSnorriEngen commented on iam-open-dataset/pyproject.toml
> +gunicorn = ["gunicorn"]
Done

2021-11-11 07:39 UTC, ComputasSnorriEngen commented on iam-open-dataset/pyproject.toml
> +psycopg2-binary = "^2.9.1"
Done

2021-11-11 07:39 UTC, ComputasSnorriEngen commented on iam-open-dataset/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends python3 git
Done

2021-11-11 07:51 UTC, omBratteng commented on iam-open-dataset/app/services/bevaring_service.py
> +    )
Ja, det kan man kanskje? Prøv å se

2021-11-11 07:57 UTC, omBratteng requested changes

2021-11-11 07:57 UTC, omBratteng commented on iam-open-dataset/pyproject.toml
> +python = "^3.9"
```suggestion
python = "^3.8"
```

2021-11-11 08:06 UTC, omBratteng commented on iam-open-dataset/app/helpers/utils.py
> +        logger.critical("Missing environment variable [BEVARING_ARKIV_SERVICE_HOST]")
Prøv å legg inn en validator i Settings. Enten på alle fields, eller på spesifikke
https://pydantic-docs.helpmanual.io/usage/validators/

2021-11-11 08:11 UTC, ComputasSnorriEngen commented on iam-open-dataset/pyproject.toml
> +python = "^3.9"
Done

2021-11-11 10:55 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/services/bevaring_service.py
> +    )
Gikk for ditt forslag. Ingen grunn til at andre skal kunne sette den.

2021-11-11 10:55 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/services/bevaring_service.py
> +    )
Done

2021-11-11 10:56 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/utils.py
> +        logger.critical("Missing environment variable [BEVARING_ARKIV_SERVICE_HOST]")
Done

2021-11-11 11:00 UTC, omBratteng requested changes

2021-11-11 11:00 UTC, omBratteng commented on iam-open-dataset/app/helpers/settings.py
> +            raise ValueError("Environment variable cant be empty")
```suggestion
            raise ValueError("Environment variable can not be empty")
```

2021-11-11 11:19 UTC, omBratteng requested changes

2021-11-11 11:19 UTC, omBratteng commented on iam-open-dataset/app/web/bevaring_client.py
> +from httpx import RequestError, HTTPStatusError
Her importerer du httpx og så errors fra httpx. Pick one.

2021-11-11 11:20 UTC, omBratteng commented on iam-open-dataset/app/main.py
> +        logger.info(f"Access keys: {access_keys} received")
Inneholder `access_keys`  noen secrets som ikke burde logges?

2021-11-11 11:28 UTC, omBratteng requested changes

2021-11-11 11:28 UTC, omBratteng commented on iam-open-dataset/app/helpers/utils.py
> +    return host_name
Med den siste endringen i Settings, så er kanskje ikke denne sjekken nødvendig?

2021-11-11 11:28 UTC, omBratteng commented on iam-open-dataset/app/helpers/return_codes.py
> +#!/usr/bin/env python3
Har du tenkte å kjøre denne? :smile:

2021-11-11 11:28 UTC, omBratteng commented on iam-open-dataset/README.md
> +Dokumenterer når den er klar.
~~~suggestion
# iam-open-dataset

`iam-open-dataset` is meant to be triggered by the Argo Workflow `submit-to-preservation`.
This container performs an HTTP POST-request to [`bevaring-arkiv-service`](https://github.com/arkivverket/bevaring/tree/develop/bevaring-arkiv-service) and get access keys to cloudian in return which it writes to `/tmp/access-keys`.

## Project prerequisites

- [`python >= 3.8`](https://www.python.org/downloads/)
- [`poetry`](https://python-poetry.org/docs/)

## Environment variables

The variables will be set by Argo

### Required variables

```dotenv
BEVARING_ARKIV_SERVICE_HOST
DEPOT_INSTUTISJON
AVGIVER
ARKIVSKAPER_ORGANISASJON
ARKIVEIER_ORGANISASJON
TITTEL
START_DATO
SLUTT_DATO
AVTALENUMMER
OUTPUT_PATH=/tmp/access-keys
```

## Running locally

### Prerequisites

Create `.env` file in [root folder](.) containing env variables, use [`.env.default`](.env.default) as a template.

### Running in docker

TODO: Jeg jobber med en docker-compose fil som skal spinne opp alle avhengigheter og gjøre det mulig å teste 100% lokalt.
Dokumenterer når den er klar.

~~~

2021-11-11 12:02 UTC, elmgren requested changes

2021-11-11 12:02 UTC, elmgren commented on iam-open-dataset/app/main.py
> +        logger.info(f"Access keys: {access_keys} received")
Er det alltid ok å skrive ut secret_access_key i loggen?

2021-11-11 12:04 UTC, omBratteng commented on iam-open-dataset/app/helpers/settings.py
> +    def not_empty(cls, v):
Kopiert mer eller mindre fra Pydantic sin dokumentasjon. Men kanskje endre den til `value` for å gi mer eksplisitt navn

2021-11-11 12:07 UTC, omBratteng commented on iam-open-dataset/README.md
> +Dokumenterer når den er klar.
I tillegg til endringen ovenfor, legg inn eksempel på hva som kommer i output filen. Husk å scrub sensitiv informasjon som navn og secrets

2021-11-11 12:25 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/settings.py
> +    def not_empty(cls, v):
Gikk først for value, men fikk en error jeg trodde kunne være relatert :
`values: a dict containing the name-to-value mapping of any previously-validated fields`
Valgte derfor v for å unngå forvirring, men jeg er helt enig i at v er lite beskrivende. Kan godt gå for `value` her.

2021-11-11 12:42 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/return_codes.py
> +#!/usr/bin/env python3
Så på hvordan det var gjort i tusd, stusset på det selv. Burde sett nærmere på det.
https://github.com/arkivverket/mottak/blob/develop/tusd/hooks/implementations/return_codes.py

2021-11-11 12:44 UTC, omBratteng commented on iam-open-dataset/app/helpers/return_codes.py
> +#!/usr/bin/env python3
\*kremt\* git blame \*kremt\*
![image](https://user-images.githubusercontent.com/1681525/141300202-abb911c1-95fb-42d8-9ee6-fd33220633cb.png)

2021-11-11 12:47 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/domain/models.py
> +    iam_access_key_id: str
Hm. Nå roter jeg litt her. Det er jo bevaring-arkiv-service som lager datasett_id, ikke mottak-arkiv-service som det først var snakk om. Så ja, den må være med, men depot_instutisjon skal jo være med i requesten til bevaring-arkiv-service så den er tjenesten nødt til å kjenne før responsen kommer tilbake.

2021-11-11 12:49 UTC, omBratteng commented on iam-open-dataset/app/helpers/return_codes.py
> +#!/usr/bin/env python3
Og akkurat det med exit codes er vell noe Per startet med, og vi har bare fortsatt med det. Men det er ganske fint da, bare sjekk exit kode opp mot den filen, så finner man raskt ut av det. Er vell derfor man kan ha flere exit codes :smile:

2021-11-11 12:50 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +def _write_to_file(access_keys: dict, target_path: str):
Ikke helt enig i at den hører hjemme i domain. 
Den kunne kanskje bli lagt i utils. La den i main siden den klassen uansett er så tynn.
Tanker?

2021-11-11 13:12 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/utils.py
> +    return host_name
Korrekt

2021-11-11 13:14 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/return_codes.py
> +#!/usr/bin/env python3
Nå som `get_api_baseurl()` i `utils.py` ikke lenger brukes er heller ikke denne filen nødvendig. Sletter den.

2021-11-11 13:17 UTC, elmgren commented on iam-open-dataset/app/domain/models.py
> +    iam_access_key_id: str
Sant, depot_institusjon kan vi droppe

2021-11-11 13:21 UTC, elmgren commented on iam-open-dataset/app/main.py
> +def _write_to_file(access_keys: dict, target_path: str):
Jeg er ikke så glad i logikk / metoder i main. Usikker på hvor jeg synes denne hører hjemme. Muligens en egen fil i helpers kan funke bedre.

2021-11-11 13:32 UTC, omBratteng commented on iam-open-dataset/app/main.py
> +def _write_to_file(access_keys: dict, target_path: str):
`not_main.py`? :joy:

2021-11-11 13:50 UTC, omBratteng requested changes

2021-11-11 13:50 UTC, omBratteng commented on iam-open-dataset/README.md
> +This container performs an HTTP POST-request to [`bevaring-arkiv-service`](https://github.com/arkivverket/bevaring/tree/develop/bevaring-arkiv-service) and get access keys to cloudian in return which
```suggestion
This container performs an HTTP POST-request to [`bevaring-arkiv-service`](https://github.com/arkivverket/bevaring/tree/develop/bevaring-arkiv-service) and get access keys to cloudian in return which it writes to `/tmp/access-keys`.
```

2021-11-11 14:30 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/domain/models.py
> +    iam_access_key_id: str
Done

2021-11-11 14:31 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/settings.py
> +    def not_empty(cls, v):
done

2021-11-11 14:31 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +def _write_to_file(access_keys: dict, target_path: str):
Done

2021-11-11 14:31 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +        logger.info(f"Access keys: {access_keys} received")
Done

2021-11-12 08:41 UTC, omBratteng requested changes
Kan du legge inn eksempel på output til `/tmp/output` i README filen? Husk å fjerne sensitiv informasjon.

2021-11-12 08:44 UTC, ComputasSnorriEngen commented on iam-open-dataset/README.md
> +
Ligger her? @omBratteng

2021-11-12 08:51 UTC, omBratteng requested changes

2021-11-12 08:51 UTC, omBratteng commented on iam-open-dataset/README.md
> +## Running locally
```suggestion
## Running locally
```

2021-11-12 08:51 UTC, omBratteng commented on iam-open-dataset/README.md
> +Dokumenterer når den er klar.
~~~suggestion
Dokumenterer når den er klar.

## Output

Example output to the `/tmp/output` file

```json
{'iam_access_key_id': '< SOME ID >', 'iam_secret_access_key': '< SOME SECRET >', 'datasett_id': '<SOME_UUID>'}
```
~~~

2021-11-12 09:27 UTC, omBratteng approved these changes

2021-11-12 09:42 UTC, omBratteng commented on iam-open-dataset/app/main.py
> +    logger.info("Running iam-open-dataset")
Kunne vi ha logget litt mer her? Litt info om hva som kjøres og hvilke variabler. Vil gjøre det enklere å se i loggen hvordan den har kjørt.
Så f.eks logge litt av det som er satt som env variabler

2021-11-12 11:27 UTC, elmgren approved these changes

2021-11-12 11:36 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +    logger.info("Running iam-open-dataset")
Hva om jeg logger `bevaring_arkiv_service_host` og `output_path` i `main.py` og så logger resten av envs (CreateDatasetRequest) som json når `_payload()` i bevaring_service.py kalles.

2021-11-12 11:38 UTC, omBratteng commented on iam-open-dataset/app/main.py
> +    logger.info("Running iam-open-dataset")
Høres greit ut

2021-11-12 11:48 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +    logger.info("Running iam-open-dataset")
Done

2021-11-12 11:49 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/main.py
> +    logger.info("Running iam-open-dataset")
Logget nå bare hvilke envs som iam-open-dataset kjører med. hva den gjør logges når den gjør det.

2021-11-12 12:02 UTC, omBratteng approved these changes

2021-11-12 12:02 UTC, merged