MOL 778
arkivverket/mottak pull request #960
Opened 2021-11-22 07:48 UTC by ComputasSnorriEngen

Tjeneste for å lukke et åpnet datasett. Tjenesten er ment å bli trigget av Argo

2021-11-22 08:18 UTC, omBratteng submitted a review, later dismissed

2021-11-22 08:18 UTC, omBratteng commented on iam-close-dataset/app/helpers/filewriter.py
> +def write_to_file(close_dataset_response: dict, target_path: str):
```suggestion
def write_to_file(close_dataset_response: dict, target_path: str) -> None:
```

2021-11-22 14:27 UTC, thomjah-computas commented on iam-close-dataset/app/main.py
> +                f"IAM_SECRET_ACCESS_KEY={settings.iam_secret_access_key}")
Du har ikke lyst til å logge SECRET. Man kan alltids logge hvor lang den er for å vise at man har tatt imot en faktisk verdi (ikke tom)

2021-11-22 14:27 UTC, thomjah-computas commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_secret_access_key=settings.iam_secret_access_key
Man sender ikke inn iam_secret_access_key til /close-endpunktet til bevaring-arkiv-service, kun datasett_id og iam_access_key_id.

2021-11-22 14:27 UTC, thomjah-computas commented on iam-close-dataset/app/services/bevaring_service.py
> +def close_dataset(client) -> None:
Parameter bør kanskje være typet?

2021-11-22 14:27 UTC, thomjah-computas commented on iam-close-dataset/app/web/bevaring_client.py
> +        self.url = bevaring_arkiv_service_host
Er base_url et mer passende navn, siden det er bare protokoll, host og port?

2021-11-22 14:27 UTC, thomjah-computas commented on iam-close-dataset/tests/web/test_bevaring_client.py
> +dotenv_path = get_project_root() / ".env.test"
Er dette nødvendig når det ikke finnes en .env.test-fil?

2021-11-22 14:29 UTC, omBratteng commented on iam-close-dataset/app/main.py
> +                f"IAM_SECRET_ACCESS_KEY={settings.iam_secret_access_key}")
Dersom type i settings er satt til `SecretStr`, så vil det bare logges `****` eller noe slikt, og ikke faktisk secret

2021-11-23 06:35 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/main.py
> +                f"IAM_SECRET_ACCESS_KEY={settings.iam_secret_access_key}")
Riktig som OM sier. iam_secret_access_key logges som `IAM_SECRET_ACCESS_KEY=********`. Når det er sagt så trengs ikke `iam_secret_access_key` for å lukke datasette. Skal fjerne den.

2021-11-23 07:12 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_secret_access_key=settings.iam_secret_access_key
Korrekt. fikser

2021-11-23 07:13 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +def close_dataset(client) -> None:
Jepp. Den henger igjen fra jeg hadde en (unødvendig) test på bevaring-service. Da brukte jeg mock client så den kunne ikke være typet. Den testen er fjernet, jeg fikser.

2021-11-23 07:18 UTC, ComputasSnorriEngen commented on iam-close-dataset/tests/web/test_bevaring_client.py
> +dotenv_path = get_project_root() / ".env.test"
nice catch. Det finnes en .env.test-fil, men kun på min maskin :P Jeg legger den til.

2021-11-23 07:20 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/helpers/filewriter.py
> +def write_to_file(close_dataset_response: dict, target_path: str):
Jeg er ganske sikker på at denne tjenesten ikke skal skrive noe til fil allikevel så jeg fjerner hele funksjonen. Og går igjennom resten av koden for å validere at alle return types er satt.

2021-11-23 07:28 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/helpers/filewriter.py
> +def write_to_file(close_dataset_response: dict, target_path: str):
done

2021-11-23 07:28 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/main.py
> +                f"IAM_SECRET_ACCESS_KEY={settings.iam_secret_access_key}")
done

2021-11-23 07:28 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_secret_access_key=settings.iam_secret_access_key
done

2021-11-23 07:29 UTC, ComputasSnorriEngen commented on iam-close-dataset/tests/web/test_bevaring_client.py
> +dotenv_path = get_project_root() / ".env.test"
Done

2021-11-23 07:39 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +def close_dataset(client) -> None:
done

2021-11-23 07:46 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/web/bevaring_client.py
> +        self.url = bevaring_arkiv_service_host
done

2021-11-23 08:08 UTC, thomjah-computas commented on iam-close-dataset/app/web/bevaring_client.py
> +        self.url = bevaring_arkiv_service_host
Nå var det self.url jeg refererte til

2021-11-23 08:12 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/web/bevaring_client.py
> +        self.url = bevaring_arkiv_service_host
hm. den er jo satt som <protokoll><host> i env-filene også så om den skal hete base_url her så bør det jo gjelde alle steder?

2021-11-23 08:53 UTC, omBratteng requested changes

2021-11-23 08:53 UTC, omBratteng commented on .github/dependabot.yaml
> +      interval: "daily"
mangler newline

2021-11-23 08:54 UTC, omBratteng commented on iam-close-dataset/app/services/bevaring_service.py
> +from app.web.bevaring_client import BevaringArkivServiceClient
jeg vil si `app.connector` er bedre en `app.web`

2021-11-23 08:55 UTC, omBratteng commented on iam-close-dataset/app/services/bevaring_service.py
> +from app.web.bevaring_client import BevaringArkivServiceClient
Og da vil den være overens med hva vi har kalt slike connectors i andre komponenter

2021-11-23 09:17 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +from app.web.bevaring_client import BevaringArkivServiceClient
Notert. Fikk ingen kommentar på det på PR for iam-open-dataset, gjorde derfor det samme her. Viktigste er som du sier at det stemmer overens på tvers av komponenter. Jeg fikser det her OG på iam-open-dataset

2021-11-23 09:18 UTC, omBratteng commented on iam-close-dataset/app/services/bevaring_service.py
> +from app.web.bevaring_client import BevaringArkivServiceClient
Så det i `iam-open-dataset`, men glemte å kommentere på det.

2021-11-23 11:34 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +from app.web.bevaring_client import BevaringArkivServiceClient
done + refactorering av `iam-open-dataset`

2021-11-23 11:38 UTC, ComputasSnorriEngen commented on .github/dependabot.yaml
> +      interval: "daily"
done

2021-11-25 14:41 UTC, elmgren requested changes

2021-11-25 14:41 UTC, elmgren commented on iam-close-dataset/README.md
> +TODO: Insert link to docker-compose directory.
Skal denne todo gjøres nå?

2021-11-25 14:41 UTC, elmgren commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
trenger å legge til `client_name` her slik at det kan loggføres i audit databasen. 
Vil bli implementert i MOL-766

2021-11-25 14:41 UTC, elmgren commented on iam-close-dataset/app/helpers/settings.py
> +from uuid import UUID
fjern ubrukt import

2021-11-25 14:41 UTC, elmgren commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_access_key_id=settings.iam_access_key_id
sette client_name her?

2021-11-25 14:41 UTC, elmgren commented on iam-close-dataset/tests/web/mock_bevaring_client.py
> +from httpx import codes
Endre navn på mappen `web` -> `connectors` her også

2021-11-25 14:45 UTC, elmgren commented on iam-open-dataset/app/helpers/filewriter.py
> +import json
Fjern ubrukt import

2021-11-26 09:19 UTC, ComputasSnorriEngen commented on iam-close-dataset/README.md
> +TODO: Insert link to docker-compose directory.
Den er avhengig av om vi velger å merge devtools/docker-compose inn i prosjektet.
https://github.com/arkivverket/mottak/pull/962

2021-11-26 10:06 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/web/bevaring_client.py
> +        self.url = bevaring_arkiv_service_host
nvm. done

2021-11-26 10:07 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/helpers/settings.py
> +from uuid import UUID
done

2021-11-26 10:07 UTC, ComputasSnorriEngen commented on iam-close-dataset/tests/web/mock_bevaring_client.py
> +from httpx import codes
done

2021-11-26 10:07 UTC, ComputasSnorriEngen commented on iam-open-dataset/app/helpers/filewriter.py
> +import json
Done

2021-11-26 10:07 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Ok, da må vel det gjøres for iam-open-dataset også?

2021-11-26 11:03 UTC, omBratteng commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Kanskje det kan endres i MOL-766?

2021-11-26 11:29 UTC, thomjah-computas commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Close-endepunktet tar vel ikke inn client_name i dag? Bør kanskje gjøre det for sin egen audit-log-rad?

2021-11-26 15:10 UTC, elmgren commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
MOL-766 ligger i kontekst av bevaring og ikke mottak så jeg synes egentlig at det bør gjøres her. 

Ja @thomjah-computas, det skal som du skriver legges til for sin egen audit-log-rad i MOL-766

2021-11-26 15:11 UTC, elmgren commented on iam-close-dataset/README.md
> +TODO: Insert link to docker-compose directory.
Da lukker jeg denne saken for å ikke blokkere oppgaven. Dette kan fikses samtidig som #962

2021-11-26 15:27 UTC, omBratteng commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Skulle bare sjekke at du var klar over at MOL-766 er i bevaring og ikke i mottak 😅  😝

2021-11-29 09:49 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
done. Skal jeg ta iam-open-dataset i denne oppgaven, eller hører det heller hjemme i MOL-766? (Selv om den tilhører bevaring9

2021-11-29 09:50 UTC, ComputasSnorriEngen commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_access_key_id=settings.iam_access_key_id
Jeg satt den i CloseDatasetRequest: `client_name: str = "iam-close-dataset"` om det er en grei måte å gjøre det på så er det ikke nødvendig å gjøre noe her.

2021-11-30 07:37 UTC, thomjah-computas commented on iam-close-dataset/app/services/bevaring_service.py
> +        iam_access_key_id=settings.iam_access_key_id
Kanskje det er mer logisk å regne hele workflowen som én klient, istedenfor hvert Docker-steg?

2021-11-30 07:39 UTC, omBratteng commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Det er opp til deg og @elmgren tenker jeg. En task kan gå på tvers av repoer, eks. når en må legge inn nye env variabler i k8s config.

2021-11-30 07:42 UTC, thomjah-computas commented on iam-close-dataset/app/domain/models.py
> +    iam_access_key_id: str
Trenger ikke å gjøre det vanskeligere enn det er. @elmgren kan ta imot i MOL-766, så kan @ComputasSnorriEngen sende det i denne branchen her.

2021-11-30 14:14 UTC, elmgren approved these changes

2021-11-30 15:45 UTC, omBratteng approved these changes

2021-11-30 15:47 UTC, thomjah-computas approved these changes

2021-11-30 15:50 UTC, merged