MOL-789 Use new service bus policies in `tusd`
arkivverket/mottak pull request #986
Opened 2021-12-03 12:46 UTC by omBratteng

2021-12-03 15:36 UTC, elmgren requested changes

2021-12-03 15:36 UTC, elmgren commented on tusd/README.md
>  AZURE_STORAGE_KEY=<Azure Blob Storage account key>
Ser at vi bruker BASE_PATH i start.sh men vi sender ikke inn den i mottak-k8s-config.

Trenger vi den? Hvis ja, bør vi skrive inn noe om den her

2021-12-03 15:36 UTC, elmgren commented on tusd/hooks/implementations/post_finish.py
> +    conn_str = os.getenv('AZURE_SERVICE_BUS_SENDER_CONNECTION_STRING')
Ta i bruk Settings()?

2021-12-06 12:09 UTC, omBratteng commented on tusd/README.md
>  AZURE_STORAGE_KEY=<Azure Blob Storage account key>
Har dokumentert env variable i README

2021-12-06 14:50 UTC, elmgren requested changes

2021-12-06 14:50 UTC, elmgren commented on tusd/hooks/implementations/hooks_utils.py
>      # Enable this when debugging the events. It dumps the input to /tmp so you can re-run the hook with stdin.
Skal vi bare slette denne kommentaren?

2021-12-06 14:50 UTC, elmgren commented on tusd/hooks/implementations/hooks_utils.py
> +def map_to_hook_data(tusd_data: TusEvent, logger: logging.Logger) -> HookData:
rename: tusd_data -> tus_event

2021-12-06 14:50 UTC, elmgren commented on tusd/hooks/implementations/pre_create.py
>      tusd_data = _read_tusd_pre_create_event()
rename: tusd_data -> tus_event

2021-12-06 15:18 UTC, elmgren approved these changes

2021-12-06 15:18 UTC, merged